import { supabase } from '@/lib/supabase';
import logger from '@/utils/logger';
import type { Classroom, ClassroomWithMembers, ClassroomStudent, VocabularyLevel } from './types';
import { isVocabularyLevel } from '@/lib/education/differentiation';

/**
 * Get all classrooms for a teacher
 */
export async function getClassrooms(teacherId: string): Promise<{ data: ClassroomWithMembers[]; error: { message: string } | null }> {
  if (!supabase) return { data: [], error: { message: 'Supabase not configured' } };

  try {
    // Get classrooms with member count
    const { data: classrooms, error: classroomsError } = await supabase
      .from('classrooms')
      .select('*')
      .eq('teacher_id', teacherId)
      .order('created_at', { ascending: false });

    if (classroomsError) {
      logger.error('Error fetching classrooms:', classroomsError);
      return { data: [], error: { message: classroomsError.message } };
    }

    if (!classrooms || classrooms.length === 0) {
      return { data: [], error: null };
    }

    // Get member counts for all classrooms in one query
    const { data: memberships, error: membershipsError } = await supabase
      .from('classroom_memberships')
      .select('classroom_id')
      .in('classroom_id', classrooms.map(c => c.id));

    if (membershipsError) {
      logger.error('Error fetching memberships:', membershipsError);
      // Return classrooms without member counts rather than failing
      return {
        data: classrooms.map(c => ({ ...c, member_count: 0 })),
        error: null
      };
    }

    // Count members per classroom
    const memberCounts = (memberships || []).reduce((acc, m) => {
      acc[m.classroom_id] = (acc[m.classroom_id] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    // Attach member counts
    const classroomsWithCounts = classrooms.map(classroom => ({
      ...classroom,
      member_count: memberCounts[classroom.id] || 0
    }));

    return { data: classroomsWithCounts, error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in getClassrooms:', error);
    return { data: [], error: { message: error } };
  }
}

/**
 * Get a single classroom by ID
 */
export async function getClassroom(classroomId: string): Promise<{ data: ClassroomWithMembers | null; error: { message: string } | null }> {
  if (!supabase) return { data: null, error: { message: 'Supabase not configured' } };

  try {
    const { data: classroom, error: classroomError } = await supabase
      .from('classrooms')
      .select('*')
      .eq('id', classroomId)
      .single();

    if (classroomError) {
      logger.error('Error fetching classroom:', classroomError);
      return { data: null, error: { message: classroomError.message } };
    }

    // Get member count
    const { count, error: countError } = await supabase
      .from('classroom_memberships')
      .select('*', { count: 'exact', head: true })
      .eq('classroom_id', classroomId);

    if (countError) {
      logger.error('Error counting members:', countError);
      return { data: { ...classroom, member_count: 0 }, error: null };
    }

    return { data: { ...classroom, member_count: count || 0 }, error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in getClassroom:', error);
    return { data: null, error: { message: error } };
  }
}

/**
 * Create a new classroom (join_code auto-generated by trigger)
 */
export async function createClassroom(
  data: Omit<Classroom, 'id' | 'join_code' | 'created_at' | 'updated_at' | 'member_count'>
): Promise<{ data: Classroom | null; error: { message: string } | null }> {
  if (!supabase) return { data: null, error: { message: 'Supabase not configured' } };

  try {
    const { data: classroom, error } = await supabase
      .from('classrooms')
      .insert(data)
      .select()
      .single();

    if (error) {
      logger.error('Error creating classroom:', error);
      return { data: null, error: { message: error.message } };
    }

    return { data: classroom, error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in createClassroom:', error);
    return { data: null, error: { message: error } };
  }
}

/**
 * Update a classroom
 */
export async function updateClassroom(
  id: string,
  updates: Partial<Pick<Classroom, 'name' | 'language'>>
): Promise<{ data: Classroom | null; error: { message: string } | null }> {
  if (!supabase) return { data: null, error: { message: 'Supabase not configured' } };

  try {
    const { data: classroom, error } = await supabase
      .from('classrooms')
      .update(updates)
      .eq('id', id)
      .select()
      .single();

    if (error) {
      logger.error('Error updating classroom:', error);
      return { data: null, error: { message: error.message } };
    }

    return { data: classroom, error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in updateClassroom:', error);
    return { data: null, error: { message: error } };
  }
}

/**
 * Delete a classroom (cascades to memberships via foreign key)
 */
export async function deleteClassroom(id: string): Promise<{ error: { message: string } | null }> {
  if (!supabase) return { error: { message: 'Supabase not configured' } };

  try {
    const { error } = await supabase
      .from('classrooms')
      .delete()
      .eq('id', id);

    if (error) {
      logger.error('Error deleting classroom:', error);
      return { error: { message: error.message } };
    }

    return { error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in deleteClassroom:', error);
    return { error: { message: error } };
  }
}

/**
 * Join a classroom using join code
 */
export async function joinClassroom(
  joinCode: string,
  studentId: string
): Promise<{ data: { classroom_id: string } | null; error: { message: string } | null }> {
  if (!supabase) return { data: null, error: { message: 'Supabase not configured' } };

  try {
    // Normalize the join code (trim whitespace and uppercase)
    const normalizedCode = joinCode.trim().toUpperCase();

    // Validate code format BEFORE database query (fail fast)
    if (!normalizedCode || normalizedCode.length !== 6) {
      return { data: null, error: { message: 'Invalid join code format (must be 6 characters)' } };
    }

    if (!/^[A-Z0-9]+$/.test(normalizedCode)) {
      return { data: null, error: { message: 'Invalid join code format (letters and numbers only)' } };
    }

    // Find classroom by join code using secure RPC function
    // This prevents enumeration of all classrooms (security fix)
    const { data: classroomResult, error: classroomError } = await supabase
      .rpc('lookup_classroom_by_join_code', { p_join_code: normalizedCode });

    if (classroomError) {
      logger.error('Error querying classroom:', classroomError);
      return { data: null, error: { message: classroomError.message } };
    }

    // RPC returns an array, get the first result
    const classroom = Array.isArray(classroomResult) ? classroomResult[0] : classroomResult;

    if (!classroom) {
      // Classroom not found - clearer error message
      return { data: null, error: { message: 'Classroom not found. Please check the code with your teacher.' } };
    }

    // Check if already a member
    const { data: existing } = await supabase
      .from('classroom_memberships')
      .select('id')
      .eq('classroom_id', classroom.id)
      .eq('student_id', studentId)
      .maybeSingle();

    if (existing) {
      // Already a member - return success with classroom_id
      return { data: { classroom_id: classroom.id }, error: null };
    }

    // Add membership
    const { error: membershipError } = await supabase
      .from('classroom_memberships')
      .insert({
        classroom_id: classroom.id,
        student_id: studentId
      });

    if (membershipError) {
      logger.error('Error joining classroom:', membershipError);
      return { data: null, error: { message: membershipError.message } };
    }

    return { data: { classroom_id: classroom.id }, error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in joinClassroom:', error);
    return { data: null, error: { message: error } };
  }
}

/**
 * Get student's classroom from their membership
 *
 * Returns the classroom the student is a member of, or null if not a member of any.
 * If a student is a member of multiple classrooms, returns the most recently joined.
 */
export async function getStudentClassroom(
  studentId: string
): Promise<{ data: Classroom | null; level: VocabularyLevel; error: { message: string } | null }> {
  if (!supabase) return { data: null, level: 'core', error: { message: 'Supabase not configured' } };

  try {
    // Query membership with joined classroom info, ordered by join date (most recent first)
    const { data: membership, error: membershipError } = await supabase
      .from('classroom_memberships')
      // Own columns as `*` for the same reason as the roster read above: a named
      // `level` fails the read outright when the column is not there yet.
      .select(`
        *,
        classrooms (
          id,
          teacher_id,
          name,
          join_code,
          language,
          created_at,
          updated_at
        )
      `)
      .eq('student_id', studentId)
      .order('joined_at', { ascending: false })
      .limit(1)
      .maybeSingle();

    if (membershipError) {
      logger.error('Error fetching student classroom:', membershipError);
      return { data: null, level: 'core', error: { message: membershipError.message } };
    }

    if (!membership || !membership.classrooms) {
      return { data: null, level: 'core', error: null };
    }

    // Extract classroom from the nested structure
    const classroom = membership.classrooms as unknown as Classroom;
    // `level` is the student's OWN differentiation tier in THIS classroom (their own
    // row is readable under "Students can view own memberships"). Pre-migration rows
    // and test doubles have no column — treat as core, never as undefined.
    const level = coerceLevel((membership as { level?: unknown }).level);

    return { data: classroom, level, error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in getStudentClassroom:', error);
    return { data: null, level: 'core', error: { message: error } };
  }
}

/**
 * Get all students in a classroom with their profile information
 */
export async function getClassroomStudents(
  classroomId: string
): Promise<{ data: ClassroomStudent[]; error: { message: string } | null }> {
  if (!supabase) return { data: [], error: { message: 'Supabase not configured' } };

  try {
    // First, get all memberships for this classroom
    const { data: memberships, error: membershipError } = await supabase
      .from('classroom_memberships')
      // `*`, not a named list: naming `level` makes the whole roster read fail on
      // a database that has not received 20260905130000 yet (the migration
      // workflow can lag the deploy). Absent → `core` via coerceLevel below.
      .select('*')
      .eq('classroom_id', classroomId)
      .order('joined_at', { ascending: true });

    if (membershipError) {
      logger.error('Error fetching classroom memberships:', membershipError);
      return { data: [], error: { message: membershipError.message } };
    }

    if (!memberships || memberships.length === 0) {
      return { data: [], error: null };
    }

    // Then, fetch profiles for all student_ids.
    // public_profiles.id = profiles.id = auth.users.id = classroom_memberships.student_id
    //
    // Read through `public_profiles`, NOT `profiles`: RLS on profiles is own-row-only, so a
    // teacher querying it for their own students gets 0 rows with error:null and every
    // student renders nameless with a permanent avatar skeleton. See
    // __tests__/studentProfileReads.test.ts.
    const studentIds = memberships.map(m => m.student_id);
    const { data: profiles, error: profilesError } = await supabase
      .from('public_profiles')
      // `display_name` as well as `username`: `username` defaults to the DB placeholder
      // `'Player_' || substr(id, 1, 8)`, so a roster built on it alone showed a teacher
      // "Player_570b3674" for a student whose display_name said "Victoria Delong".
      // Callers resolve with `resolveDisplayName([display_name, username], fallback)`.
      .select('id, username, display_name, avatar_config')
      .in('id', studentIds);

    if (profilesError) {
      logger.error('Error fetching student profiles:', profilesError);
      // Return memberships without profile data rather than failing completely
    }

    // Create a map of profiles by id for quick lookup
    const profileMap = new Map((profiles || []).map(p => [p.id, p]));

    // Combine memberships with their profiles
    const studentsWithProfiles = memberships.map(membership => ({
      ...membership,
      level: coerceLevel((membership as { level?: unknown }).level),
      profiles: profileMap.get(membership.student_id) || null,
    }));

    return { data: studentsWithProfiles as ClassroomStudent[], error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in getClassroomStudents:', error);
    return { data: [], error: { message: error } };
  }
}

/** Unknown/absent → core. The DB CHECK guarantees the value, but old rows and mocks may lack the column. */
function coerceLevel(value: unknown): VocabularyLevel {
  return isVocabularyLevel(value) ? value : 'core';
}

/**
 * Set a student's differentiation level in a classroom (teacher-owner only).
 *
 * Goes through the API route rather than a direct table write: the update must run
 * on the service role and assert one row changed — under RLS a direct client update
 * that matches nothing returns error:null and looks like success.
 */
export async function setStudentLevel(
  classroomId: string,
  studentId: string,
  level: VocabularyLevel
): Promise<{ error: { message: string } | null }> {
  try {
    const response = await fetch(
      `/api/education/classroom/${encodeURIComponent(classroomId)}/members/${encodeURIComponent(studentId)}`,
      {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ level }),
      }
    );
    if (!response.ok) {
      let message = `Failed to update level (${response.status})`;
      try {
        const data = await response.json();
        if (typeof data?.error === 'string') message = data.error;
      } catch { /* non-JSON error body */ }
      return { error: { message } };
    }
    return { error: null };
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Failed to update level';
    logger.error('Exception in setStudentLevel:', message);
    return { error: { message } };
  }
}
