/**
 * Curated COMMON words for crossword seed generation. The game's main dictionary is a Boggle
 * validity list (415k EN words incl. obscure/archaic) — great for solvability, terrible for a
 * clueable, fun crossword. The CSP is fed THIS pool instead so generated grids contain words
 * players actually know. Every word here is also validated against the real dictionary at
 * generation time, so nothing un-submittable can appear.
 *
 * Keep entries common, neutral, 3–5 letters. Extend freely.
 */

export const COMMON_EN: string[] = [
  // 3
  'cat', 'dog', 'sun', 'sea', 'sky', 'ice', 'art', 'ace', 'arm', 'ear',
  'eat', 'tea', 'ten', 'net', 'nap', 'map', 'tap', 'top', 'pot', 'pet',
  'pen', 'pan', 'pin', 'pie', 'tie', 'toe', 'oak', 'owl', 'ant', 'bee',
  'bat', 'bar', 'bad', 'bag', 'big', 'bus', 'cup', 'car', 'cap', 'cab',
  'cow', 'dot', 'day', 'dry', 'ear', 'egg', 'elf', 'end', 'fan', 'far',
  'fig', 'fit', 'fox', 'fun', 'gas', 'gem', 'gum', 'hat', 'hen', 'hot',
  'ink', 'jam', 'jar', 'jet', 'key', 'kid', 'kit', 'lap', 'leg', 'lip',
  'log', 'mad', 'man', 'mat', 'mud', 'mug', 'nut', 'oar', 'oat', 'odd',
  'oil', 'one', 'owe', 'pad', 'paw', 'pea', 'pig', 'ear', 'rag', 'ram',
  'rat', 'red', 'rib', 'rim', 'rip', 'rod', 'row', 'rug', 'run', 'sad',
  'sit', 'six', 'ski', 'sob', 'son', 'spa', 'sum', 'tag', 'tan', 'tar',
  'tax', 'toy', 'tub', 'van', 'wax', 'web', 'wet', 'wig', 'win', 'yak',
  'yes', 'zip', 'zoo', 'are', 'eve', 'ore', 'use', 'age', 'ago', 'aid',
  'aim', 'air', 'ash', 'ask', 'bay', 'bed', 'bet', 'bin', 'bit', 'bow',
  'box', 'boy', 'cut', 'den', 'dim', 'dip', 'ebb', 'elk', 'era', 'fin',
  // 4
  'lake', 'rain', 'snow', 'star', 'moon', 'tree', 'leaf', 'rose', 'fish', 'bird',
  'bear', 'lion', 'wolf', 'frog', 'deer', 'goat', 'duck', 'crab', 'seal', 'mole',
  'cake', 'milk', 'rice', 'soup', 'corn', 'bean', 'pear', 'plum', 'lime', 'mint',
  'door', 'roof', 'wall', 'desk', 'lamp', 'sofa', 'bowl', 'fork', 'cup', 'dish',
  'road', 'park', 'shop', 'café', 'farm', 'city', 'town', 'home', 'room', 'gate',
  'blue', 'pink', 'gold', 'grey', 'ruby', 'jade', 'teal', 'cyan',
  'open', 'shut', 'fast', 'slow', 'cold', 'warm', 'soft', 'hard', 'good', 'kind',
  'cool', 'calm', 'busy', 'easy', 'tidy', 'neat', 'rich', 'wise', 'bold', 'glad',
  'walk', 'jump', 'swim', 'read', 'sing', 'cook', 'draw', 'play', 'work', 'rest',
  'gift', 'note', 'song', 'tale', 'poem', 'film', 'game', 'team', 'goal', 'race',
  'time', 'date', 'week', 'year', 'noon', 'dawn', 'dusk', 'tide', 'wave', 'wind',
  'east', 'west', 'main', 'edge', 'core', 'peak', 'path', 'trip', 'tour', 'ride',
  'idea', 'plan', 'fact', 'rule', 'name', 'word', 'page', 'line', 'list', 'menu',
  // 5
  'apple', 'grape', 'lemon', 'mango', 'peach', 'berry', 'melon', 'olive', 'onion', 'wheat',
  'beach', 'cloud', 'river', 'ocean', 'storm', 'field', 'grass', 'plant', 'stone', 'earth',
  'tiger', 'horse', 'sheep', 'mouse', 'snake', 'whale', 'shark', 'eagle', 'robin', 'zebra',
  'chair', 'table', 'house', 'plate', 'spoon', 'clock', 'phone', 'piano', 'brush', 'knife',
  'happy', 'green', 'white', 'black', 'brown', 'sweet', 'fresh', 'clean', 'quiet', 'brave',
  'smile', 'laugh', 'dance', 'dream', 'paint', 'write', 'learn', 'teach', 'build', 'climb',
  'water', 'light', 'music', 'sound', 'color', 'space', 'world', 'place', 'story', 'image',
  'north', 'south', 'today', 'night', 'month', 'first', 'third', 'sixth', 'early', 'later',
  'heart', 'brain', 'hands', 'voice', 'sense', 'power', 'magic', 'peace', 'truth', 'trust',
  'train', 'plane', 'truck', 'wheel', 'route', 'cabin', 'tower', 'house', 'plaza', 'court',
  // --- enrichment batch (common, cluable; non-dictionary entries are dropped at gen time) ---
  // 3
  'all', 'and', 'any', 'ate', 'bee', 'cob', 'cot', 'cry', 'cue', 'cut', 'dad', 'dew', 'die',
  'dig', 'dot', 'due', 'dye', 'eel', 'elm', 'eye', 'fed', 'fee', 'few', 'fig', 'fir', 'fix',
  'fly', 'foe', 'fog', 'for', 'fox', 'fry', 'gap', 'get', 'god', 'got', 'gum', 'gun', 'gut',
  'guy', 'had', 'ham', 'has', 'hay', 'her', 'hid', 'him', 'hip', 'hit', 'hog', 'hop', 'hub',
  'hue', 'hug', 'hum', 'ice', 'icy', 'ill', 'ink', 'ion', 'ivy', 'jaw', 'jay', 'job', 'jog',
  'joy', 'jug', 'key', 'kit', 'lab', 'lad', 'law', 'led', 'let', 'lid', 'lie', 'lip', 'lit',
  'log', 'lot', 'low', 'mad', 'map', 'mat', 'mob', 'mop', 'mud', 'mug', 'nap', 'net', 'new',
  'nod', 'now', 'nut', 'oak', 'oar', 'oat', 'odd', 'oil', 'old', 'one', 'orb', 'our', 'out',
  'owl', 'own', 'pad', 'pan', 'paw', 'pea', 'pen', 'pet', 'pie', 'pig', 'pin', 'pit', 'pod',
  'pot', 'pub', 'pup', 'rag', 'ram', 'rat', 'raw', 'ray', 'red', 'rib', 'rim', 'rip', 'rob',
  'rod', 'row', 'rub', 'rug', 'run', 'sad', 'sap', 'saw', 'sea', 'set', 'she', 'shy', 'sin',
  'sip', 'sir', 'sit', 'six', 'ski', 'sky', 'sly', 'sob', 'son', 'sow', 'soy', 'spa', 'spy',
  'sub', 'sue', 'sum', 'sun', 'tab', 'tag', 'tan', 'tap', 'tar', 'tax', 'tea', 'ten', 'the',
  'tie', 'tin', 'tip', 'toe', 'ton', 'too', 'top', 'tow', 'toy', 'try', 'tub', 'two', 'urn',
  'use', 'van', 'vet', 'vow', 'war', 'wax', 'way', 'web', 'wed', 'wet', 'who', 'why', 'wig',
  'win', 'wit', 'woe', 'won', 'yak', 'yam', 'yes', 'yet', 'you', 'zip', 'zoo',
  // 4
  'army', 'baby', 'bake', 'ball', 'band', 'bank', 'bare', 'bark', 'barn', 'base', 'bath',
  'bead', 'beam', 'bean', 'bear', 'beat', 'beef', 'bell', 'belt', 'bend', 'best', 'bike',
  'bill', 'bird', 'bite', 'blow', 'blue', 'boat', 'body', 'boil', 'bold', 'bolt', 'bone',
  'book', 'boot', 'born', 'boss', 'bowl', 'brew', 'buck', 'bulb', 'bump', 'burn', 'bush',
  'busy', 'cage', 'cake', 'calf', 'call', 'calm', 'camp', 'cane', 'cape', 'card', 'care',
  'cart', 'case', 'cash', 'cast', 'cave', 'cell', 'chat', 'chef', 'chew', 'chin', 'chip',
  'city', 'clap', 'claw', 'clay', 'clip', 'club', 'clue', 'coal', 'coat', 'code', 'coin',
  'cold', 'comb', 'cook', 'cool', 'cope', 'copy', 'cord', 'core', 'cork', 'corn', 'cost',
  'crab', 'crew', 'crop', 'crow', 'cube', 'cure', 'dale', 'dame', 'damp', 'dare', 'dark',
  'dart', 'dash', 'date', 'dawn', 'deal', 'dear', 'deck', 'deep', 'deer', 'desk', 'dial',
  'dice', 'diet', 'dime', 'dine', 'dirt', 'dish', 'dive', 'dock', 'doll', 'dome', 'done',
  'door', 'dose', 'dove', 'down', 'drag', 'draw', 'drip', 'drop', 'drum', 'duck', 'dull',
  'dusk', 'dust', 'duty', 'each', 'earl', 'earn', 'ease', 'east', 'easy', 'echo', 'edge',
  'face', 'fact', 'fade', 'fail', 'fair', 'fall', 'fame', 'farm', 'fast', 'fate', 'fear',
  'feed', 'feel', 'fern', 'file', 'fill', 'film', 'find', 'fine', 'fire', 'firm', 'fist',
  'flag', 'flat', 'flaw', 'flea', 'flew', 'flip', 'flop', 'flow', 'foam', 'fold', 'folk',
  'fond', 'food', 'fool', 'foot', 'fork', 'form', 'fort', 'four', 'fowl', 'frog', 'fuel',
  'full', 'fund', 'fuse', 'gain', 'gale', 'game', 'gang', 'gate', 'gaze', 'gear', 'gift',
  'girl', 'give', 'glad', 'glow', 'glue', 'goal', 'goat', 'gold', 'golf', 'gone', 'gown',
  'grab', 'gray', 'grew', 'grid', 'grim', 'grin', 'grip', 'grow', 'gulf', 'gull', 'hail',
  'hair', 'half', 'hall', 'halo', 'halt', 'hand', 'hang', 'hard', 'hare', 'harm', 'harp',
  'hate', 'haul', 'have', 'hawk', 'haze', 'head', 'heal', 'heap', 'hear', 'heat', 'heel',
  'help', 'herb', 'herd', 'hero', 'hide', 'high', 'hike', 'hill', 'hint', 'hire', 'hive',
  'hold', 'hole', 'holy', 'home', 'hood', 'hoof', 'hook', 'hope', 'horn', 'hose', 'host',
  'hour', 'howl', 'hunt', 'hurt', 'icon', 'iris', 'iron', 'isle', 'item', 'jade', 'jail',
  'jazz', 'jeep', 'join', 'joke', 'jump', 'junk', 'jury', 'just', 'keen', 'keep', 'kelp',
  'kept', 'kick', 'kind', 'king', 'kiss', 'kite', 'knee', 'knit', 'knot', 'know', 'lace',
  'lack', 'lady', 'laid', 'lake', 'lamb', 'lamp', 'land', 'lane', 'lark', 'lava', 'lawn',
  'lazy', 'lead', 'leaf', 'leak', 'lean', 'leap', 'left', 'lend', 'lens', 'lion', 'list',
  'live', 'load', 'loaf', 'loan', 'lock', 'loft', 'lone', 'long', 'look', 'loop', 'lord',
  'lose', 'loss', 'lost', 'loud', 'love', 'luck', 'lump', 'lung', 'lure', 'mail', 'main',
  'make', 'male', 'mall', 'mane', 'many', 'mare', 'mark', 'mash', 'mask', 'mast', 'mate',
  'maze', 'meal', 'mean', 'meat', 'meet', 'melt', 'menu', 'mere', 'mesh', 'mild', 'mile',
  'mind', 'mine', 'mint', 'mist', 'moat', 'mode', 'mold', 'monk', 'mood', 'moon', 'moss',
  'most', 'moth', 'move', 'much', 'mule', 'muse', 'must', 'myth', 'nail', 'name', 'navy',
  'neat', 'neck', 'need', 'nest', 'news', 'next', 'nice', 'nine', 'node', 'noon', 'norm',
  'nose', 'note', 'noun', 'nude', 'oath', 'obey', 'odor', 'okay', 'omen', 'once', 'only',
  'onto', 'open', 'oral', 'oval', 'oven', 'over', 'page', 'paid', 'pail', 'pain', 'pair',
  'pale', 'palm', 'pane', 'park', 'part', 'pass', 'past', 'path', 'pave', 'pawn', 'peak',
  'pear', 'peel', 'peer', 'pest', 'pick', 'pier', 'pile', 'pill', 'pine', 'pink', 'pipe',
  'plan', 'play', 'plot', 'plow', 'plug', 'plum', 'plus', 'poem', 'poet', 'poke', 'pole',
  'poll', 'pond', 'pony', 'pool', 'poor', 'pore', 'pork', 'port', 'pose', 'post', 'pour',
  'pray', 'prey', 'prop', 'pull', 'pulp', 'pump', 'pure', 'push', 'quit', 'quiz', 'race',
  'rack', 'raft', 'rage', 'raid', 'rail', 'rake', 'ramp', 'rank', 'rant', 'rare', 'rash',
  'rate', 'rave', 'read', 'real', 'reap', 'rear', 'reed', 'reef', 'reel', 'rely', 'rent',
  'rice', 'rich', 'ride', 'ring', 'ripe', 'rise', 'risk', 'road', 'roam', 'roar', 'robe',
  'rock', 'role', 'roll', 'roof', 'room', 'root', 'rope', 'rose', 'ruby', 'rude', 'ruin',
  'rule', 'rush', 'rust', 'sack', 'safe', 'sage', 'sail', 'sake', 'sale', 'salt', 'same',
  'sand', 'save', 'scan', 'scar', 'seal', 'seam', 'seat', 'seed', 'seek', 'seem', 'seen',
  'self', 'sell', 'send', 'shed', 'shin', 'ship', 'shoe', 'shop', 'shot', 'show', 'shut',
  'sick', 'side', 'sigh', 'sign', 'silk', 'sing', 'sink', 'site', 'size', 'skin', 'skip',
  'slam', 'slap', 'sled', 'slim', 'slip', 'slot', 'slow', 'snap', 'snow', 'soak', 'soap',
  'soar', 'sock', 'soda', 'sofa', 'soft', 'soil', 'sold', 'sole', 'solo', 'song', 'soon',
  'sore', 'sort', 'soul', 'soup', 'sour', 'span', 'spin', 'spot', 'star', 'stay', 'stem',
  'step', 'stew', 'stop', 'such', 'suit', 'sung', 'sure', 'surf', 'swam', 'swan', 'swap',
  'swim', 'tail', 'take', 'tale', 'talk', 'tall', 'tame', 'tank', 'tape', 'task', 'taxi',
  'team', 'tear', 'tell', 'tend', 'tent', 'term', 'test', 'text', 'than', 'that', 'thaw',
  'them', 'then', 'they', 'thin', 'this', 'tide', 'tidy', 'tier', 'tile', 'tilt', 'time',
  'tiny', 'tire', 'toad', 'tofu', 'toll', 'tomb', 'tone', 'tool', 'tore', 'torn', 'toss',
  'tour', 'town', 'trap', 'tray', 'tree', 'trim', 'trio', 'trip', 'true', 'tube', 'tuck',
  'tuna', 'tune', 'turf', 'turn', 'twin', 'type', 'ugly', 'undo', 'unit', 'upon', 'urge',
  'vain', 'vane', 'vary', 'vase', 'vast', 'veal', 'veil', 'vein', 'vent', 'verb', 'very',
  'vest', 'veto', 'vibe', 'vice', 'view', 'vine', 'visa', 'void', 'volt', 'vote', 'wade',
  'wage', 'wail', 'wait', 'wake', 'walk', 'wall', 'wand', 'want', 'ward', 'warm', 'warn',
  'wash', 'wasp', 'wave', 'weak', 'wear', 'weed', 'week', 'weep', 'well', 'went', 'were',
  'west', 'what', 'when', 'whip', 'wide', 'wife', 'wild', 'will', 'wind', 'wine', 'wing',
  'wink', 'wipe', 'wire', 'wise', 'wish', 'with', 'wolf', 'womb', 'wood', 'wool', 'word',
  'wore', 'work', 'worm', 'worn', 'wrap', 'wren', 'yard', 'yarn', 'yawn', 'year', 'yell',
  'yoga', 'yolk', 'your', 'zero', 'zest', 'zone', 'zoom',
  // 5
  'about', 'above', 'actor', 'acute', 'admit', 'adopt', 'adore', 'adult', 'agent', 'agile',
  'ahead', 'alarm', 'album', 'alert', 'alien', 'alike', 'alive', 'alley', 'allow', 'alone',
  'along', 'aloud', 'alpha', 'altar', 'alter', 'amber', 'amend', 'ample', 'angel', 'anger',
  'angle', 'angry', 'ankle', 'apple', 'apron', 'arena', 'argue', 'arise', 'armor', 'aroma',
  'array', 'arrow', 'aside', 'asset', 'atlas', 'attic', 'audio', 'avoid', 'await', 'awake',
  'award', 'aware', 'awful', 'bacon', 'badge', 'badly', 'bagel', 'baker', 'basic', 'basil',
  'basin', 'batch', 'beach', 'beard', 'beast', 'began', 'begin', 'being', 'belly', 'below',
  'bench', 'berry', 'bingo', 'birch', 'birth', 'black', 'blade', 'blame', 'bland', 'blank',
  'blast', 'blaze', 'bleak', 'blend', 'bless', 'blind', 'blink', 'block', 'blond', 'blood',
  'bloom', 'blown', 'bluff', 'blunt', 'blush', 'board', 'boast', 'bonus', 'boost', 'booth',
  'bound', 'boxer', 'brace', 'braid', 'brain', 'brake', 'brand', 'brave', 'bread', 'break',
  'breed', 'brick', 'bride', 'brief', 'bring', 'brink', 'brisk', 'broad', 'broke', 'brook',
  'broom', 'broth', 'brown', 'brush', 'build', 'built', 'bulky', 'bunch', 'bunny', 'burst',
  'cabin', 'cable', 'cache', 'cameo', 'canal', 'candy', 'canoe', 'cargo', 'carol', 'carve',
  'catch', 'cause', 'cease', 'cedar', 'chain', 'chair', 'chalk', 'chant', 'chaos', 'charm',
  'chart', 'chase', 'cheap', 'cheat', 'check', 'cheek', 'cheer', 'chess', 'chest', 'chief',
  'child', 'chili', 'chill', 'chime', 'chirp', 'choir', 'choke', 'chord', 'chose', 'chunk',
  'churn', 'cider', 'cigar', 'civil', 'claim', 'clamp', 'clash', 'clasp', 'class', 'clean',
  'clear', 'clerk', 'click', 'cliff', 'climb', 'cling', 'cloak', 'clock', 'clone', 'close',
  'cloth', 'cloud', 'clout', 'clove', 'clown', 'clump', 'coach', 'coast', 'cobra', 'cocoa',
  'comet', 'comic', 'comma', 'coral', 'couch', 'cough', 'could', 'count', 'court', 'cover',
  'crack', 'craft', 'cramp', 'crane', 'crank', 'crash', 'crate', 'crave', 'crawl', 'crazy',
  'cream', 'creek', 'creep', 'crept', 'crest', 'cried', 'crime', 'crisp', 'croak', 'crook',
  'cross', 'crowd', 'crown', 'crude', 'cruel', 'crumb', 'crush', 'crust', 'cubic', 'curly',
  'curry', 'curse', 'curve', 'cycle', 'daily', 'dairy', 'daisy', 'dance', 'dandy', 'dealt',
  'death', 'debut', 'decay', 'decoy', 'delay', 'delta', 'demon', 'denim', 'dense', 'depth',
  'devil', 'diary', 'digit', 'diner', 'dingo', 'dirty', 'ditch', 'diver', 'dizzy', 'dodge',
  'dogma', 'donor', 'donut', 'doubt', 'dough', 'dozen', 'draft', 'drain', 'drama', 'drank',
  'drape', 'drawn', 'dread', 'dream', 'dress', 'dried', 'drift', 'drill', 'drink', 'drive',
  'drone', 'drove', 'drown', 'drunk', 'dryer', 'dusky', 'dusty', 'dwarf', 'dwell', 'eager',
  'eagle', 'early', 'earth', 'easel', 'eaten', 'ebony', 'eight', 'elbow', 'elder', 'elect',
  'elite', 'elope', 'ember', 'empty', 'enact', 'enemy', 'enjoy', 'enter', 'entry', 'equal',
  'equip', 'erase', 'erupt', 'essay', 'ethic', 'evade', 'event', 'every', 'evoke', 'exact',
  'excel', 'exile', 'exist', 'extra', 'fable', 'faint', 'fairy', 'faith', 'false', 'fancy',
  'fatal', 'fault', 'fauna', 'favor', 'feast', 'fence', 'ferry', 'fetch', 'fever', 'fiber',
  'field', 'fiery', 'fifth', 'fifty', 'fight', 'final', 'finch', 'first', 'flair', 'flake',
  'flame', 'flank', 'flash', 'flask', 'fleet', 'flesh', 'flick', 'fling', 'flint', 'float',
  'flock', 'flood', 'floor', 'flora', 'flour', 'flown', 'fluid', 'flung', 'flush', 'flute',
  'foamy', 'focal', 'focus', 'foggy', 'force', 'forge', 'forth', 'forty', 'forum', 'found',
  'foyer', 'frame', 'frank', 'fraud', 'freak', 'fresh', 'fried', 'frill', 'frock', 'front',
  'frost', 'froth', 'frown', 'froze', 'fruit', 'fudge', 'fully', 'fungi', 'funny', 'furry',
  'fuzzy', 'gauge', 'gaunt', 'gavel', 'gazer', 'gecko', 'geese', 'genie', 'genre', 'ghost',
  'giant', 'giddy', 'given', 'giver', 'glade', 'gland', 'glare', 'glass', 'glaze', 'gleam',
  'glide', 'globe', 'gloom', 'glory', 'gloss', 'glove', 'gnome', 'going', 'goose', 'gorge',
  'gourd', 'grace', 'grade', 'grain', 'grand', 'grant', 'grape', 'graph', 'grasp', 'grass',
  'grate', 'grave', 'gravy', 'graze', 'great', 'greed', 'green', 'greet', 'grief', 'grill',
  'grime', 'grind', 'groan', 'groom', 'grove', 'growl', 'grown', 'gruff', 'grunt', 'guard',
  'guess', 'guest', 'guide', 'guild', 'guilt', 'gully', 'gusto', 'habit', 'hairy', 'halve',
  'handy', 'happy', 'hardy', 'harsh', 'haste', 'hasty', 'hatch', 'haunt', 'haven', 'havoc',
  'hazel', 'heart', 'heath', 'heave', 'heavy', 'hedge', 'hefty', 'hello', 'hence', 'heron',
  'hilly', 'hinge', 'hippo', 'hoard', 'hobby', 'hoist', 'honey', 'honor', 'horde', 'horse',
  'hotel', 'hound', 'house', 'hover', 'human', 'humid', 'humor', 'hunch', 'hurry', 'husky',
  'hydra', 'hyena', 'ideal', 'idiom', 'igloo', 'image', 'imply', 'inbox', 'index', 'inert',
  'infer', 'inlet', 'inner', 'input', 'intro', 'irony', 'issue', 'itchy', 'ivory', 'jaunt',
  'jelly', 'jewel', 'joint', 'joker', 'jolly', 'judge', 'juice', 'juicy', 'jumbo', 'jumpy',
  'kayak', 'kebab', 'khaki', 'kiosk', 'kitty', 'knack', 'knead', 'kneel', 'knife', 'knock',
  'knoll', 'known', 'koala', 'label', 'labor', 'laden', 'ladle', 'lance', 'lanky', 'lapse',
  'large', 'larva', 'laser', 'latch', 'later', 'lathe', 'latte', 'laugh', 'layer', 'leafy',
  'leant', 'leapt', 'learn', 'lease', 'leash', 'least', 'leave', 'ledge', 'lemon', 'lemur',
  'level', 'lever', 'light', 'lilac', 'limit', 'linen', 'liner', 'lithe', 'liver', 'llama',
  'lobby', 'local', 'lodge', 'lofty', 'logic', 'loose', 'loser', 'lotus', 'lousy', 'lover',
  'lower', 'loyal', 'lucky', 'lunar', 'lunch', 'lunge', 'lyric', 'macaw', 'macho', 'madam',
  'magic', 'magma', 'maize', 'major', 'maker', 'mango', 'mania', 'manor', 'maple', 'march',
  'marry', 'marsh', 'match', 'mayor', 'meant', 'medal', 'media', 'melon', 'mercy', 'merge',
  'merit', 'merry', 'metal', 'meter', 'metro', 'midst', 'might', 'mimic', 'mince', 'miner',
  'minor', 'minus', 'mixer', 'model', 'modem', 'moist', 'molar', 'money', 'month', 'moody',
  'moose', 'moral', 'motor', 'motto', 'mound', 'mount', 'mourn', 'mouse', 'mouth', 'mover',
  'movie', 'mower', 'muddy', 'mulch', 'mummy', 'munch', 'mural', 'music', 'naive', 'nanny',
  'nasal', 'nasty', 'naval', 'navel', 'nerve', 'never', 'newly', 'niche', 'niece', 'night',
  'ninja', 'ninth', 'noble', 'noise', 'noisy', 'nomad', 'north', 'notch', 'novel', 'nudge',
  'nurse', 'nylon', 'oasis', 'ocean', 'offer', 'often', 'olive', 'onion', 'onset', 'opera',
  'orbit', 'organ', 'other', 'otter', 'ought', 'ounce', 'outer', 'ovary', 'owner', 'oxide',
  'ozone', 'paint', 'panda', 'panel', 'panic', 'pansy', 'paper', 'parka', 'party', 'pasta',
  'paste', 'patch', 'patio', 'pause', 'peace', 'peach', 'pearl', 'pecan', 'pedal', 'penny',
  'perch', 'petal', 'phase', 'phone', 'photo', 'piano', 'piece', 'pilot', 'pinch', 'pitch',
  'pivot', 'pixel', 'pixie', 'pizza', 'place', 'plaid', 'plain', 'plane', 'plank', 'plant',
  'plate', 'plaza', 'plead', 'pluck', 'plumb', 'plume', 'plump', 'plush', 'poach', 'point',
  'poise', 'poker', 'polar', 'polka', 'porch', 'pouch', 'pound', 'power', 'prank', 'prawn',
  'press', 'price', 'prick', 'pride', 'prime', 'print', 'prior', 'prism', 'prize', 'probe',
  'prone', 'prong', 'proof', 'prose', 'proud', 'prove', 'prowl', 'prune', 'pulse', 'punch',
  'pupil', 'puppy', 'puree', 'purge', 'purse', 'quack', 'quail', 'quake', 'quart', 'queen',
  'query', 'quest', 'queue', 'quick', 'quiet', 'quill', 'quilt', 'quirk', 'quite', 'quote',
  'racer', 'radar', 'radio', 'rainy', 'raise', 'rally', 'ranch', 'range', 'rapid', 'ratio',
  'raven', 'razor', 'reach', 'react', 'ready', 'realm', 'rebel', 'recap', 'relax', 'relay',
  'relic', 'renew', 'reply', 'reset', 'resin', 'rhino', 'rhyme', 'rider', 'ridge', 'rifle',
  'right', 'rigid', 'rinse', 'ripen', 'risky', 'rival', 'river', 'rivet', 'roast', 'robin',
  'robot', 'rocky', 'rodeo', 'rogue', 'rotor', 'rough', 'round', 'rouse', 'route', 'rover',
  'rowdy', 'royal', 'rugby', 'ruler', 'rumor', 'rural', 'rusty', 'saber', 'sadly', 'safer',
  'saint', 'salad', 'salon', 'salsa', 'salty', 'sandy', 'satin', 'sauce', 'saucy', 'sauna',
  'saved', 'savor', 'scale', 'scalp', 'scare', 'scarf', 'scary', 'scene', 'scent', 'scoff',
  'scold', 'scone', 'scoop', 'scope', 'score', 'scorn', 'scout', 'scowl', 'scrap', 'screw',
  'scrub', 'scuba', 'sedan', 'seize', 'sense', 'serum', 'serve', 'setup', 'seven', 'sever',
  'sewer', 'shade', 'shady', 'shaft', 'shake', 'shaky', 'shale', 'shall', 'shame', 'shape',
  'share', 'shark', 'sharp', 'shave', 'shawl', 'shear', 'sheen', 'sheep', 'sheer', 'sheet',
  'shelf', 'shell', 'shift', 'shine', 'shiny', 'shire', 'shirt', 'shoal', 'shock', 'shone',
  'shook', 'shoot', 'shore', 'short', 'shout', 'shove', 'shown', 'showy', 'shred', 'shrub',
  'shrug', 'siege', 'sight', 'silky', 'silly', 'since', 'siren', 'sixth', 'sixty', 'skate',
  'skier', 'skill', 'skirt', 'skull', 'skunk', 'slack', 'slain', 'slang', 'slant', 'slash',
  'slate', 'slave', 'sleek', 'sleep', 'sleet', 'slept', 'slice', 'slick', 'slide', 'slime',
  'slimy', 'sling', 'slope', 'sloth', 'slump', 'slung', 'slush', 'small', 'smart', 'smash',
  'smear', 'smell', 'smile', 'smirk', 'smith', 'smock', 'smoke', 'smoky', 'snack', 'snail',
  'snake', 'snare', 'snarl', 'sneak', 'sneer', 'sniff', 'snipe', 'snore', 'snort', 'snout',
  'snowy', 'soapy', 'sober', 'soggy', 'solar', 'solid', 'solve', 'sonar', 'sonic', 'sorry',
  'sound', 'south', 'space', 'spade', 'spare', 'spark', 'spasm', 'spawn', 'speak', 'spear',
  'speck', 'speed', 'spell', 'spend', 'spent', 'spice', 'spicy', 'spike', 'spiky', 'spill',
  'spine', 'spiny', 'spire', 'spite', 'split', 'spoil', 'spoke', 'spook', 'spool', 'spoon',
  'spore', 'sport', 'spout', 'spray', 'spree', 'sprig', 'squad', 'squat', 'stack', 'staff',
  'stage', 'stain', 'stair', 'stake', 'stale', 'stalk', 'stall', 'stamp', 'stand', 'stare',
  'stark', 'start', 'state', 'steak', 'steal', 'steam', 'steed', 'steel', 'steep', 'steer',
  'stern', 'stick', 'stiff', 'still', 'stilt', 'sting', 'stink', 'stock', 'stoic', 'stoke',
  'stole', 'stomp', 'stone', 'stony', 'stood', 'stool', 'stoop', 'store', 'stork', 'storm',
  'story', 'stout', 'stove', 'strap', 'straw', 'stray', 'strip', 'study', 'stuff', 'stump',
  'stung', 'stunt', 'style', 'suave', 'sugar', 'suite', 'sunny', 'super', 'surge', 'sushi',
  'swamp', 'swarm', 'swear', 'sweat', 'sweep', 'sweet', 'swell', 'swept', 'swift', 'swine',
  'swing', 'swipe', 'swirl', 'sword', 'swore', 'sworn', 'syrup', 'table', 'taboo', 'tacky',
  'taken', 'tally', 'talon', 'tango', 'tangy', 'taper', 'tapir', 'tardy', 'taste', 'tasty',
  'teach', 'tease', 'teddy', 'teeth', 'tempo', 'tenor', 'tense', 'tenth', 'thank', 'theft',
  'their', 'theme', 'there', 'these', 'thick', 'thief', 'thigh', 'thing', 'think', 'third',
  'thorn', 'those', 'three', 'threw', 'throw', 'thumb', 'thump', 'thyme', 'tiara', 'tidal',
  'tiger', 'tight', 'timer', 'timid', 'tipsy', 'title', 'toast', 'today', 'token', 'tonic',
  'tooth', 'topaz', 'topic', 'torch', 'torso', 'total', 'totem', 'touch', 'tough', 'towel',
  'tower', 'toxic', 'toxin', 'trace', 'track', 'trade', 'trail', 'train', 'trait', 'tramp',
  'trash', 'tread', 'treat', 'trend', 'trial', 'tribe', 'trick', 'tried', 'troll', 'troop',
  'trout', 'truce', 'truck', 'truly', 'trump', 'trunk', 'trust', 'truth', 'tulip', 'tumor',
  'tunic', 'turbo', 'tutor', 'tweak', 'tweed', 'tweet', 'twice', 'twine', 'twirl', 'twist',
  'ulcer', 'ultra', 'uncle', 'under', 'union', 'unite', 'unity', 'until', 'upper', 'upset',
  'urban', 'usage', 'usher', 'usual', 'vague', 'valet', 'valid', 'valor', 'value', 'valve',
  'vapor', 'vault', 'vegan', 'venom', 'venue', 'verge', 'verse', 'video', 'vigor', 'villa',
  'vinyl', 'viola', 'viper', 'viral', 'virus', 'visit', 'visor', 'vista', 'vital', 'vivid',
  'vocal', 'vodka', 'vogue', 'voice', 'voter', 'vowel', 'wafer', 'wager', 'wagon', 'waist',
  'waltz', 'waste', 'watch', 'water', 'waver', 'weary', 'weave', 'wedge', 'weigh', 'weird',
  'whale', 'wharf', 'wheat', 'wheel', 'where', 'which', 'while', 'whine', 'whirl', 'whisk',
  'white', 'whole', 'whoop', 'whose', 'widen', 'wider', 'widow', 'width', 'wield', 'windy',
  'wiper', 'witch', 'witty', 'woman', 'women', 'woody', 'world', 'worry', 'worse', 'worst',
  'worth', 'would', 'wound', 'woven', 'wrath', 'wreck', 'wrist', 'write', 'wrong', 'wrote',
  'yacht', 'yearn', 'yeast', 'yield', 'young', 'yummy', 'zebra', 'zesty', 'zonal',
];

// Common Hebrew words (3–5 letters, no niqqud, regular forms). Kept basic and neutral; all are
// re-validated against the real Hebrew dictionary at generation time. Marked for admin QA.
export const COMMON_HE: string[] = [
  // 3
  'אור', 'יום', 'מים', 'איש', 'ילד', 'גשם', 'רוח', 'שמש', 'ירח', 'עץ',
  'פרי', 'דרך', 'בית', 'דלת', 'חלב', 'לחם', 'דבש', 'ביצ', 'תות', 'גזר',
  'כלב', 'חתל', 'אריה', 'דוב', 'דג', 'צבי', 'נמר', 'עז', 'פיל', 'סוס',
  'ראש', 'יד', 'רגל', 'אוז', 'עין', 'אזן', 'פה', 'אף', 'לב', 'דם',
  'ספר', 'עט', 'דף', 'שיר', 'סוד', 'חבר', 'אמא', 'אבא', 'אח', 'דוד',
  // 3 (more common nouns/verbs — re-validated against the dict at gen time)
  'חום', 'קור', 'קיר', 'סיר', 'חול', 'שלג', 'כוס', 'נוף', 'גוף', 'סוף',
  'עוף', 'אגס', 'נחש', 'קוף', 'תוף', 'חוף', 'שום', 'לוח', 'כוח', 'מוח',
  'צום', 'תור', 'עור', 'עיר', 'חבל', 'גבר', 'זהב', 'ברז', 'פרח', 'קמח',
  'בצל', 'רכב', 'ענף', 'גזע', 'זרע', 'חרב', 'קשת', 'דלק', 'מרק', 'פול',
  'נמל', 'גמל', 'דבר', 'יער', 'נהר', 'אגם', 'הרי', 'שדה', 'גשר', 'ים',
  // 4
  'שמים', 'ארץ', 'הרים', 'נהר', 'אגם', 'יער', 'פרח', 'עלה', 'ענן', 'ברק',
  'כוכב', 'בוקר', 'ערב', 'לילה', 'אביב', 'קיץ', 'סתיו', 'חורף', 'שבוע', 'חודש',
  'שולח', 'כסא', 'מיטה', 'דלת', 'חלון', 'מנורה', 'כוס', 'צלחת', 'מזלג', 'סכין',
  'כביש', 'גינה', 'חנות', 'שדה', 'עיר', 'כפר', 'חדר', 'בית', 'גשר', 'מגדל',
  // 5
  'תפוח', 'ענבים', 'לימון', 'אבטיח', 'תפוז', 'בננה', 'גזר', 'בצל', 'חיטה', 'זית',
  'אריות', 'נמרים', 'סוסים', 'דגים', 'ציפור', 'נשרים', 'דובים', 'זאבים', 'צבים', 'פילים',
  'כסאות', 'שולחן', 'מנורה', 'מקרר', 'תמונה', 'מוזיקה', 'צבעים', 'חלום', 'שלום', 'אמת',
  // --- enrichment batch (common; sofit folded + non-dictionary entries dropped at gen time) ---
  // verbs (3)
  'פתח', 'סגר', 'ישב', 'נתן', 'לקח', 'כתב', 'קרא', 'שמע', 'ראה', 'אכל',
  'שתה', 'הלך', 'בנה', 'עבד', 'למד', 'שחק', 'צחק', 'בכה', 'אהב', 'שנא',
  'פחד', 'חלם', 'חשב', 'מצא', 'שלח', 'קנה', 'מכר', 'פגש', 'רץ', 'קם',
  'בא', 'שר', 'נס', 'עף', 'גר', 'דאג', 'חזר', 'עלה', 'ירד', 'נפל',
  'קפץ', 'שאל', 'ענה', 'גמר', 'פסק', 'שבר', 'בנא',
  // verbs / present (4)
  'אוכל', 'שותה', 'הולך', 'רוצה', 'יודע', 'רואה', 'שומע', 'אומר', 'עושה', 'כותב',
  'קורא', 'שומר', 'עוזר', 'פותח', 'סוגר', 'נוסע', 'בורח', 'קופץ', 'צוחק', 'בוכה',
  'חושב', 'יושב', 'עומד', 'שוכב', 'חולם', 'אוהב', 'שונא', 'מפחד', 'זוכר', 'שוכח',
  'מבין', 'מדבר', 'שותק', 'צועק', 'לוחש', 'רוקד', 'מביא', 'לוקח', 'נותן', 'גומר',
  // colors / adjectives
  'אדום', 'ירוק', 'כחול', 'צהוב', 'שחור', 'לבן', 'ורוד', 'אפור', 'כתום', 'סגול',
  'כסף', 'גדול', 'קטן', 'ארוך', 'קצר', 'גבוה', 'נמוך', 'רחב', 'עבה', 'יבש',
  'רטוב', 'נקי', 'חדש', 'ישן', 'צעיר', 'זקן', 'חזק', 'חלש', 'מהיר', 'איטי',
  'חכם', 'טיפש', 'עשיר', 'עני', 'שמח', 'עצוב', 'כועס', 'רגוע', 'עייף', 'חולה',
  'בריא', 'חמים', 'קריר', 'נעים', 'יפה', 'נורא', 'טוב', 'נכון',
  // body
  'פנים', 'ידים', 'רגל', 'עין', 'שיער', 'שנים', 'אצבע', 'ברך', 'כתף', 'גב',
  'בטן', 'לשון', 'שפה', 'מצח', 'לחי', 'ראש',
  // home / objects (4-5)
  'כיסא', 'מיטה', 'ארון', 'מדף', 'חלון', 'רצפה', 'מטבח', 'אמבט', 'נרות', 'צלחת',
  'מזלג', 'סכין', 'כרית', 'שמיכה', 'מגבת', 'מברשת', 'מראה', 'שעון', 'ספה', 'וילון',
  // clothing
  'כובע', 'מעיל', 'שמלה', 'חולצה', 'מכנס', 'נעלים', 'גרב', 'צעיף', 'כפפה', 'חגורה',
  // food (4-5)
  'חמאה', 'גבינה', 'ביצה', 'בשר', 'אורז', 'פסטה', 'מרק', 'סלט', 'עוגה', 'עוגיה',
  'סוכר', 'מלח', 'פלפל', 'שמן', 'חומץ', 'ריבה', 'בירה', 'יין', 'מיץ', 'קפה',
  'תפוח', 'תפוז', 'בננה', 'ענב', 'אגס', 'שזיף', 'מלון', 'אבטיח', 'לימון', 'תירס',
  'חסה', 'בטטה', 'עגבן',
  // animals (4-5)
  'ארנב', 'צפרדע', 'פרה', 'חזיר', 'אווז', 'ברווז', 'יונה', 'עורב', 'דבורה', 'נמלה',
  'זבוב', 'עכבר', 'חתול', 'תוכי', 'דולפין', 'לטאה', 'צבים', 'אריות', 'נמרים',
  // nature / world (4-5)
  'עולם', 'טבע', 'צמח', 'עשב', 'שורש', 'מדבר', 'עמק', 'גלים', 'איים', 'עננים',
  'שמים', 'כוכב', 'מטר', 'רעם', 'אבן', 'חצץ', 'אדמה', 'פסגה', 'גבעה', 'נחל',
  // places / transport (4-5)
  'מטוס', 'רכבת', 'אוטו', 'אופן', 'סירה', 'ספינה', 'מדינה', 'עיתון', 'מחשב', 'טלפון',
  'מסעדה', 'גינה', 'חנות', 'מגדל', 'ארמון', 'מבצר', 'כפר', 'רחוב', 'מגרש', 'בריכה',
  // time / misc (4-5)
  'זמן', 'שעה', 'שנה', 'בוקר', 'צהרים', 'לילה', 'אתמול', 'היום', 'מחר', 'עכשיו',
  'חופש', 'שמחה', 'אהבה', 'מתנה', 'משחק', 'סיפור', 'ציור', 'שאלה', 'מספר', 'אות',
  // plurals (4-5)
  'ילדים', 'אנשים', 'בתים', 'ימים', 'חיים', 'דברים', 'ספרים', 'מורים', 'חברים', 'כלבים',
  'חתולים', 'פרחים', 'עצים', 'הרים', 'נהרות', 'גשרים', 'חלונות', 'דלתות', 'רגלים', 'עינים',
  // --- short-word variety batch (3-4 letters → richer 4×4 interlock) ---
  'גיל', 'קול', 'אזן', 'נר', 'סל', 'כד', 'חג', 'שק', 'תא', 'חי',
  'שם', 'גן', 'צל', 'טל', 'אם', 'אב', 'בן', 'בת', 'אש', 'עם',
  'יש', 'כל', 'רק', 'גם', 'עד', 'צו', 'קן', 'חוט', 'ליל', 'עפר',
  'אבן', 'ילד', 'איש', 'אשה', 'שכן', 'מלך', 'גנן', 'טבח', 'זמר', 'נחל',
  'זרם', 'גיר', 'חלון', 'נביא', 'שופט', 'חייל', 'רופא', 'צייר', 'רקדן', 'נסיך',
  'מים', 'דרך', 'עיר', 'כפר', 'גשם', 'רוח', 'ענן', 'גשר', 'נמל', 'גמל',
  'חמור', 'סוס', 'תיק', 'עיפ', 'חבל', 'מפה', 'כלי', 'בגד', 'נעל', 'כפה',
  'דוד', 'אחות', 'בנים', 'אבות', 'נשים', 'מלכה', 'נמר', 'דבש', 'חמה', 'לבנה',
  'שמש', 'ירח', 'כוכב', 'מטר', 'ברד', 'קרח', 'אגל', 'טיפה', 'נהר', 'אגם',
  'חצר', 'גדר', 'שער', 'גג', 'יער', 'שדה', 'דשא', 'פרג', 'ורד', 'צמח',
];
