/**
 * Build-time crossword generator. Loads the real per-language dictionary, runs the CSP filler
 * over a set of 5x5 templates, and writes valid puzzles to
 *   lib/crossword/puzzles/generated/{locale}.generated.ts
 *
 * Grids are produced offline; CLUES are intentionally left empty (source: 'generated') for a
 * later LLM clue pass + admin QA. See docs/2026-06-06-crossword-mode-spec.md.
 *
 * Usage:  npx tsx scripts/crossword/generate.ts en he
 */
import fs from 'node:fs';
import path from 'node:path';
import {
  createSafeReadFile,
  loadEnglishDictionary,
  loadHebrewDictionary,
} from '../../backend/dictionaryLoaders';
import { buildGrid } from '../../lib/crossword/grid';
import { buildDictIndex, fillGrid, type FillTemplate } from '../../lib/crossword/generate.core';
import type { CrosswordPuzzle, PuzzleLocale, Slot } from '../../lib/crossword/types';
import { COMMON_EN, COMMON_HE } from './commonWords';

const COMMON_BY_LOCALE: Partial<Record<PuzzleLocale, string[]>> = { en: COMMON_EN, he: COMMON_HE };

// Pure-letter filters so grid runs only ever contain real fillable letters.
const LETTER_RE: Partial<Record<PuzzleLocale, RegExp>> = {
  en: /^[a-z]+$/,
  he: /^[א-ת]+$/, // Hebrew consonants (already sofit-normalized by the loader)
};

// Cap candidates per length to bound CSP runtime on huge buckets (Hebrew 5L ~ 73k).
const MAX_PER_LENGTH = 6000;

// Rotationally-symmetric 5x5 templates (block coordinates). Mix of open + lightly blocked
// to bias toward abundant short words and create variety.
const TEMPLATES_5: Array<[number, number][]> = [
  [], // fully open 5x5 (word square)
  [[0, 0], [4, 4]],
  [[0, 4], [4, 0]],
  [[2, 2]], // single center block (self-symmetric)
  [[0, 0], [0, 4], [4, 0], [4, 4]], // four corners
  [[1, 1], [3, 3]],
];

const SEEDS = [11, 29, 47, 83, 131, 211, 307, 401];

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function indexFor(words: Set<string>, locale: PuzzleLocale, common: boolean) {
  const re = LETTER_RE[locale]!;
  const rng = mulberry32(99);
  // Common mode: candidate pool = curated common words that ALSO exist in the real dictionary
  // (so nothing un-submittable can appear). Otherwise: the full validity dictionary.
  const source: Iterable<string> = common
    ? (COMMON_BY_LOCALE[locale] ?? []).filter((w) => words.has(w))
    : words;
  const byLen = new Map<number, string[]>();
  const seen = new Set<string>();
  for (const w of source) {
    if (w.length < 3 || w.length > 5) continue;
    if (!re.test(w)) continue;
    if (seen.has(w)) continue;
    seen.add(w);
    const bucket = byLen.get(w.length) ?? [];
    bucket.push(w);
    byLen.set(w.length, bucket);
  }
  // Shuffle + cap each bucket.
  const flat: string[] = [];
  for (const [, bucket] of byLen) {
    for (let i = bucket.length - 1; i > 0; i--) {
      const j = Math.floor(rng() * (i + 1));
      [bucket[i], bucket[j]] = [bucket[j], bucket[i]];
    }
    flat.push(...bucket.slice(0, MAX_PER_LENGTH));
  }
  return buildDictIndex(flat);
}

function makePuzzle(
  id: string,
  locale: PuzzleLocale,
  grid: (string | null)[][],
): CrosswordPuzzle {
  const rtl = locale === 'he';
  const { size, cells, slots } = buildGrid({ rtl, solution: grid });
  // Clues empty for now — filled by a later LLM pass + admin QA.
  const cluedSlots: Slot[] = slots.map((s) => ({ ...s, clue: '' }));
  return {
    id,
    locale,
    size,
    rtl,
    cells,
    slots: cluedSlots,
    difficulty: 'easy',
    source: 'generated',
  };
}

function generateForLocale(
  locale: PuzzleLocale,
  dict: Set<string>,
  want: number,
  common: boolean,
): CrosswordPuzzle[] {
  const index = indexFor(dict, locale, common);
  const puzzles: CrosswordPuzzle[] = [];
  const seenSignature = new Set<string>();
  let n = 0;
  for (const blocks of TEMPLATES_5) {
    for (const seed of SEEDS) {
      if (puzzles.length >= want) break;
      const template: FillTemplate = { size: 5, rtl: locale === 'he', blocks };
      const grid = fillGrid(template, index, { rng: mulberry32(seed), maxSteps: 120_000 });
      if (!grid) continue;
      const sig = grid.map((r) => r.map((c) => c ?? '#').join('')).join('|');
      if (seenSignature.has(sig)) continue;
      seenSignature.add(sig);
      n += 1;
      puzzles.push(makePuzzle(`${locale}-mini-${String(n).padStart(3, '0')}`, locale, grid));
    }
    if (puzzles.length >= want) break;
  }
  return puzzles;
}

function serialize(locale: PuzzleLocale, puzzles: CrosswordPuzzle[]): string {
  const constName = `${locale.toUpperCase()}_GENERATED_PUZZLES`;
  return (
    `// AUTO-GENERATED by scripts/crossword/generate.ts — do not edit by hand.\n` +
    `// Grids filled from the ${locale} dictionary (CSP). Clues pending LLM + admin QA.\n` +
    `import type { CrosswordPuzzle } from '../../types';\n\n` +
    `export const ${constName}: CrosswordPuzzle[] = ${JSON.stringify(puzzles, null, 2)};\n`
  );
}

async function main() {
  const args = process.argv.slice(2);
  const common = args.includes('--common');
  const locales = (args.filter((a) => !a.startsWith('--')).length
    ? args.filter((a) => !a.startsWith('--'))
    : ['en', 'he']) as PuzzleLocale[];
  const want = 8;
  const safeRead = createSafeReadFile();
  const outDir = path.join(__dirname, '../../lib/crossword/puzzles/generated');
  fs.mkdirSync(outDir, { recursive: true });

  for (const locale of locales) {
    const t0 = Date.now();
    const dict =
      locale === 'he'
        ? await loadHebrewDictionary(safeRead)
        : await loadEnglishDictionary(safeRead);
    const puzzles = generateForLocale(locale, dict, want, common);
    const outPath = path.join(outDir, `${locale}.generated.ts`);
    fs.writeFileSync(outPath, serialize(locale, puzzles), 'utf-8');
     
    console.log(
      `[crossword] ${locale}: ${puzzles.length} puzzles in ${Date.now() - t0}ms -> ${path.relative(process.cwd(), outPath)}`,
    );
    for (const p of puzzles.slice(0, 2)) {
      const words = p.slots.map((s) => `${s.id}:${s.answer}`).join('  ');
       
      console.log(`  ${p.id} (${p.slots.length} slots)  ${words}`);
    }
  }
}

main().catch((e) => {
   
  console.error(e);
  process.exit(1);
});
