#!/bin/bash
# feedback-digest.sh — summarize recent PLAYER FEEDBACK for the nightly loop.
#
# Pulls two distinct signals and writes one markdown file the lanes read via the
# __FEEDBACK_SUMMARY__ placeholder (see lib/headless.sh):
#   1. Sentiment ratings — PostHog `growth:game_feedback` events (the in-game
#      "how was that?" card; surfaces: mp_round | singleplayer | daily).
#   2. Bug / free-text reports — Supabase `feedback_reports` table (Report-a-Bug).
#
# These answer different questions — "how did the game FEEL" vs "what's BROKEN" —
# so they're labelled separately. Degrades to a clear empty-state when a key is
# missing or no data lands; never fails the run (always exits 0, always writes
# a valid file).
#
# Output: docs/nightly/feedback/summary-<TODAY>.md  (path also printed to stdout)
# Env: POSTHOG_HOST, POSTHOG_PROJECT_ID, POSTHOG_PERSONAL_API_KEY,
#      SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, PROJECT_DIR, TODAY

set -uo pipefail

PROJECT_DIR="${PROJECT_DIR:-/Users/ohadfisher/git/boggle-new}"
TODAY="${TODAY:-$(date +%Y-%m-%d)}"
OUT_DIR="$PROJECT_DIR/docs/nightly/feedback"
OUT="$OUT_DIR/summary-$TODAY.md"
mkdir -p "$OUT_DIR"

PH_HOST="${POSTHOG_HOST:-https://us.i.posthog.com}"

# Run a HogQL query, print raw JSON results array (or empty on failure).
ph_query() {
  local q="$1"
  [ -n "${POSTHOG_PERSONAL_API_KEY:-}" ] && [ -n "${POSTHOG_PROJECT_ID:-}" ] || return 1
  curl -sS --max-time 20 \
    "${PH_HOST}/api/projects/${POSTHOG_PROJECT_ID}/query/" \
    -H "Authorization: Bearer ${POSTHOG_PERSONAL_API_KEY}" \
    -H "Content-Type: application/json" \
    -d "{\"query\":{\"kind\":\"HogQLQuery\",\"query\":$(printf '%s' "$q" | jq -Rs .)}}" \
    2>/dev/null | jq -c '.results // []' 2>/dev/null
}

# Per-surface sentiment over the last $1 hours. Columns:
# surface, n, avg_rating(1-3), bad, ok, great
sentiment_rows() {
  local hours="$1"
  ph_query "SELECT properties.surface, count(), round(avg(toFloat(properties.ratingValue)),2), countIf(properties.rating='bad'), countIf(properties.rating='ok'), countIf(properties.rating='great') FROM events WHERE event='growth:game_feedback' AND timestamp > now() - INTERVAL ${hours} HOUR GROUP BY properties.surface ORDER BY count() DESC"
}

{
  echo "# Player feedback digest — $TODAY"
  echo

  # ── 1. Sentiment ratings (game_feedback) ────────────────────────────────
  echo "## Sentiment ratings (in-game \"how was that?\" card)"
  echo
  WINDOW_LABEL="last 24h"
  ROWS="$(sentiment_rows 24)"
  if [ -z "$ROWS" ]; then
    echo "_PostHog unavailable (no API key or query failed) — skip sentiment this run._"
  else
    COUNT="$(printf '%s' "$ROWS" | jq 'length' 2>/dev/null || echo 0)"
    if [ "${COUNT:-0}" -eq 0 ]; then
      # Widen to 7 days so early/low-traffic days still surface a signal.
      ROWS="$(sentiment_rows 168)"
      COUNT="$(printf '%s' "$ROWS" | jq 'length' 2>/dev/null || echo 0)"
      WINDOW_LABEL="last 7d"
    fi
    if [ "${COUNT:-0}" -eq 0 ]; then
      echo "_No sentiment ratings in the last 7 days._"
    else
      echo "Window: **$WINDOW_LABEL**. Rating scale: bad=1, ok=2, great=3."
      echo
      echo "| Surface | Responses | Avg | 😕 bad | 😐 ok | 🤩 great |"
      echo "|---|---|---|---|---|---|"
      printf '%s' "$ROWS" | jq -r '.[] | "| \(.[0] // "?") | \(.[1]) | \(.[2]) | \(.[3]) | \(.[4]) | \(.[5]) |"' 2>/dev/null
      echo
      echo "_A low avg or a bad-heavy surface is a prioritization signal — find the root cause, don't dismiss it._"
    fi
  fi
  echo

  # ── 2. Bug / free-text reports (feedback_reports) ───────────────────────
  echo "## Bug & free-text reports (Report-a-Bug)"
  echo
  if [ -n "${SUPABASE_URL:-}" ] && [ -n "${SUPABASE_SERVICE_ROLE_KEY:-}" ]; then
    SINCE="$(date -u -v-7d +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -d '7 days ago' +%Y-%m-%dT%H:%M:%SZ 2>/dev/null)"
    REPORTS="$(curl -sS --max-time 20 \
      "${SUPABASE_URL}/rest/v1/feedback_reports?select=created_at,locale,page,message&created_at=gte.${SINCE}&order=created_at.desc&limit=10" \
      -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" \
      -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
      2>/dev/null)"
    RCOUNT="$(printf '%s' "$REPORTS" | jq 'if type=="array" then length else 0 end' 2>/dev/null || echo 0)"
    if [ "${RCOUNT:-0}" -eq 0 ]; then
      echo "_No bug reports in the last 7 days._"
    else
      echo "**$RCOUNT** report(s) in the last 7 days (most recent first):"
      echo
      printf '%s' "$REPORTS" | jq -r '.[] | "- [\(.created_at[0:10]) · \(.locale // "?") · \(.page // "?" | .[0:40])] \(.message // "" | gsub("[\n\r]";" ") | .[0:200])"' 2>/dev/null
    fi
  else
    echo "_Supabase credentials unavailable — skip bug reports this run._"
  fi
  echo
  echo "---"
  echo "_Generated by lib/feedback-digest.sh. Sentiment = PostHog \`growth:game_feedback\`; reports = Supabase \`feedback_reports\`._"
} > "$OUT" 2>/dev/null

echo "$OUT"
exit 0
