export interface WordEntry {
  word: string;
  definition: string;
  etymology: string;
  example: string;
  funFact: string;
  difficulty: 'easy' | 'medium' | 'hard';
  partOfSpeech: string;
  dateKey: string;
}

export type Locale = 'en' | 'he' | 'sv' | 'ja' | 'es';

const enWords: WordEntry[] = [
  { dateKey: '2026-03-10', word: 'Quixotic', definition: 'Extremely idealistic; unrealistic and impractical.', etymology: 'From Don Quixote, the fictional Spanish knight created by Cervantes (1605).', example: 'Her quixotic plan to end all pollution by next year impressed no one.', funFact: 'One of the few English words derived from a fictional character\'s name.', difficulty: 'hard', partOfSpeech: 'adjective' },
  { dateKey: '2026-03-09', word: 'Ephemeral', definition: 'Lasting for a very short time.', etymology: 'Greek ephemeros, meaning "lasting only a day."', example: 'The beauty of cherry blossoms is ephemeral, lasting just two weeks.', funFact: 'In biology, an ephemeral organism lives for only one day, like mayflies.', difficulty: 'medium', partOfSpeech: 'adjective' },
  { dateKey: '2026-03-08', word: 'Zephyr', definition: 'A soft, gentle breeze.', etymology: 'From Zephyrus, the Greek god of the west wind.', example: 'A warm zephyr carried the scent of jasmine through the garden.', funFact: 'Worth 21 points in Scrabble — the Z alone is worth 10!', difficulty: 'medium', partOfSpeech: 'noun' },
  { dateKey: '2026-03-07', word: 'Petrichor', definition: 'The pleasant earthy smell after rain falls on dry ground.', etymology: 'Coined in 1964 from Greek petra (stone) + ichor (the fluid of the gods).', example: 'After weeks of drought, the petrichor was intoxicating.', funFact: 'The scent is caused by an oil called geosmin released by soil bacteria.', difficulty: 'hard', partOfSpeech: 'noun' },
  { dateKey: '2026-03-06', word: 'Candor', definition: 'The quality of being open, honest, and sincere.', etymology: 'Latin candor, meaning "whiteness, brightness, sincerity."', example: 'I appreciate your candor — not everyone would be so honest.', funFact: 'In the Divergent series, Candor is the faction devoted to truth.', difficulty: 'easy', partOfSpeech: 'noun' },
  { dateKey: '2026-03-05', word: 'Sonder', definition: 'The realization that every passerby has a life as vivid as your own.', etymology: 'Coined by John Koenig in The Dictionary of Obscure Sorrows (2012).', example: 'Standing in the busy station, she felt a wave of sonder.', funFact: 'This is a neologism — it does not appear in traditional dictionaries yet.', difficulty: 'hard', partOfSpeech: 'noun' },
  { dateKey: '2026-03-04', word: 'Lucid', definition: 'Expressed clearly; easy to understand. Also: bright or luminous.', etymology: 'Latin lucidus, from lux meaning "light."', example: 'Despite the complexity, her explanation was remarkably lucid.', funFact: 'A lucid dream is one where the dreamer is aware they are dreaming.', difficulty: 'easy', partOfSpeech: 'adjective' },
  { dateKey: '2026-03-03', word: 'Mellifluous', definition: 'Sweet-sounding; pleasant to hear.', etymology: 'Latin mel (honey) + fluere (to flow) — literally "flowing with honey."', example: 'The singer\'s mellifluous voice filled the concert hall.', funFact: 'Often used to describe voices, music, and accents in literature.', difficulty: 'hard', partOfSpeech: 'adjective' },
  { dateKey: '2026-03-02', word: 'Aplomb', definition: 'Self-confidence or assurance, especially under pressure.', etymology: 'French aplomb, from a plomb meaning "according to the plumb line" — perfectly vertical.', example: 'She handled the crisis with remarkable aplomb.', funFact: 'Originally a ballet term for maintaining perfect vertical balance.', difficulty: 'medium', partOfSpeech: 'noun' },
  { dateKey: '2026-03-01', word: 'Serendipity', definition: 'The occurrence of happy events by chance.', etymology: 'Coined by Horace Walpole in 1754, from the fairy tale The Three Princes of Serendip.', example: 'Finding that rare book at a garage sale was pure serendipity.', funFact: 'Voted one of the hardest English words to translate into other languages.', difficulty: 'medium', partOfSpeech: 'noun' },
  { dateKey: '2026-02-28', word: 'Verbose', definition: 'Using more words than needed; wordy.', etymology: 'Latin verbosus, from verbum meaning "word."', example: 'The verbose report could have been summarized in two pages.', funFact: 'In programming, "verbose mode" means showing extra detailed output.', difficulty: 'easy', partOfSpeech: 'adjective' },
  { dateKey: '2026-02-27', word: 'Ubiquitous', definition: 'Present, appearing, or found everywhere.', etymology: 'Latin ubique meaning "everywhere."', example: 'Smartphones have become ubiquitous in modern life.', funFact: 'Contains all five standard vowels (u, i, u, i, o, u) — six vowel sounds!', difficulty: 'medium', partOfSpeech: 'adjective' },
  { dateKey: '2026-02-26', word: 'Zenith', definition: 'The highest point reached; the peak or climax.', etymology: 'Arabic samt ar-ra\'s, meaning "path above the head," corrupted through Old Spanish.', example: 'The empire reached its zenith in the 15th century.', funFact: 'In astronomy, the zenith is the point directly above you in the sky.', difficulty: 'medium', partOfSpeech: 'noun' },
  { dateKey: '2026-02-25', word: 'Enigma', definition: 'A person or thing that is mysterious or difficult to understand.', etymology: 'Greek ainigma, from ainissesthai meaning "to speak in riddles."', example: 'The disappearance of the crew remains an enigma to this day.', funFact: 'The Enigma machine was the famous WWII German cipher device cracked by Alan Turing.', difficulty: 'easy', partOfSpeech: 'noun' },
];

const heWords: WordEntry[] = [
  { dateKey: '2026-03-10', word: 'דקדקן', definition: 'אדם המקפיד על פרטים קטנים ודיוק.', etymology: 'מהשורש ד.ק.ד.ק בעברית, הקשור לדקדוק ולדיוק.', example: 'המורה הייתה דקדקנית כל כך שסימנה כל פסיק חסר.', funFact: 'המילה קשורה גם ל"דקדוק" — חוקי השפה, כי שניהם עוסקים בדיוק.', difficulty: 'medium', partOfSpeech: 'שם תואר' },
  { dateKey: '2026-03-09', word: 'חלומי', definition: 'דמיוני, כמו בחלום; לא מציאותי.', etymology: 'מהמילה "חלום" בעברית, עם הסיומת -י ליצירת שם תואר.', example: 'הנוף הררי היה חלומי באור השקיעה.', funFact: 'בעברית המקראית, חלומות נחשבו לנבואות מאת אלוהים.', difficulty: 'easy', partOfSpeech: 'שם תואר' },
  { dateKey: '2026-03-08', word: 'תעלומה', definition: 'דבר שקשה להסבירו או להבינו; סוד.', etymology: 'מהשורש ע.ל.מ — "נעלם", "נסתר".', example: 'היעלמות הספינה נותרה תעלומה עד היום.', funFact: 'ספרות הבלשים בעברית נקראת "ספרות תעלומה".', difficulty: 'easy', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-07', word: 'ערגה', definition: 'געגוע עז, כיסופים עמוקים.', etymology: 'מהשורש ע.ר.ג, הופיע כבר בתנ"ך בתהילים.', example: 'הערגה למולדת ליוותה אותו כל שנות הגלות.', funFact: '"כאיל תערוג על אפיקי מים" — מתהילים מ"ב, אחד הפסוקים המפורסמים.', difficulty: 'medium', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-06', word: 'חוצפה', definition: 'עזות מצח, העזה חסרת כבוד.', etymology: 'ממילה ארמית שחדרה לעברית, ומשם לאנגלית!', example: 'הייתה לו חוצפה לבקש העלאה ביום הראשון שלו.', funFact: 'חוצפה נכנסה למילון האנגלי והיא מוכרת בכל העולם.', difficulty: 'easy', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-05', word: 'אפוריזם', definition: 'אמרה קצרה וחדה המביעה אמת או עיקרון.', etymology: 'מיוונית aphorismos — "הגדרה", דרך הלטינית.', example: '"הזמן הוא כסף" הוא אפוריזם ידוע.', funFact: 'היפוקרטס כתב את ה"אפוריזמים" הרפואיים הראשונים.', difficulty: 'hard', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-04', word: 'סהרורי', definition: 'הולך בשנתו; פועל ללא מודעות.', etymology: 'מ"סהר" (ירח) — כי סהרוריות קושרה לאור הירח.', example: 'הוא הלך כמו סהרורי, בלי לשים לב לסביבה.', funFact: 'בימי הביניים האמינו שסהרוריות נגרמת מכוח הירח המלא.', difficulty: 'hard', partOfSpeech: 'שם תואר' },
  { dateKey: '2026-03-03', word: 'תושייה', definition: 'כושר המצאה, חריצות, יכולת למצוא פתרונות.', etymology: 'מילה מקראית מספר איוב ומשלי.', example: 'בזכות תושייתו הוא מצא פתרון יצירתי לבעיה.', funFact: 'מילה שאליעזר בן-יהודה החיה בתחייה העברית.', difficulty: 'hard', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-02', word: 'שלווה', definition: 'מצב של שקט, רוגע ושלום פנימי.', etymology: 'מהשורש ש.ל.ו — "שקט", "רגוע".', example: 'שלווה עמוקה שררה באגם בשעות הבוקר.', funFact: 'שם פרטי פופולרי בישראל — שלו/שלווה.', difficulty: 'easy', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-01', word: 'הדהוד', definition: 'חזרה של צליל; תגובה רגשית עמוקה.', etymology: 'מהשורש ה.ד.ה.ד — חיקוי צליל (אונומטופיאה).', example: 'דבריה מצאו הדהוד עמוק בליבם של כולם.', funFact: 'מילה שמשמשת גם בפיזיקה (הדהוד אקוסטי) וגם בפסיכולוגיה.', difficulty: 'medium', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-02-28', word: 'גחמה', definition: 'רצון פתאומי וחסר הגיון; קפריזה.', etymology: 'מארמית, קשורה ל"גחם" — רצון, חשק.', example: 'היא קנתה את השמלה מתוך גחמה רגעית.', funFact: 'בתלמוד המילה מופיעה בהקשר של רצונות בלתי צפויים.', difficulty: 'medium', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-02-27', word: 'מופלא', definition: 'נפלא, מעורר פליאה והתפעלות.', etymology: 'מהשורש פ.ל.א — "פלא", "דבר מופלא".', example: 'ההצגה הייתה מופלאה — הקהל עמד על רגליו.', funFact: 'בעברית מקראית, "מופלא" שימש גם במובן של "נסתר, בלתי מושג".', difficulty: 'easy', partOfSpeech: 'שם תואר' },
  { dateKey: '2026-02-26', word: 'פרדוקס', definition: 'אמירה שנראית סותרת את עצמה אך מכילה אמת.', etymology: 'מיוונית paradoxon — "מנוגד לדעה הרווחת".', example: '"ככל שיודעים יותר, מבינים כמה מעט יודעים" — פרדוקס קלאסי.', funFact: 'פרדוקס זנון על אכילס והצב הוא מהמפורסמים ביותר בפילוסופיה.', difficulty: 'medium', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-02-25', word: 'דמדומים', definition: 'האור החלש בזמן שקיעת השמש או זריחתה.', etymology: 'כפילות השורש ד.מ.מ — "דממה", רמז לשקט של הרגע.', example: 'בדמדומים, השמיים נצבעו בוורוד וסגול.', funFact: 'יש שלושה סוגי דמדומים: אזרחיים, ימיים ואסטרונומיים.', difficulty: 'easy', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-11', word: 'חיוך', definition: 'עיוות פנים המבטא שמחה, חיבה או הומור.', etymology: 'מהשורש ח.י.ך, קשור ל"חך" — חלק הפה הפנימי.', example: 'חיוך רחב התפשט על פניה כשראתה אותו.', funFact: 'מחקרים מראים שגם חיוך מאולץ יכול לשפר את מצב הרוח.', difficulty: 'easy', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-12', word: 'סקרנות', definition: 'רצון עז לדעת, להבין או לחקור דברים חדשים.', etymology: 'מהשורש ס.ק.ר — לבחון, לבדוק.', example: 'הילדה שאלה שאלות מתוך סקרנות בלתי נדלית.', funFact: 'איינשטיין אמר: "אין לי כישרון מיוחד, אני רק סקרן באופן נלהב."', difficulty: 'easy', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-13', word: 'התלהבות', definition: 'התרגשות וחיוניות; תחושת התרוממות רוח עזה.', etymology: 'מהשורש ל.ה.ב — אש ולהבה. "בוער מבפנים".', example: 'הצוות עבד בהתלהבות עד השעות הקטנות של הלילה.', funFact: 'בעברית מודרנית, "התלהבות" מקבילה ל-enthusiasm — שתיהן משלבות אש עם רגש.', difficulty: 'easy', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-14', word: 'ענווה', definition: 'צניעות; היעדר יוהרה והכרת המקום הראוי לעצמי.', etymology: 'מהשורש ע.נ.ה — "להיכנע", "להיות עני ברוח".', example: 'למרות הצלחתו הגדולה, הוא נשאר אדם של ענווה.', funFact: 'משה רבנו מתואר במקרא כ"עניו מכל האדם אשר על פני האדמה".', difficulty: 'medium', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-15', word: 'קסום', definition: 'מלא קסם; מעורר התפעלות ופליאה.', etymology: 'מהשורש ק.ס.מ — קוסם, להפעיל כישוף.', example: 'הסיור בעיר העתיקה היה קסום במיוחד בלילה.', funFact: 'בעברית מקראית "קסם" התייחס לכישוף אסור, היום למשהו מופלא.', difficulty: 'easy', partOfSpeech: 'שם תואר' },
  { dateKey: '2026-03-16', word: 'זריז', definition: 'מהיר ופעיל; מי שעושה דברים בזריזות.', etymology: 'מהשורש ז.ר.ז — האיץ, דירבן.', example: 'השחקן הזריז חמק בין הבלמים והבקיע.', funFact: 'שמו של "זרזיר" (ציפור) — נגזר מאותו שורש בגלל תנועותיה המהירות.', difficulty: 'easy', partOfSpeech: 'שם תואר' },
  { dateKey: '2026-03-17', word: 'השראה', definition: 'רעיון או דחף יצירתי שמגיע פתאום, כמעט מבחוץ.', etymology: 'מהשורש ש.ר.ה — "להשרות". כאילו הרעיון יורד מלמעלה.', example: 'היא מצאה את ההשראה לציור בטיול אל הים.', funFact: 'בעברית, "השראה" קשורה גם ל"שכינה" — כינוי לנוכחות אלוהית.', difficulty: 'easy', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-18', word: 'רחמים', definition: 'חמלה ורגישות לסבל הזולת; נכונות לסלוח.', etymology: 'מהשורש ר.ח.מ — קרוב ל"רחם" (אם), כי האם רחמנית מטבעה.', example: 'השופט גילה רחמים והקל בעונשו של הנאשם.', funFact: 'בערבית "רחים" מאותו שורש שמי, מילה מ-99 שמות האל באסלאם.', difficulty: 'easy', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-19', word: 'בועה', definition: 'כדור של אוויר במים או נוזל; דבר שביר.', etymology: 'מהשורש ב.ע.ע — לרתוח, להעלות בועות.', example: 'ילדים אוהבים לפוצץ בועות סבון בגינה.', funFact: 'בכלכלה יש "בועה כלכלית" — מצב של מחירים מנופחים שמתרסקים פתאום.', difficulty: 'easy', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-20', word: 'מעיין', definition: 'מקור מים טבעי הנובע מן האדמה.', etymology: 'מהשורש ע.י.נ — קשור ל"עין" (כמו "עין מים").', example: 'הטיול הסתיים בשתיית מים צוננים מן המעיין.', funFact: 'שם פרטי פופולרי בישראל — נשיים וגבריים גם יחד.', difficulty: 'medium', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-21', word: 'לחישה', definition: 'דיבור שקט, כמעט בלתי נשמע.', etymology: 'מהשורש ל.ח.ש — לדבר חרש; קשור גם ל"לחש" של כישוף.', example: 'היא העבירה את הסוד בלחישה דקה.', funFact: '"מלחשי לחש" בקבלה — אנשים שעוסקים בכישוף באמצעות מילים שקטות.', difficulty: 'medium', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-22', word: 'נדיבות', definition: 'נכונות לתת בשפע, ללא חישוב או ציפייה לתמורה.', etymology: 'מהשורש נ.ד.ב — להתנדב, לתרום מרצון.', example: 'הוא ידוע בנדיבות לבו כלפי מי שצריך עזרה.', funFact: '"נדבה" בעברית היא תרומה רצונית, בניגוד ל"מס" שהוא חובה.', difficulty: 'medium', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-23', word: 'צפרירים', definition: 'רוחות קלות של בוקר; משבי רוח עדינים בשחר.', etymology: 'מן השורש צ.פ.ר — קשור ל"צפרא" בארמית: בוקר.', example: 'צפרירי שחר הניעו את עלי הזית בעדינות.', funFact: 'שם שיר מפורסם של חיים נחמן ביאליק — "הצפרירים" מ-1900.', difficulty: 'hard', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-24', word: 'אומץ', definition: 'גבורה; היכולת לפעול נכון למרות הפחד.', etymology: 'מהשורש א.מ.צ — להיות חזק, איתן.', example: 'צריך אומץ אמיתי כדי להודות בטעות בפומבי.', funFact: '"חזק ואמץ" — ברכת משה ליהושע במקרא, הפכה לסיסמת חיילים בישראל.', difficulty: 'easy', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-25', word: 'יצירתיות', definition: 'היכולת לחשוב ולעצב דברים חדשים ומקוריים.', etymology: 'מהשורש י.צ.ר — לעצב, לברוא. אותו שורש כמו "יצירה".', example: 'היצירתיות שלו בפתרון בעיות מרשימה את כולם.', funFact: 'בתנ"ך, "וייצר ה\' אלוהים את האדם" — אותו שורש מתאר את הבריאה הראשונה.', difficulty: 'medium', partOfSpeech: 'שם עצם' },
  { dateKey: '2026-03-26', word: 'זיכרון', definition: 'יכולת השכל לשמור מידע ולהיזכר בעבר.', etymology: 'מהשורש ז.כ.ר — לזכור, להזכיר.', example: 'יש לו זיכרון מצוין לשמות ולפרצופים.', funFact: '"יום הזיכרון" בישראל מציין את חללי מערכות ישראל ופעולות האיבה.', difficulty: 'easy', partOfSpeech: 'שם עצם' },
];

const svWords: WordEntry[] = [
  { dateKey: '2026-03-10', word: 'Lagom', definition: 'Precis lagom mycket; inte for lite, inte for mycket.', etymology: 'Fran fornsvenska "laget om" — "runt laget" (delning i grupp).', example: 'Kaffet var lagom varmt, precis som jag vill ha det.', funFact: 'Lagom ar sa centralt i svensk kultur att det ibland kallas "det svenska idealet".', difficulty: 'easy', partOfSpeech: 'adjektiv' },
  { dateKey: '2026-03-09', word: 'Smultronstalle', definition: 'En hemlig favorit plats for avkoppling och gladje.', etymology: 'Bokstavligen "smultron-stalle" — en plats dar vilda jordgubbar vaxer.', example: 'Stugan vid sjon ar mitt smultronstalle.', funFact: 'Ingmar Bergmans film "Smultronstallet" (1957) gjorde ordet kant internationellt.', difficulty: 'medium', partOfSpeech: 'substantiv' },
  { dateKey: '2026-03-08', word: 'Fika', definition: 'En kaffepaus, ofta med bakverk, som social tradition.', etymology: 'Slang fran 1800-talet — bokstaverna i "kaffi" (kaffe) omvanda.', example: 'Ska vi ta en fika pa det nya kafeet?', funFact: 'Svenskar dricker tredje mest kaffe i varlden per capita.', difficulty: 'easy', partOfSpeech: 'substantiv/verb' },
  { dateKey: '2026-03-07', word: 'Mångata', definition: 'Den glittrande strimman av mansken pa vatten.', etymology: 'Fran "mane" (moon) + "gata" (street) — bokstavligt "mangata".', example: 'Vi satt pa bryggan och tittade pa mangatan over sjon.', funFact: 'Ett av de mest delade "vackra svenska ord" pa sociala medier globalt.', difficulty: 'medium', partOfSpeech: 'substantiv' },
  { dateKey: '2026-03-06', word: 'Gokotta', definition: 'Att stiga upp tidigt pa morgonen for att hora faglar sjunga.', etymology: 'Fran "gok" (gok) + "otta" (tidig morgon).', example: 'Pa Kristi himmelsfardsdag ar det tradition med gokotta.', funFact: 'En unik svensk tradition kopplad till Kristi himmelsfardsdag.', difficulty: 'hard', partOfSpeech: 'substantiv' },
  { dateKey: '2026-03-05', word: 'Vemod', definition: 'En mild, poetisk sorg; ljuv melankolie.', etymology: 'Fran fornsvenska, beslaektat med "ve" (sorg) och "mod" (sinne).', example: 'En kansla av vemod fyllde honom nar han sag barndomshemmet.', funFact: 'Vemod skiljer sig fran sorg — det ar en vacker, nostalgisk kansla.', difficulty: 'medium', partOfSpeech: 'substantiv' },
  { dateKey: '2026-03-04', word: 'Orka', definition: 'Att ha energi eller ork att gora nagot.', etymology: 'Fran fornsvenska "orka" — styrka, formaga.', example: 'Jag orkar inte springa langre, jag ar for trott.', funFact: '"Orka" anvands ofta ironiskt bland ungdomar: "Orka..." = "Palansen inte..."', difficulty: 'easy', partOfSpeech: 'verb' },
  { dateKey: '2026-03-03', word: 'Skimrande', definition: 'Glittrande, lysande med ett mjukt, flackande ljus.', etymology: 'Fran "skimra" — att ge ifran sig ett svagt, flackande ljus.', example: 'Sjon lag skimrande i solnedgangens ljus.', funFact: 'Beslaektat med engelskans "shimmer" — bada fran germanskt ursprung.', difficulty: 'medium', partOfSpeech: 'adjektiv' },
  { dateKey: '2026-03-02', word: 'Dromsk', definition: 'Dromliknande, dagdrommande; forsjunken i tankar.', etymology: 'Fran "drom" (drom) med adjektivandelsen "-sk".', example: 'Hon hade ett dromskt uttryck i ogonen.', funFact: 'Uttrycker en typiskt nordisk kansla av dagdrommeri och eftertanke.', difficulty: 'hard', partOfSpeech: 'adjektiv' },
  { dateKey: '2026-03-01', word: 'Blunder', definition: 'Ett dumt, klumpigt misstag.', etymology: 'Fran engelska "blunder", som i sin tur kommer fran fornnordiska.', example: 'Att skicka mejlet till fel person var en riktig blunder.', funFact: 'Ordet vandrade fran nordiska till engelska och tillbaka till svenska!', difficulty: 'easy', partOfSpeech: 'substantiv' },
  { dateKey: '2026-02-28', word: 'Himmelsblå', definition: 'Den klara bla fargen pa en molnfri himmel.', etymology: 'Fran "himmel" + "bla" — bokstavligen himlens farg.', example: 'Havet var nastan himmelsblatt den dagen.', funFact: 'Sverige har en sarskild koppling till bla — det ar en av nationalfargerna.', difficulty: 'easy', partOfSpeech: 'adjektiv' },
  { dateKey: '2026-02-27', word: 'Trollbunden', definition: 'Fangad av troll; helt fascinated, fortrollad.', etymology: 'Fran "troll" + "bunden" (bunden) — bokstavligt "bunden av troll".', example: 'Publiken satt trollbunden under hela forestallningen.', funFact: 'Troll ar centrala i nordisk folktra och Skandinaviens kulturarv.', difficulty: 'medium', partOfSpeech: 'adjektiv' },
  { dateKey: '2026-02-26', word: 'Yrvaket', definition: 'Forvirrad och desorienterad precis efter att ha vaknat.', etymology: 'Fran "yr" (virrig) + "vaken" (vaken).', example: 'Han svarade i telefonen helt yrvaket klockan tre pa natten.', funFact: 'De flesta sprak saknar ett specifikt ord for detta vardagliga tillstand.', difficulty: 'hard', partOfSpeech: 'adjektiv' },
  { dateKey: '2026-02-25', word: 'Mysa', definition: 'Att ha det mysigt; koppla av i en varm, trivsam miljo.', etymology: 'Beslaektat med danskans "hygge", fran fornsvenska.', example: 'Pa fredagskvallen vill jag bara mysa med en bok och te.', funFact: 'Liknar danska "hygge" men med en mer personlig, lugn nyans.', difficulty: 'easy', partOfSpeech: 'verb' },
];

const jaWords: WordEntry[] = [
  { dateKey: '2026-03-10', word: '木漏れ日', definition: '木々の葉の隙間から差し込む日光。', etymology: '「木」（き）＋「漏れ」（もれ）＋「日」（ひ）— 木から漏れる日の光。', example: '公園の木漏れ日の中で読書を楽しんだ。', funFact: 'この美しい概念を一語で表せる言語はほとんどなく、世界中で愛されている日本語です。', difficulty: 'medium', partOfSpeech: '名詞' },
  { dateKey: '2026-03-09', word: '侘寂', definition: '不完全さの中に見出す美しさ。', etymology: '「侘」（わび：質素な美）＋「寂」（さび：時の経過による美）。', example: '古い陶器のひび割れに侘寂の美を感じた。', funFact: '千利休の茶道哲学の中心概念で、日本美学の根幹をなします。', difficulty: 'hard', partOfSpeech: '名詞' },
  { dateKey: '2026-03-08', word: '懐かしい', definition: '過去を思い出して温かい気持ちになること。', etymology: '古語「懐く」（なつく：親しむ）から派生。', example: 'この歌を聴くと子供時代が懐かしい。', funFact: '英語の「nostalgic」より肯定的なニュアンスが強く、痛みより温かさを感じさせます。', difficulty: 'easy', partOfSpeech: '形容詞' },
  { dateKey: '2026-03-07', word: '積ん読', definition: '買ったまま読まずに積んでおくこと。', etymology: '「積む」（つむ）＋「読」（どく）の語呂合わせ。', example: '本棚の積ん読が増える一方だ。', funFact: '明治時代から使われており、世界中の本好きが共感する日本語として有名です。', difficulty: 'medium', partOfSpeech: '名詞' },
  { dateKey: '2026-03-06', word: '一期一会', definition: '一生に一度きりの出会いを大切にすること。', etymology: '茶道用語。「一期」（一生）＋「一会」（一つの出会い）。', example: '旅先での出会いを一期一会の精神で楽しんだ。', funFact: '千利休の弟子・山上宗二が広めた茶道の根本精神です。', difficulty: 'medium', partOfSpeech: '名詞' },
  { dateKey: '2026-03-05', word: '切ない', definition: '胸が締めつけられるような、悲しくも美しい感情。', etymology: '古語「切なし」から。「切る」ほど胸が痛む感覚。', example: '別れの場面が切なくて涙が出た。', funFact: '英語では一語で訳せない感情で、bittersweet に近いが完全には一致しません。', difficulty: 'easy', partOfSpeech: '形容詞' },
  { dateKey: '2026-03-04', word: '森林浴', definition: '森の中を歩いて心身をリフレッシュすること。', etymology: '「森林」＋「浴」（浴びる）— 森を浴びる。', example: '週末は近くの森で森林浴を楽しんでいる。', funFact: '1982年に林野庁が提唱。科学的にストレスホルモンが減少することが証明されています。', difficulty: 'easy', partOfSpeech: '名詞' },
  { dateKey: '2026-03-03', word: '幽玄', definition: '奥深く神秘的な美しさ。言葉では表せない趣。', etymology: '「幽」（かすかな）＋「玄」（奥深い）— 中国哲学由来。', example: '能の舞台には幽玄な雰囲気が漂っていた。', funFact: '能楽の世阿弥が理想とした美意識で、日本芸術の最高概念の一つです。', difficulty: 'hard', partOfSpeech: '名詞' },
  { dateKey: '2026-03-02', word: '金継ぎ', definition: '割れた陶器を金で修復する日本の伝統技法。', etymology: '「金」（きん）＋「継ぐ」（つぐ：つなぐ）。', example: '金継ぎされた茶碗は元より美しくなった。', funFact: '「壊れたものは隠すのではなく、美しく直す」という哲学が世界中で注目されています。', difficulty: 'medium', partOfSpeech: '名詞' },
  { dateKey: '2026-03-01', word: '生きがい', definition: '生きる喜び、人生の目的や張り合い。', etymology: '「生き」（いき：生きること）＋「甲斐」（かい：価値）。', example: '孫の成長を見ることが祖母の生きがいだ。', funFact: '沖縄の長寿の秘訣として「生きがい」が世界的に注目されています。', difficulty: 'easy', partOfSpeech: '名詞' },
  { dateKey: '2026-02-28', word: '物の哀れ', definition: 'ものごとの移ろいに対する深い感動や哀愁。', etymology: '「物」（もの）＋「哀れ」（あわれ：しみじみとした感情）。', example: '散る桜に物の哀れを感じた。', funFact: '本居宣長が『源氏物語』の本質として提唱した日本文学の中心概念です。', difficulty: 'hard', partOfSpeech: '名詞' },
  { dateKey: '2026-02-27', word: '縁', definition: '人と人との不思議なつながり、巡り合わせ。', etymology: '仏教用語「因縁」から。原因と条件の結びつき。', example: 'こうして出会えたのも何かの縁ですね。', funFact: '「縁がある」「縁を感じる」など、日本人の人間関係観の根底にある概念です。', difficulty: 'easy', partOfSpeech: '名詞' },
  { dateKey: '2026-02-26', word: '花鳥風月', definition: '自然の美しい風物。風雅な趣。', etymology: '「花」「鳥」「風」「月」— 四つの自然の象徴を並べた四字熟語。', example: '日本庭園は花鳥風月の世界を凝縮している。', funFact: 'しりとりや言葉遊びでも人気の四字熟語です。', difficulty: 'medium', partOfSpeech: '名詞' },
  { dateKey: '2026-02-25', word: '七転び八起き', definition: '何度失敗しても諦めずに立ち上がること。', etymology: '「七回転んでも八回起き上がる」という意味のことわざ。', example: '七転び八起きの精神で事業を成功させた。', funFact: 'だるまの置物はこの精神を象徴しており、倒しても起き上がります。', difficulty: 'medium', partOfSpeech: '名詞' },
];

const esWords: WordEntry[] = [
  { dateKey: '2026-03-10', word: 'Sobremesa', definition: 'El tiempo que se pasa conversando en la mesa despues de comer.', etymology: 'Del latin "super" (sobre) + "mensa" (mesa) — literalmente "sobre la mesa".', example: 'La sobremesa del domingo duro mas de dos horas.', funFact: 'Es una tradicion tan importante en Espana que no existe una traduccion directa en ingles.', difficulty: 'easy', partOfSpeech: 'sustantivo' },
  { dateKey: '2026-03-09', word: 'Madrugada', definition: 'Las horas entre la medianoche y el amanecer.', etymology: 'Del latin "maturare" — madrugar, levantarse temprano.', example: 'Llegamos a casa en la madrugada despues de la fiesta.', funFact: 'Pocos idiomas tienen una palabra especifica para este periodo del dia.', difficulty: 'easy', partOfSpeech: 'sustantivo' },
  { dateKey: '2026-03-08', word: 'Desvelado', definition: 'Que no puede dormir; que se ha quedado despierto toda la noche.', etymology: 'Del prefijo "des-" + "velo" (del latin vigilare, estar alerta).', example: 'Estoy desvelado porque no pare de pensar en el examen.', funFact: 'En Mexico se usa mucho como sustantivo: "Soy un desvelado" (soy alguien que trasnocha).', difficulty: 'medium', partOfSpeech: 'adjetivo' },
  { dateKey: '2026-03-07', word: 'Empalagar', definition: 'Causar hastio o cansancio por exceso de dulzura o amabilidad.', etymology: 'Del latin "impalare" transformado — originalmente "pegar al paladar".', example: 'El postre era tan dulce que llegaba a empalagar.', funFact: 'Se usa tanto para comida como para personas: "Esa pelicula romantica empalaga".', difficulty: 'medium', partOfSpeech: 'verbo' },
  { dateKey: '2026-03-06', word: 'Estrenar', definition: 'Usar algo por primera vez; presentar algo nuevo al publico.', etymology: 'Del latin "extraneare" — hacer algo por primera vez.', example: 'Manana voy a estrenar mis zapatos nuevos.', funFact: 'En espanol se "estrena" ropa nueva, pero en ingles simplemente se "usa por primera vez".', difficulty: 'easy', partOfSpeech: 'verbo' },
  { dateKey: '2026-03-05', word: 'Duende', definition: 'Encanto misterioso e indefinible; poder magico de una obra de arte.', etymology: 'Contraccion de "duen de casa" (dueno de casa) — un espiritu domestico.', example: 'La bailaora de flamenco tenia un duende que cautivaba al publico.', funFact: 'Federico Garcia Lorca escribio un famoso ensayo sobre el duende en el arte.', difficulty: 'hard', partOfSpeech: 'sustantivo' },
  { dateKey: '2026-03-04', word: 'Friolento', definition: 'Persona que es muy sensible al frio.', etymology: 'De "frio" + sufijo "-lento" que indica tendencia.', example: 'Soy tan friolento que uso bufanda incluso en primavera.', funFact: 'En Argentina se dice "friolento", en Espana "friolero" — mismo concepto, distinta palabra.', difficulty: 'easy', partOfSpeech: 'adjetivo' },
  { dateKey: '2026-03-03', word: 'Tertulia', definition: 'Reunion informal de personas para conversar sobre temas culturales.', etymology: 'Posiblemente de Tertuliano, teologo romano conocido por sus debates.', example: 'Cada viernes nos reunimos para una tertulia literaria en el cafe.', funFact: 'Las tertulias fueron fundamentales en la vida intelectual espanola del siglo XIX.', difficulty: 'medium', partOfSpeech: 'sustantivo' },
  { dateKey: '2026-03-02', word: 'Chapuza', definition: 'Trabajo mal hecho, de baja calidad; remiendo torpe.', etymology: 'Origen incierto, posiblemente onomatopeyico del sonido de un trabajo descuidado.', example: 'La reparacion fue una chapuza — se volvio a romper al dia siguiente.', funFact: 'En Espana, un "chapuzas" es una persona que hace trabajos de mala calidad.', difficulty: 'medium', partOfSpeech: 'sustantivo' },
  { dateKey: '2026-03-01', word: 'Atardecer', definition: 'El momento del dia en que el sol se pone; el crepusculo vespertino.', etymology: 'De "a-" + "tarde" + "-ecer" — literalmente "hacerse tarde".', example: 'El atardecer sobre el mar fue espectacular.', funFact: 'En espanol, "atardecer" es tanto sustantivo como verbo: "esta atardeciendo".', difficulty: 'easy', partOfSpeech: 'sustantivo/verbo' },
  { dateKey: '2026-02-28', word: 'Quisquilloso', definition: 'Persona que se molesta por cosas insignificantes; muy exigente.', etymology: 'De "quisquilla" (cosa insignificante), del latin "quisquiliae" (desperdicios).', example: 'No seas tan quisquilloso con la comida, prueba algo nuevo.', funFact: 'Tiene 12 letras y es un favorito en juegos de palabras en espanol.', difficulty: 'hard', partOfSpeech: 'adjetivo' },
  { dateKey: '2026-02-27', word: 'Entranable', definition: 'Que inspira carino profundo y sincero; muy querido.', etymology: 'De "entranas" (entranas) — algo que se siente desde lo mas profundo.', example: 'Mi abuela es una persona entranable que todos adoran.', funFact: 'Literalmente significa "de las entranas" — el carino viene de lo mas profundo del ser.', difficulty: 'medium', partOfSpeech: 'adjetivo' },
  { dateKey: '2026-02-26', word: 'Trasnochar', definition: 'Quedarse despierto hasta muy tarde en la noche.', etymology: 'De "tras" (despues de) + "noche" — ir mas alla de la noche.', example: 'Los estudiantes suelen trasnochar antes de los examenes.', funFact: 'En espanol existe "trasnochar" (quedarse despierto) y "madrugar" (levantarse temprano) como verbos especificos.', difficulty: 'medium', partOfSpeech: 'verbo' },
  { dateKey: '2026-02-25', word: 'Efimero', definition: 'Que dura muy poco tiempo; pasajero y fugaz.', etymology: 'Del griego ephemeros — "que dura un dia".', example: 'La fama en redes sociales es efimera.', funFact: 'Comparte raiz con "ephemeral" en ingles — ambas del griego antiguo.', difficulty: 'medium', partOfSpeech: 'adjetivo' },
];

export const wordsByLocale: Record<Locale, WordEntry[]> = {
  en: enWords,
  he: heWords,
  sv: svWords,
  ja: jaWords,
  es: esWords,
};

const ISO_DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
const ROTATION_EPOCH_MS = Date.UTC(2026, 0, 1);
const MS_PER_DAY = 86_400_000;

function localeWords(locale: Locale): WordEntry[] {
  return wordsByLocale[locale] && wordsByLocale[locale].length > 0
    ? wordsByLocale[locale]
    : wordsByLocale.en;
}

export function getWordByDate(locale: Locale, dateKey: string): WordEntry | null {
  if (!dateKey || !ISO_DATE_RE.test(dateKey)) return null;
  const words = localeWords(locale);
  return words.find((w) => w.dateKey === dateKey) ?? null;
}

export function getRotatedTodayWord(locale: Locale, dateKey: string): WordEntry {
  const words = localeWords(locale);
  const exact = words.find((w) => w.dateKey === dateKey);
  if (exact) return exact;
  if (!ISO_DATE_RE.test(dateKey)) return words[0];
  const dayIndex = Math.floor((Date.parse(dateKey + 'T00:00:00Z') - ROTATION_EPOCH_MS) / MS_PER_DAY);
  const idx = ((dayIndex % words.length) + words.length) % words.length;
  return words[idx];
}

export function getTodayWord(locale: Locale): WordEntry {
  const today = new Date().toISOString().slice(0, 10);
  return getRotatedTodayWord(locale, today);
}

