// Hand-curated crossword puzzles. These are REAL crosswords — black blocks, varied word lengths,
// across and down are DIFFERENT interlocking words (NOT symmetric word squares), and every white
// cell is checked in both directions. Grids were filled by scripts/crossword/build.ts from a
// curated common-word pool (so every entry is a real, cluable dictionary word) and every clue is
// hand-authored below. Clues are keyed by SLOT ID (A1/D2…). See quality invariants in
// lib/crossword/puzzles/__tests__/quality.test.ts and docs/2026-06-06-crossword-quality-overhaul-spec.md.
//
// English: 5×5 minis (2- and 4-block layouts). Hebrew: 4×4 minis — Hebrew's compact vocabulary
// has few common 5-letter words, so a doubly-checked 5×5 won't fill cleanly; the 4×4 is a genuine
// mini crossword that fits. Hebrew grids store NORMALIZED (non-sofit) letters; the renderer applies
// final forms at word end.

import type { Difficulty, PuzzleLocale } from '../types';

export interface SeedPuzzle {
  id: string;
  locale: PuzzleLocale;
  difficulty: Difficulty;
  rtl: boolean;
  grid: (string | null)[][];
  /** clue text keyed by slot id (e.g. "A1", "D2"). */
  clues: Record<string, string>;
}

export const EN_SEED: SeedPuzzle[] = [
  {
    id: 'en-mini-001',
    locale: 'en',
    difficulty: 'easy',
    rtl: false,
    grid: [
      [null, 'b', 'e', 's', 't'],
      ['s', 'l', 'a', 't', 'e'],
      ['w', 'a', 'g', 'o', 'n'],
      ['a', 'm', 'e', 'n', 'd'],
      ['m', 'e', 'r', 'e', null],
    ],
    clues: {
      A1: 'The very finest',
      A5: 'Wipe the ___ clean',
      A6: 'Cart pulled by horses',
      A7: 'Make changes to',
      A8: 'Nothing more than',
      D1: 'Pin the fault on',
      D2: 'Keen and raring to go',
      D3: 'A rock, or a peach pit',
      D4: 'Look after',
      D5: 'Did laps in the pool',
    },
  },
  {
    id: 'en-mini-002',
    locale: 'en',
    difficulty: 'easy',
    rtl: false,
    grid: [
      [null, 's', 'a', 'l', 't'],
      ['s', 'o', 'l', 'a', 'r'],
      ['a', 'l', 'o', 'n', 'e'],
      ['m', 'i', 'n', 'c', 'e'],
      ['e', 'd', 'g', 'e', null],
    ],
    clues: {
      A1: 'Shaker beside the pepper',
      A5: '___ panel: sun-powered',
      A6: 'All by yourself',
      A7: 'Chop into tiny bits',
      A8: 'Border of a table',
      D1: 'Not liquid or gas',
      D2: 'Come ___ for the ride',
      D3: "Knight's long spear",
      D4: 'It has bark and leaves',
      D5: 'Identical; not different',
    },
  },
  {
    id: 'en-mini-003',
    locale: 'en',
    difficulty: 'medium',
    rtl: false,
    grid: [
      [null, 'd', 'a', 's', 'h'],
      ['f', 'o', 'r', 'c', 'e'],
      ['a', 'n', 'g', 'e', 'r'],
      ['s', 'o', 'u', 'n', 'd'],
      ['t', 'r', 'e', 'e', null],
    ],
    clues: {
      A1: 'Quick sprint',
      A5: 'May the ___ be with you',
      A6: 'Rage; what makes you see red',
      A7: 'Noise you can hear',
      A8: 'Oak or maple',
      D1: 'One who gives blood',
      D2: 'Quarrel over something',
      D3: 'Part of a play',
      D4: 'Group of cattle',
      D5: 'Speedy; quick',
    },
  },
  {
    id: 'en-mini-004',
    locale: 'en',
    difficulty: 'medium',
    rtl: false,
    grid: [
      [null, 'p', 'r', 'o', 'p'],
      ['s', 'h', 'o', 'n', 'e'],
      ['h', 'o', 'u', 's', 'e'],
      ['o', 't', 't', 'e', 'r'],
      ['p', 'o', 'e', 't', null],
    ],
    clues: {
      A1: 'Object an actor handles on stage',
      A5: 'Glowed brightly',
      A6: 'Place where you live',
      A7: 'Playful river mammal',
      A8: 'Writer of verse',
      D1: 'Snapshot',
      D2: 'Path from A to B',
      D3: 'The very beginning',
      D4: 'Look closely, or an equal',
      D5: 'Store where you buy things',
    },
  },
  {
    id: 'en-mini-005',
    locale: 'en',
    difficulty: 'easy',
    rtl: false,
    grid: [
      [null, 's', 't', 'e', 'w'],
      ['s', 't', 'o', 'v', 'e'],
      ['t', 'a', 'k', 'e', 'n'],
      ['a', 'g', 'e', 'n', 't'],
      ['r', 'e', 'n', 't', null],
    ],
    clues: {
      A1: 'Hearty simmered dish',
      A5: 'You cook on it',
      A6: 'Already claimed',
      A7: 'Secret ___: a 007',
      A8: 'Monthly payment to a landlord',
      D1: 'Where the play happens',
      D2: 'Arcade coin, or a small gift',
      D3: 'Special happening',
      D4: 'Did go',
      D5: 'Twinkler in the night sky',
    },
  },
  {
    id: 'en-mini-006',
    locale: 'en',
    difficulty: 'medium',
    rtl: false,
    grid: [
      [null, 's', 'w', 'a', 'p'],
      ['s', 'c', 'e', 'n', 'e'],
      ['l', 'o', 'd', 'g', 'e'],
      ['a', 'n', 'g', 'e', 'l'],
      ['p', 'e', 'e', 'r', null],
    ],
    clues: {
      A1: 'Trade one for another',
      A5: 'Setting of the action',
      A6: 'Cabin in the woods',
      A7: 'Winged heavenly being',
      A8: 'Someone your own age',
      D1: 'Baked treat served with tea',
      D2: 'Triangular slice',
      D3: 'Hot temper',
      D4: "Remove a banana's skin",
      D5: 'Smack with an open hand',
    },
  },
  {
    id: 'en-mini-007',
    locale: 'en',
    difficulty: 'medium',
    rtl: false,
    grid: [
      [null, 'v', 'e', 's', 't'],
      ['s', 'i', 'n', 'c', 'e'],
      ['u', 'l', 't', 'r', 'a'],
      ['c', 'l', 'e', 'a', 'r'],
      ['h', 'a', 'r', 'p', null],
    ],
    clues: {
      A1: 'Sleeveless top',
      A5: 'From then until now',
      A6: 'Extreme; beyond the usual',
      A7: 'Easy to see through',
      A8: 'Large stringed instrument',
      D1: 'Fancy country house',
      D2: 'Go in',
      D3: 'Tiny leftover piece',
      D4: 'Rip apart, or an eye drop',
      D5: '___ a nice day!',
    },
  },
  {
    id: 'en-mini-008',
    locale: 'en',
    difficulty: 'easy',
    rtl: false,
    grid: [
      ['e', 'a', 'c', 'h', null],
      ['a', 'l', 'l', 'o', 'w'],
      ['s', 't', 'o', 'r', 'e'],
      ['t', 'e', 'n', 's', 'e'],
      [null, 'r', 'e', 'e', 'd'],
    ],
    clues: {
      A1: 'Every single one',
      A5: 'Permit; let happen',
      A7: 'Shop, or to stock away',
      A8: 'Nervous and on edge',
      A9: 'Marsh plant by the water',
      D1: 'Where the sun rises',
      D2: 'Change or modify',
      D3: 'Exact genetic copy',
      D4: 'Animal you saddle and ride',
      D6: 'Unwanted garden plant',
    },
  },
  {
    id: 'en-mini-009',
    locale: 'en',
    difficulty: 'medium',
    rtl: false,
    grid: [
      ['p', 'a', 's', 't', null],
      ['a', 'l', 't', 'e', 'r'],
      ['s', 't', 'o', 'n', 'e'],
      ['s', 'a', 'l', 's', 'a'],
      [null, 'r', 'e', 'e', 'l'],
    ],
    clues: {
      A1: 'Times gone by',
      A5: 'Tweak or adjust',
      A7: 'Rock, or a cherry pit',
      A8: 'Spicy dip, or a Latin dance',
      A9: 'Spool on a fishing rod',
      D1: 'Go by, or a ticket of entry',
      D2: 'Front table in a church',
      D3: 'Took without asking',
      D4: 'Tight with nerves',
      D6: 'Genuine; not fake',
    },
  },
  {
    id: 'en-mini-010',
    locale: 'en',
    difficulty: 'medium',
    rtl: false,
    grid: [
      ['c', 'a', 's', 't', null],
      ['a', 'l', 'l', 'o', 'w'],
      ['s', 't', 'a', 'k', 'e'],
      ['h', 'a', 'v', 'e', 'n'],
      [null, 'r', 'e', 'n', 't'],
    ],
    clues: {
      A1: 'The actors in a show',
      A5: 'Give permission',
      A7: 'Pointed post, or a bet',
      A8: 'Safe, peaceful refuge',
      A9: 'What a tenant pays',
      D1: 'Coins and bills',
      D2: 'Where vows are exchanged',
      D3: 'One forced to work unfree',
      D4: 'Bus-fare coin, or a keepsake',
      D6: 'Departed',
    },
  },
  {
    id: 'en-mini-011',
    locale: 'en',
    difficulty: 'medium',
    rtl: false,
    grid: [
      [null, 'h', 'a', 'd', null],
      ['r', 'e', 'n', 'e', 'w'],
      ['e', 'a', 'g', 'l', 'e'],
      ['d', 'r', 'e', 'a', 'd'],
      [null, 't', 'r', 'y', null],
    ],
    clues: {
      A1: 'Possessed, in the past',
      A4: 'Extend a subscription',
      A6: 'Bald bird on the US seal',
      A7: 'Fear what is coming',
      A8: 'Give it a go',
      D1: 'It pumps your blood',
      D2: 'Fury; rage',
      D3: 'Hold-up; postponement',
      D4: 'Color of a stop sign',
      D5: 'Get married',
    },
  },
  {
    id: 'en-mini-012',
    locale: 'en',
    difficulty: 'medium',
    rtl: false,
    grid: [
      [null, 'v', 'o', 'w', null],
      ['t', 'a', 'l', 'o', 'n'],
      ['a', 'l', 'i', 'v', 'e'],
      ['r', 'i', 'v', 'e', 't'],
      [null, 'd', 'e', 'n', null],
    ],
    clues: {
      A1: 'Solemn promise',
      A4: "Eagle's sharp claw",
      A6: 'Living and breathing',
      A7: 'Metal bolt, or to grip attention',
      A8: 'Cozy room, or a lion’s home',
      D1: 'Legitimate; still in effect',
      D2: 'Green fruit on a pizza',
      D3: 'Made on a loom',
      D4: 'Black road goo',
      D5: 'What catches a fish',
    },
  },
  {
    id: 'en-mini-013',
    locale: 'en',
    difficulty: 'medium',
    rtl: false,
    grid: [
      [null, 'o', 'l', 'd', null],
      ['s', 'p', 'e', 'e', 'd'],
      ['p', 'e', 'a', 'c', 'e'],
      ['a', 'r', 'r', 'o', 'w'],
      [null, 'a', 'n', 'y', null],
    ],
    clues: {
      A1: 'Not young',
      A4: 'How fast you go',
      A6: 'Calm; no war',
      A7: 'It flies from a bow',
      A8: 'Even one will do',
      D1: 'Sung dramatic stage show',
      D2: 'Pick up new knowledge',
      D3: 'Duck-shaped lure',
      D4: 'Place for a massage',
      D5: 'Morning droplets on grass',
    },
  },
];

export const HE_SEED: SeedPuzzle[] = [
  {
    id: 'he-mini-001',
    locale: 'he',
    difficulty: 'easy',
    rtl: true,
    grid: [
      [null, 'א', 'ו', 'ר'],
      ['ב', 'ו', 'ר', 'ח'],
      ['ר', 'ט', 'ו', 'ב'],
      ['ד', 'ו', 'ד', null],
    ],
    clues: {
      A1: 'הפוך מחושך',
      A4: 'נמלט; רץ מפני סכנה',
      A5: 'ספוג במים; הפוך מיבש',
      A6: 'אח של אבא או אמא',
      D1: 'מכונית; רכב פרטי',
      D2: 'צבע בין אדום ללבן',
      D3: 'הפוך מצר',
      D4: 'כדורי קרח שיורדים מהשמיים',
    },
  },
  {
    id: 'he-mini-002',
    locale: 'he',
    difficulty: 'easy',
    rtl: true,
    grid: [
      [null, 'ש', 'ל', 'ח'],
      ['נ', 'ע', 'י', 'מ'],
      ['ח', 'ו', 'ל', 'ה'],
      ['ש', 'נ', 'ה', null],
    ],
    clues: {
      A1: 'העביר דבר ליעד; שיגר',
      A4: 'מהנה ונחמד',
      A5: 'מי שאינו בריא',
      A6: '365 ימים',
      D1: 'מכשיר שמראה את הזמן',
      D2: 'הזמן החשוך של היממה',
      D3: 'כינוי לשמש',
      D4: 'זוחל ארוך ללא רגליים',
    },
  },
  {
    id: 'he-mini-003',
    locale: 'he',
    difficulty: 'easy',
    rtl: true,
    grid: [
      [null, 'נ', 'ח', 'ש'],
      ['צ', 'ע', 'י', 'פ'],
      ['מ', 'י', 'ט', 'ה'],
      ['ח', 'מ', 'ה', null],
    ],
    clues: {
      A1: 'זוחל שמשמיע שש',
      A4: 'עוטפים בו את הצוואר בחורף',
      A5: 'רהיט שעליו ישנים',
      A6: 'השמש, בלשון אחרת',
      D1: 'גדל באדמה; פרח או עץ קטן',
      D2: 'ממנה עושים קמח ולחם',
      D3: 'אנגלית או עברית, למשל',
      D4: 'מהנה ונחמד',
    },
  },
  {
    id: 'he-mini-004',
    locale: 'he',
    difficulty: 'easy',
    rtl: true,
    grid: [
      [null, 'ש', 'מ', 'ע'],
      ['י', 'ו', 'ש', 'ב'],
      ['ש', 'מ', 'ח', 'ה'],
      ['ב', 'ר', 'ק', null],
    ],
    clues: {
      A1: 'קלט באוזניים',
      A4: 'אינו עומד; נמצא על כיסא',
      A5: 'אושר; רגש טוב',
      A6: 'אור פתאומי בסערה',
      D1: 'מי ששומר ומגן על מקום',
      D2: 'כדורגל או שחמט, למשל',
      D3: 'הפוך מדק',
      D4: 'התיישב',
    },
  },
  {
    id: 'he-mini-005',
    locale: 'he',
    difficulty: 'medium',
    rtl: true,
    grid: [
      [null, 'מ', 'צ', 'ח'],
      ['ד', 'ג', 'י', 'מ'],
      ['א', 'ר', 'י', 'ה'],
      ['ג', 'ש', 'ר', null],
    ],
    clues: {
      A1: 'החלק העליון של הפנים',
      A4: 'חיים במים ושוחים',
      A5: 'מלך החיות',
      A6: 'מעבר מעל נהר',
      D1: 'שטח שמשחקים בו כדורגל',
      D2: 'אמן שמצייר תמונות',
      D3: 'כינוי לשמש',
      D4: 'חשש; היה מודאג',
    },
  },
  {
    id: 'he-mini-006',
    locale: 'he',
    difficulty: 'medium',
    rtl: true,
    grid: [
      ['ר', 'א', 'ש', null],
      ['א', 'ו', 'מ', 'ר'],
      ['ה', 'ו', 'ל', 'כ'],
      [null, 'ז', 'ה', 'ב'],
    ],
    clues: {
      A1: 'החלק העליון של הגוף',
      A4: 'מדבר; מבטא מילים',
      A6: 'צועד ברגל',
      A7: 'מתכת יקרה וצהובה',
      D1: 'הביט בעיניים',
      D2: 'עוף מים גדול שמגעגע',
      D3: 'לבוש של נשים',
      D5: 'אוטו או אופנוע, למשל',
    },
  },
];
