#!/usr/bin/env node
/**
 * Build-time script: scans app/[locale]/ for page.tsx files
 * and writes the static route list to utils/generatedRoutes.ts.
 * Called automatically before `next build`.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const EXCLUDED_DIRS = new Set(['admin', 'auth', 'api', 'avatar-test']);

function scan(baseDir, relativePath, routes) {
  const fullPath = path.join(baseDir, relativePath);
  const entries = fs.readdirSync(fullPath, { withFileTypes: true });

  if (entries.some(e => e.isFile() && e.name === 'page.tsx')) {
    const route = relativePath ? '/' + relativePath.replace(/\\/g, '/') : '';
    routes.push(route);
  }

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (EXCLUDED_DIRS.has(entry.name)) continue;
    if (entry.name.startsWith('[') || entry.name.startsWith('.') || entry.name.startsWith('_')) continue;
    scan(baseDir, path.join(relativePath, entry.name), routes);
  }
}

const localeDir = path.join(ROOT, 'app', '[locale]');
const routes = [];
scan(localeDir, '', routes);
routes.sort();

const output = `// Auto-generated by scripts/generate-routes.mjs — do not edit manually
export const PUBLIC_ROUTES: string[] = ${JSON.stringify(routes, null, 2)};
`;

fs.writeFileSync(path.join(ROOT, 'utils', 'generatedRoutes.ts'), output);
console.log(`Generated ${routes.length} public routes → utils/generatedRoutes.ts`);
