#!/bin/bash
# setup.sh — interactive first-time setup for the nightly loop.
# Detects existing values in fe-next/.env.local + fe-next/.env, prompts for the rest,
# writes ~/.config/lexi-nightly/env with chmod 600.
#
# Idempotent: re-run any time. Existing values become defaults; press Enter to keep them.

set -uo pipefail

ENV_FILE="$HOME/.config/lexi-nightly/env"
PROJECT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"

mkdir -p "$(dirname "$ENV_FILE")"
# Pre-create the launchd log directory (launchd cannot mkdir parents for
# StandardOutPath; missing dir = silent skip with error 72).
mkdir -p "$HOME/logs/lexi-nightly"

# --- helpers ---------------------------------------------------------------
existing() {
  # Echo existing value if env file already exists
  local key="$1"
  if [ -f "$ENV_FILE" ]; then
    grep -E "^${key}=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2- | sed -e 's/^"//' -e 's/"$//'
  fi
}

probe_dotenv() {
  # Pull a value from fe-next/.env.local or fe-next/.env (without exposing content)
  local key="$1"
  for f in "$PROJECT_DIR/fe-next/.env.local" "$PROJECT_DIR/fe-next/.env" "$PROJECT_DIR/.env"; do
    if [ -f "$f" ]; then
      local v
      v=$(grep -E "^${key}=" "$f" 2>/dev/null | head -1 | cut -d= -f2- | sed -e 's/^"//' -e 's/"$//')
      if [ -n "$v" ]; then echo "$v"; return; fi
    fi
  done
}

prompt() {
  # prompt "label" "var_name" "hint_url" [--secret]
  local label="$1"
  local var="$2"
  local hint="${3:-}"
  local secret="${4:-}"

  local default
  default=$(existing "$var")
  [ -z "$default" ] && default=$(probe_dotenv "$var")

  local masked="${default}"
  if [ "$secret" = "--secret" ] && [ -n "$default" ]; then
    masked="${default:0:6}…${default: -4}"
  fi

  echo
  echo "▸ $label"
  [ -n "$hint" ] && echo "  $hint"
  if [ -n "$default" ]; then
    read -p "  $var [keep current: $masked]: " input
    eval "${var}=\"${input:-$default}\""
  else
    read -p "  $var: " input
    eval "${var}=\"${input}\""
  fi
}

# --- prompts ---------------------------------------------------------------
echo "════════════════════════════════════════════"
echo "  Nightly Improvement Loop — first-time setup"
echo "════════════════════════════════════════════"
echo "Writes $ENV_FILE (chmod 600). Press Enter to keep current values."

prompt "Telegram bot token" \
       "TELEGRAM_BOT_TOKEN" \
       "Create via @BotFather (/newbot). Token format: 1234567890:ABC..." \
       --secret

prompt "Telegram chat ID (yours)" \
       "TELEGRAM_CHAT_ID" \
       "DM your bot once, then: curl https://api.telegram.org/bot\$TELEGRAM_BOT_TOKEN/getUpdates | jq '.result[-1].message.chat.id'"

prompt "PostHog Personal API Key" \
       "POSTHOG_PERSONAL_API_KEY" \
       "https://app.posthog.com/me/settings → Personal API keys → 'scope: read events, feature_flags, query'" \
       --secret

prompt "PostHog project ID (numeric)" \
       "POSTHOG_PROJECT_ID" \
       "Visit https://app.posthog.com/project → URL has /project/<NUMBER>/"

prompt "PostHog host" \
       "POSTHOG_HOST" \
       "https://us.i.posthog.com (default) or https://eu.i.posthog.com"
[ -z "${POSTHOG_HOST:-}" ] && POSTHOG_HOST="https://us.i.posthog.com"

prompt "Firecrawl API key (optional — lane 3 skips if blank)" \
       "FIRECRAWL_API_KEY" \
       "https://firecrawl.dev/app/api-keys (paid plan)" \
       --secret

prompt "Supabase URL" \
       "SUPABASE_URL" \
       "Default: https://hdtmpkicuxvtmvrmtybx.supabase.co"
[ -z "${SUPABASE_URL:-}" ] && SUPABASE_URL="https://hdtmpkicuxvtmvrmtybx.supabase.co"

prompt "Supabase service role key (only for direct SQL fallback; MCP usually suffices)" \
       "SUPABASE_SERVICE_ROLE_KEY" \
       "Supabase dashboard → Project Settings → API → service_role secret" \
       --secret

# --- write -----------------------------------------------------------------
cat > "$ENV_FILE" <<EOF
# ~/.config/lexi-nightly/env — generated by scripts/nightly/setup.sh
# chmod 600 — do NOT commit
TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN:-}"
TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID:-}"
POSTHOG_PERSONAL_API_KEY="${POSTHOG_PERSONAL_API_KEY:-}"
POSTHOG_PROJECT_ID="${POSTHOG_PROJECT_ID:-}"
POSTHOG_HOST="${POSTHOG_HOST}"
FIRECRAWL_API_KEY="${FIRECRAWL_API_KEY:-}"
SUPABASE_URL="${SUPABASE_URL}"
SUPABASE_SERVICE_ROLE_KEY="${SUPABASE_SERVICE_ROLE_KEY:-}"
# NIGHTLY_DISABLED=1   # uncomment to pause without unloading launchd
EOF
chmod 600 "$ENV_FILE"

echo
echo "✓ Wrote $ENV_FILE (chmod 600)"
echo

# --- verify ---------------------------------------------------------------
missing=()
for v in TELEGRAM_BOT_TOKEN TELEGRAM_CHAT_ID POSTHOG_PERSONAL_API_KEY POSTHOG_PROJECT_ID; do
  eval "val=\${$v:-}"
  [ -z "$val" ] && missing+=("$v")
done

if [ ${#missing[@]} -gt 0 ]; then
  echo "⚠ Missing required: ${missing[*]}"
  echo "  Re-run this script when you have them, or edit the file directly."
  exit 1
fi

echo "→ Smoke-test Telegram now? (y/N)"
read -r ans
if [[ "$ans" =~ ^[Yy] ]]; then
  set -a; . "$ENV_FILE"; set +a
  "$(dirname "$0")/lib/telegram.sh" msg "✓ nightly-loop setup OK — $(date '+%Y-%m-%d %H:%M')"
fi

echo
echo "Next steps:"
echo "  1. Dry-run:  ./scripts/nightly/run.sh --dry-run"
echo "  2. Inspect:  tail -f ~/logs/lexi-nightly/run-*.log"
echo "  3. Load launchd (subsumes seo-daily):"
echo "       launchctl unload ~/Library/LaunchAgents/com.claude.seo-daily.plist 2>/dev/null"
echo "       rm -f ~/Library/LaunchAgents/com.claude.seo-daily.plist"
echo "       cp scripts/nightly/com.claude.nightly-loop.plist ~/Library/LaunchAgents/"
echo "       launchctl load ~/Library/LaunchAgents/com.claude.nightly-loop.plist"
