import type { ConnectionPuzzle } from '../types';

export const EN_HARD: ConnectionPuzzle[] = [
  { id: 'en-h-001', word1: 'CHEST', word2: 'PLAY', bridge: 'FAIR', difficulty: 'hard', hint: 'Also a festival context' },
  { id: 'en-h-002', word1: 'CORN', word2: 'STONE', bridge: 'COBBLE', difficulty: 'hard', hint: 'Old street material' },
  { id: 'en-h-003', word1: 'HORSE', word2: 'BRIDGE', bridge: 'DRAW', difficulty: 'hard' },
  { id: 'en-h-004', word1: 'ROUGH', word2: 'HOUSE', bridge: 'SHOD', difficulty: 'hard' },
  { id: 'en-h-005', word1: 'BACK', word2: 'WARDS', bridge: 'STROKES', difficulty: 'hard' },
  { id: 'en-h-006', word1: 'FLAG', word2: 'STOP', bridge: 'SHIP', difficulty: 'hard' },
  { id: 'en-h-007', word1: 'CLOUD', word2: 'BURST', bridge: 'NINE', difficulty: 'hard' },
  { id: 'en-h-008', word1: 'DOUBLE', word2: 'TAKE', bridge: 'CROSS', difficulty: 'hard' },
  { id: 'en-h-009', word1: 'ELOPE', word2: 'MENT', bridge: 'ENGAGE', difficulty: 'hard' },
  { id: 'en-h-010', word1: 'FLAT', word2: 'OUT', bridge: 'SPIN', difficulty: 'hard', hint: 'A gymnastic move' },
  { id: 'en-h-011', word1: 'GRAVE', word2: 'SHIFT', bridge: 'YARD', difficulty: 'hard' },
  { id: 'en-h-012', word1: 'HOLLOW', word2: 'WEEN', bridge: 'HALL', difficulty: 'hard' },
  { id: 'en-h-013', word1: 'INTRO', word2: 'SPECT', bridge: 'VERT', difficulty: 'hard' },
  { id: 'en-h-014', word1: 'JAW', word2: 'LINE', bridge: 'DROP', difficulty: 'hard' },
  { id: 'en-h-016', word1: 'LEAN', word2: 'TO', bridge: 'OVER', difficulty: 'hard' },
  { id: 'en-h-017', word1: 'MEANDER', word2: 'ING', bridge: 'WANDER', difficulty: 'hard' },
  { id: 'en-h-018', word1: 'NERVE', word2: 'WRACKING', bridge: 'RACK', difficulty: 'hard' },
  { id: 'en-h-019', word1: 'OAK', word2: 'BARREL', bridge: 'EN', difficulty: 'hard' },
  { id: 'en-h-020', word1: 'PORE', word2: 'OVER', bridge: 'BONE', difficulty: 'hard' },
  { id: 'en-h-021', word1: 'RABBIT', word2: 'WARREN', bridge: 'HOLE', difficulty: 'hard' },
  { id: 'en-h-022', word1: 'SKULL', word2: 'BONE', bridge: 'CROSS', difficulty: 'hard' },
  { id: 'en-h-023', word1: 'TONGUE', word2: 'CHEEK', bridge: 'IN', difficulty: 'hard' },
  { id: 'en-h-025', word1: 'VEIL', word2: 'LIFTING', bridge: 'BRIDAL', difficulty: 'hard' },
  { id: 'en-h-026', word1: 'WARP', word2: 'DRIVE', bridge: 'SPEED', difficulty: 'hard' },
  { id: 'en-h-027', word1: 'XENON', word2: 'LAMP', bridge: 'ARC', difficulty: 'hard' },
  { id: 'en-h-028', word1: 'YIELD', word2: 'SIGN', bridge: 'ROAD', difficulty: 'hard' },
  { id: 'en-h-029', word1: 'ZENITH', word2: 'SKY', bridge: 'NADIR', difficulty: 'hard', hint: 'Opposite of zenith' },
  { id: 'en-h-030', word1: 'ANVIL', word2: 'HEAD', bridge: 'CLOUD', difficulty: 'hard' },
  { id: 'en-h-031', word1: 'BLEAK', word2: 'HOUSE', bridge: 'GRIM', difficulty: 'hard' },
  { id: 'en-h-032', word1: 'CLENCH', word2: 'FIST', bridge: 'IRON', difficulty: 'hard' },
  { id: 'en-h-033', word1: 'DUNCE', word2: 'CAP', bridge: 'NIGHT', difficulty: 'hard' },
  { id: 'en-h-034', word1: 'ELDER', word2: 'BERRY', bridge: 'STRAW', difficulty: 'hard' },
  { id: 'en-h-035', word1: 'FEATHER', word2: 'WEIGHT', bridge: 'LIGHT', difficulty: 'hard' },
  { id: 'en-h-036', word1: 'GHOST', word2: 'WRITER', bridge: 'COPY', difficulty: 'hard' },
  { id: 'en-h-037', word1: 'HAMLET', word2: 'VILLAGE', bridge: 'SMALL', difficulty: 'hard', hint: 'Shakespeare or small settlement?' },
  { id: 'en-h-038', word1: 'IVORY', word2: 'TOWER', bridge: 'TUSK', difficulty: 'hard' },
  { id: 'en-h-039', word1: 'JINX', word2: 'HEX', bridge: 'CURSE', difficulty: 'hard', hint: 'All three mean the same thing' },
  { id: 'en-h-040', word1: 'KERNEL', word2: 'TRUTH', bridge: 'CORN', difficulty: 'hard' },
  { id: 'en-h-041', word1: 'LIMELIGHT', word2: 'STAGE', bridge: 'LIME', difficulty: 'hard' },
  { id: 'en-h-043', word1: 'NICHE', word2: 'MARKET', bridge: 'ALCOVE', difficulty: 'hard' },
  { id: 'en-h-044', word1: 'OMEN', word2: 'SIGN', bridge: 'PORTENT', difficulty: 'hard', hint: 'Also a creepy film' },
  { id: 'en-h-045', word1: 'PRISM', word2: 'LIGHT', bridge: 'SPLIT', difficulty: 'hard' },
  { id: 'en-h-046', word1: 'QUIVER', word2: 'ARROW', bridge: 'BOW', difficulty: 'hard' },
  { id: 'en-h-047', word1: 'RAMPART', word2: 'WALL', bridge: 'CASTLE', difficulty: 'hard' },
  { id: 'en-h-048', word1: 'SCYTHE', word2: 'BLADE', bridge: 'REAPER', difficulty: 'hard', hint: 'Also known as the grim...' },
  { id: 'en-h-049', word1: 'TIDAL', word2: 'POOL', bridge: 'WAVE', difficulty: 'hard' },
  { id: 'en-h-050', word1: 'ULTERIOR', word2: 'MOTIVE', bridge: 'HIDDEN', difficulty: 'hard', hint: 'Both mean concealed purpose' },
  { id: 'en-h-051', word1: 'VERMIN', word2: 'PEST', bridge: 'RAT', difficulty: 'hard' },
  { id: 'en-h-052', word1: 'WAKE', word2: 'FUNERAL', bridge: 'VIGIL', difficulty: 'hard' },
  { id: 'en-h-053', word1: 'YOKE', word2: 'EGG', bridge: 'YOLK', difficulty: 'hard', hint: 'Sounds the same, means different things' },
  { id: 'en-h-054', word1: 'ZINC', word2: 'IRON', bridge: 'METAL', difficulty: 'hard' },
];
