import type { ConnectionPuzzle } from '../types';

export const EN_HARD: ConnectionPuzzle[] = [
  { id: 'en-h-001', word1: 'CHEST', word2: 'PLAY', bridge: 'FAIR', difficulty: 'hard', hint: 'Also a festival context' },
  { id: 'en-h-002', word1: 'CORN', word2: 'STONE', bridge: 'COBBLE', difficulty: 'hard', hint: 'Old street material' },
  { id: 'en-h-003', word1: 'HORSE', word2: 'BRIDGE', bridge: 'DRAW', difficulty: 'hard' },
  { id: 'en-h-004', word1: 'ROUGH', word2: 'HOUSE', bridge: 'SHOD', difficulty: 'hard' },
  { id: 'en-h-005', word1: 'BACK', word2: 'WARDS', bridge: 'STROKES', difficulty: 'hard' },
  { id: 'en-h-006', word1: 'FLAG', word2: 'STOP', bridge: 'SHIP', difficulty: 'hard' },
  { id: 'en-h-007', word1: 'CLOUD', word2: 'BURST', bridge: 'NINE', difficulty: 'hard' },
  { id: 'en-h-008', word1: 'DOUBLE', word2: 'TAKE', bridge: 'CROSS', difficulty: 'hard' },
  { id: 'en-h-009', word1: 'ELOPE', word2: 'MENT', bridge: 'ENGAGE', difficulty: 'hard' },
  { id: 'en-h-010', word1: 'FLAT', word2: 'OUT', bridge: 'SPIN', difficulty: 'hard', hint: 'A gymnastic move' },
  { id: 'en-h-011', word1: 'GRAVE', word2: 'SHIFT', bridge: 'YARD', difficulty: 'hard' },
  { id: 'en-h-012', word1: 'HOLLOW', word2: 'WEEN', bridge: 'HALL', difficulty: 'hard' },
  { id: 'en-h-013', word1: 'INTRO', word2: 'SPECT', bridge: 'VERT', difficulty: 'hard' },
  { id: 'en-h-014', word1: 'JAW', word2: 'LINE', bridge: 'DROP', difficulty: 'hard' },
  { id: 'en-h-015', word1: 'KNAP', word2: 'SACK', bridge: 'HAVERSACK', difficulty: 'hard', hint: 'Starts with H too' },
  { id: 'en-h-016', word1: 'LEAN', word2: 'TO', bridge: 'OVER', difficulty: 'hard' },
  { id: 'en-h-017', word1: 'MEANDER', word2: 'ING', bridge: 'WANDER', difficulty: 'hard' },
  { id: 'en-h-018', word1: 'NERVE', word2: 'WRACKING', bridge: 'RACK', difficulty: 'hard' },
  { id: 'en-h-019', word1: 'OAK', word2: 'BARREL', bridge: 'EN', difficulty: 'hard' },
  { id: 'en-h-020', word1: 'PORE', word2: 'OVER', bridge: 'BONE', difficulty: 'hard' },
  { id: 'en-h-021', word1: 'RABBIT', word2: 'WARREN', bridge: 'HOLE', difficulty: 'hard' },
  { id: 'en-h-022', word1: 'SKULL', word2: 'BONE', bridge: 'CROSS', difficulty: 'hard' },
  { id: 'en-h-023', word1: 'TONGUE', word2: 'CHEEK', bridge: 'IN', difficulty: 'hard' },
  { id: 'en-h-024', word1: 'UNDER', word2: 'BELLY', bridge: 'UNDER', difficulty: 'hard', hint: 'Literally under-under' },
  { id: 'en-h-025', word1: 'VEIL', word2: 'LIFTING', bridge: 'BRIDAL', difficulty: 'hard' },
  { id: 'en-h-026', word1: 'WARP', word2: 'DRIVE', bridge: 'SPEED', difficulty: 'hard' },
  { id: 'en-h-027', word1: 'XENON', word2: 'LAMP', bridge: 'ARC', difficulty: 'hard' },
  { id: 'en-h-028', word1: 'YIELD', word2: 'SIGN', bridge: 'ROAD', difficulty: 'hard' },
  { id: 'en-h-029', word1: 'ZENITH', word2: 'SKY', bridge: 'NADIR', difficulty: 'hard', hint: 'Opposite of zenith' },
  { id: 'en-h-030', word1: 'ANVIL', word2: 'HEAD', bridge: 'CLOUD', difficulty: 'hard' },
  { id: 'en-h-031', word1: 'BLEAK', word2: 'HOUSE', bridge: 'GRIM', difficulty: 'hard' },
  { id: 'en-h-032', word1: 'CLENCH', word2: 'FIST', bridge: 'IRON', difficulty: 'hard' },
  { id: 'en-h-033', word1: 'DUNCE', word2: 'CAP', bridge: 'NIGHT', difficulty: 'hard' },
  { id: 'en-h-034', word1: 'ELDER', word2: 'BERRY', bridge: 'STRAW', difficulty: 'hard' },
  { id: 'en-h-035', word1: 'FEATHER', word2: 'WEIGHT', bridge: 'LIGHT', difficulty: 'hard' },
  { id: 'en-h-036', word1: 'GHOST', word2: 'WRITER', bridge: 'COPY', difficulty: 'hard' },
  { id: 'en-h-037', word1: 'HAMLET', word2: 'VILLAGE', bridge: 'SMALL', difficulty: 'hard', hint: 'Shakespeare or small settlement?' },
  { id: 'en-h-038', word1: 'IVORY', word2: 'TOWER', bridge: 'TUSK', difficulty: 'hard' },
  { id: 'en-h-039', word1: 'JINX', word2: 'HEX', bridge: 'CURSE', difficulty: 'hard', hint: 'All three mean the same thing' },
  { id: 'en-h-040', word1: 'KERNEL', word2: 'TRUTH', bridge: 'CORN', difficulty: 'hard' },
  { id: 'en-h-041', word1: 'LIMELIGHT', word2: 'STAGE', bridge: 'LIME', difficulty: 'hard' },
  { id: 'en-h-042', word1: 'MAST', word2: 'CELL', bridge: 'MAST', difficulty: 'hard', hint: 'Biology meets sailing' },
  { id: 'en-h-043', word1: 'NICHE', word2: 'MARKET', bridge: 'ALCOVE', difficulty: 'hard' },
  { id: 'en-h-044', word1: 'OMEN', word2: 'SIGN', bridge: 'PORTENT', difficulty: 'hard', hint: 'Also a creepy film' },
  { id: 'en-h-045', word1: 'PRISM', word2: 'LIGHT', bridge: 'SPLIT', difficulty: 'hard' },
  { id: 'en-h-046', word1: 'QUIVER', word2: 'ARROW', bridge: 'BOW', difficulty: 'hard' },
  { id: 'en-h-047', word1: 'RAMPART', word2: 'WALL', bridge: 'CASTLE', difficulty: 'hard' },
  { id: 'en-h-048', word1: 'SCYTHE', word2: 'BLADE', bridge: 'REAPER', difficulty: 'hard', hint: 'Also known as the grim...' },
  { id: 'en-h-049', word1: 'TIDAL', word2: 'POOL', bridge: 'WAVE', difficulty: 'hard' },
  { id: 'en-h-050', word1: 'ULTERIOR', word2: 'MOTIVE', bridge: 'HIDDEN', difficulty: 'hard', hint: 'Both mean concealed purpose' },
  { id: 'en-h-051', word1: 'VERMIN', word2: 'PEST', bridge: 'RAT', difficulty: 'hard' },
  { id: 'en-h-052', word1: 'WAKE', word2: 'FUNERAL', bridge: 'VIGIL', difficulty: 'hard' },
  { id: 'en-h-053', word1: 'YOKE', word2: 'EGG', bridge: 'YOLK', difficulty: 'hard', hint: 'Sounds the same, means different things' },
  { id: 'en-h-054', word1: 'ZINC', word2: 'IRON', bridge: 'METAL', difficulty: 'hard' },
  { id: 'en-h-055', word1: 'ABYSS', word2: 'DEEP', bridge: 'CHASM', difficulty: 'hard' },
  { id: 'en-h-056', word1: 'BRINE', word2: 'SEA', bridge: 'SALT', difficulty: 'hard' },
  { id: 'en-h-057', word1: 'CIPHER', word2: 'CODE', bridge: 'ZERO', difficulty: 'hard', hint: 'Also means the number 0' },
  { id: 'en-h-058', word1: 'DUSK', word2: 'TWILIGHT', bridge: 'GLOAMING', difficulty: 'hard', hint: 'Old word for evening' },
  { id: 'en-h-059', word1: 'ENNUI', word2: 'BOREDOM', bridge: 'TEDIUM', difficulty: 'hard' },
  { id: 'en-h-060', word1: 'FOIBLE', word2: 'FLAW', bridge: 'QUIRK', difficulty: 'hard' },
  { id: 'en-h-061', word1: 'GAMBIT', word2: 'CHESS', bridge: 'PAWN', difficulty: 'hard' },
  { id: 'en-h-062', word1: 'HEARTH', word2: 'FIRE', bridge: 'HOME', difficulty: 'hard' },
  { id: 'en-h-063', word1: 'INERT', word2: 'GAS', bridge: 'NOBLE', difficulty: 'hard' },
  { id: 'en-h-064', word1: 'JOUST', word2: 'KNIGHT', bridge: 'LANCE', difficulty: 'hard' },
  { id: 'en-h-065', word1: 'KEEL', word2: 'BOAT', bridge: 'HULL', difficulty: 'hard' },
  { id: 'en-h-066', word1: 'LEVEE', word2: 'FLOOD', bridge: 'BANK', difficulty: 'hard' },
  { id: 'en-h-067', word1: 'MIRTH', word2: 'JOY', bridge: 'GLEE', difficulty: 'hard' },
  { id: 'en-h-068', word1: 'NADIR', word2: 'LOW', bridge: 'BOTTOM', difficulty: 'hard' },
  { id: 'en-h-069', word1: 'ORB', word2: 'SPHERE', bridge: 'GLOBE', difficulty: 'hard' },
  { id: 'en-h-070', word1: 'PYRE', word2: 'FIRE', bridge: 'FUNERAL', difficulty: 'hard' },
  { id: 'en-h-071', word1: 'QUAFF', word2: 'DRINK', bridge: 'DRAFT', difficulty: 'hard' },
  { id: 'en-h-072', word1: 'RIFT', word2: 'VALLEY', bridge: 'SPLIT', difficulty: 'hard' },
  { id: 'en-h-073', word1: 'SANCTUM', word2: 'ROOM', bridge: 'INNER', difficulty: 'hard' },
  { id: 'en-h-074', word1: 'TOME', word2: 'BOOK', bridge: 'VOLUME', difficulty: 'hard' },
  { id: 'en-h-075', word1: 'URN', word2: 'ASHES', bridge: 'VASE', difficulty: 'hard' },
  { id: 'en-h-076', word1: 'VERDANT', word2: 'GREEN', bridge: 'LUSH', difficulty: 'hard' },
  { id: 'en-h-077', word1: 'WRATH', word2: 'ANGER', bridge: 'FURY', difficulty: 'hard' },
  { id: 'en-h-078', word1: 'YORE', word2: 'PAST', bridge: 'DAYS', difficulty: 'hard', hint: 'Days of...' },
  { id: 'en-h-079', word1: 'ZEAL', word2: 'PASSION', bridge: 'FERVOR', difficulty: 'hard' },
  { id: 'en-h-080', word1: 'APEX', word2: 'TOP', bridge: 'PEAK', difficulty: 'hard' },
  { id: 'en-h-081', word1: 'CANDID', word2: 'FRANK', bridge: 'SINCERE', difficulty: 'hard' },
  { id: 'en-h-082', word1: 'MEANDER', word2: 'RAMBLE', bridge: 'WANDER', difficulty: 'hard' },
  { id: 'en-h-083', word1: 'PLACID', word2: 'TRANQUIL', bridge: 'SERENE', difficulty: 'hard' },
  { id: 'en-h-084', word1: 'EPHEMERAL', word2: 'TRANSIENT', bridge: 'FLEETING', difficulty: 'hard' },
  { id: 'en-h-085', word1: 'ENIGMATIC', word2: 'MYSTERIOUS', bridge: 'CRYPTIC', difficulty: 'hard' },
  { id: 'en-h-086', word1: 'MELANCHOLY', word2: 'GLOOMY', bridge: 'SOMBER', difficulty: 'hard' },
  { id: 'en-h-087', word1: 'TENACIOUS', word2: 'STEADFAST', bridge: 'RESOLUTE', difficulty: 'hard' },
  { id: 'en-h-088', word1: 'ANTIQUATED', word2: 'OBSOLETE', bridge: 'ARCHAIC', difficulty: 'hard' },
  { id: 'en-h-089', word1: 'LACONIC', word2: 'CONCISE', bridge: 'TERSE', difficulty: 'hard' },
  { id: 'en-h-090', word1: 'TACITURN', word2: 'RESERVED', bridge: 'RETICENT', difficulty: 'hard' },
  { id: 'en-h-091', word1: 'AMIABLE', word2: 'GENIAL', bridge: 'AFFABLE', difficulty: 'hard' },
  { id: 'en-h-092', word1: 'BAFFLE', word2: 'BEWILDER', bridge: 'PERPLEX', difficulty: 'hard' },
  { id: 'en-h-093', word1: 'CALAMITY', word2: 'DISASTER', bridge: 'CATASTROPHE', difficulty: 'hard' },
  { id: 'en-h-094', word1: 'DAUNTLESS', word2: 'VALIANT', bridge: 'INTREPID', difficulty: 'hard' },
  { id: 'en-h-095', word1: 'ERUDITE', word2: 'LEARNED', bridge: 'SCHOLARLY', difficulty: 'hard' },
  { id: 'en-h-096', word1: 'GAUNT', word2: 'HAGGARD', bridge: 'EMACIATED', difficulty: 'hard' },
  { id: 'en-h-097', word1: 'JOCULAR', word2: 'MERRY', bridge: 'JOVIAL', difficulty: 'hard' },
  { id: 'en-h-098', word1: 'MAGNANIMOUS', word2: 'GENEROUS', bridge: 'BENEVOLENT', difficulty: 'hard' },
  { id: 'en-h-099', word1: 'RANCOR', word2: 'RESENTMENT', bridge: 'BITTERNESS', difficulty: 'hard' },
  { id: 'en-h-100', word1: 'ZENITH', word2: 'PINNACLE', bridge: 'APEX', difficulty: 'hard' },
  { id: 'en-h-101', word1: 'VERBOSE', word2: 'LOQUACIOUS', bridge: 'WORDY', difficulty: 'hard' },
  { id: 'en-h-102', word1: 'AFFLUENT', word2: 'WEALTHY', bridge: 'PROSPEROUS', difficulty: 'hard' },
  { id: 'en-h-103', word1: 'SURREPTITIOUS', word2: 'CLANDESTINE', bridge: 'COVERT', difficulty: 'hard' },
  { id: 'en-h-104', word1: 'UBIQUITOUS', word2: 'PERVASIVE', bridge: 'OMNIPRESENT', difficulty: 'hard' },
  { id: 'en-h-105', word1: 'ALACRITY', word2: 'ZEAL', bridge: 'EAGERNESS', difficulty: 'hard' },
  { id: 'en-h-106', word1: 'ACRIMONIOUS', word2: 'VITRIOLIC', bridge: 'CAUSTIC', difficulty: 'hard' },
  { id: 'en-h-107', word1: 'PERSPICACIOUS', word2: 'SHREWD', bridge: 'ASTUTE', difficulty: 'hard' },
  { id: 'en-h-108', word1: 'SOMNOLENT', word2: 'LETHARGIC', bridge: 'DROWSY', difficulty: 'hard' },
  { id: 'en-h-109', word1: 'OBSTINATE', word2: 'INTRANSIGENT', bridge: 'STUBBORN', difficulty: 'hard' },
  { id: 'en-h-110', word1: 'FRACAS', word2: 'MELEE', bridge: 'BRAWL', difficulty: 'hard' },
  { id: 'en-h-111', word1: 'IMPECUNIOUS', word2: 'INDIGENT', bridge: 'DESTITUTE', difficulty: 'hard' },
  { id: 'en-h-112', word1: 'SPURIOUS', word2: 'FRAUDULENT', bridge: 'COUNTERFEIT', difficulty: 'hard' },
  { id: 'en-h-113', word1: 'VEXATION', word2: 'ANNOYANCE', bridge: 'IRRITATION', difficulty: 'hard' },
  { id: 'en-h-114', word1: 'BELLIGERENT', word2: 'HOSTILE', bridge: 'PUGNACIOUS', difficulty: 'hard' },
  { id: 'en-h-115', word1: 'WARY', word2: 'GUARDED', bridge: 'CAUTIOUS', difficulty: 'hard' },
  { id: 'en-h-116', word1: 'HAPLESS', word2: 'LUCKLESS', bridge: 'UNFORTUNATE', difficulty: 'hard' },
  { id: 'en-h-117', word1: 'INCLEMENT', word2: 'SEVERE', bridge: 'HARSH', difficulty: 'hard' },
  { id: 'en-h-118', word1: 'PEDANTIC', word2: 'BOOKISH', bridge: 'ACADEMIC', difficulty: 'hard' },
  { id: 'en-h-119', word1: 'SOLEMN', word2: 'EARNEST', bridge: 'GRAVE', difficulty: 'hard' },
  { id: 'en-h-120', word1: 'FURTIVE', word2: 'SNEAKY', bridge: 'STEALTHY', difficulty: 'hard' },
];
