import type { ConnectionPuzzle } from '../types';

// Hebrew Word Chain puzzles
// Mechanic: WORD1 + BRIDGE → valid phrase, BRIDGE + WORD2 → valid phrase
// Example: בית + תורה → BRIDGE=ספר (בית ספר = school, ספר תורה = Torah scroll)

export const HE_EASY: ConnectionPuzzle[] = [
  { id: 'he-e-001', word1: 'בית', word2: 'תורה', bridge: 'ספר', difficulty: 'easy', hint: 'בית _________ ו_______ תורה' },
  { id: 'he-e-002', word1: 'כדור', word2: 'מים', bridge: 'רגל', difficulty: 'easy' },
  { id: 'he-e-003', word1: 'מים', word2: 'חיים', bridge: 'שפת', difficulty: 'easy' },
  { id: 'he-e-004', word1: 'יד', word2: 'חשמל', bridge: 'עבודת', difficulty: 'easy' },
  { id: 'he-e-005', word1: 'כוס', word2: 'לשלום', bridge: 'תה', difficulty: 'easy', hint: 'שתייה חמה' },
  { id: 'he-e-006', word1: 'אדמה', word2: 'כוח', bridge: 'כבידת', difficulty: 'easy' },
  { id: 'he-e-007', word1: 'דרך', word2: 'ברזל', bridge: 'מסילת', difficulty: 'easy' },
  { id: 'he-e-008', word1: 'שמש', word2: 'זריחה', bridge: 'שקיעת', difficulty: 'easy' },
  { id: 'he-e-009', word1: 'לב', word2: 'אחים', bridge: 'אחוות', difficulty: 'easy' },
  { id: 'he-e-010', word1: 'זמן', word2: 'חינם', bridge: 'פנאי', difficulty: 'easy' },
  { id: 'he-e-011', word1: 'קול', word2: 'דממה', bridge: 'דקה', difficulty: 'easy' },
  { id: 'he-e-012', word1: 'אש', word2: 'שלהבת', bridge: 'לבת', difficulty: 'easy' },
  { id: 'he-e-013', word1: 'ים', word2: 'עבר', bridge: 'התיכון', difficulty: 'easy' },
  { id: 'he-e-014', word1: 'יום', word2: 'חופש', bridge: 'הולדת', difficulty: 'easy' },
  { id: 'he-e-015', word1: 'ראש', word2: 'פינה', bridge: 'אבן', difficulty: 'easy' },
  { id: 'he-e-016', word1: 'שיר', word2: 'הלל', bridge: 'שבח', difficulty: 'easy' },
  { id: 'he-e-017', word1: 'עץ', word2: 'שדה', bridge: 'תפוח', difficulty: 'easy', hint: 'פרי' },
  { id: 'he-e-018', word1: 'חלון', word2: 'הזדמנות', bridge: 'ראווה', difficulty: 'easy' },
  { id: 'he-e-019', word1: 'כלב', word2: 'ים', bridge: 'כלב', difficulty: 'easy', hint: 'חיה ימית' },
  { id: 'he-e-020', word1: 'ילד', word2: 'רמז', bridge: 'פלא', difficulty: 'easy' },
  { id: 'he-e-021', word1: 'ענן', word2: 'מטר', bridge: 'גשם', difficulty: 'easy' },
  { id: 'he-e-022', word1: 'גבר', word2: 'כוח', bridge: 'אגרוף', difficulty: 'easy' },
  { id: 'he-e-023', word1: 'שם', word2: 'נדיר', bridge: 'טוב', difficulty: 'easy' },
  { id: 'he-e-024', word1: 'אור', word2: 'ירח', bridge: 'ירח', difficulty: 'easy' },
  { id: 'he-e-025', word1: 'אוהל', word2: 'מועד', bridge: 'אוהל', difficulty: 'easy', hint: 'גם שם מקום קדוש' },
  { id: 'he-e-026', word1: 'מלך', word2: 'מלאכים', bridge: 'מל', difficulty: 'easy' },
  { id: 'he-e-027', word1: 'דם', word2: 'ירידה', bridge: 'לחץ', difficulty: 'easy' },
  { id: 'he-e-028', word1: 'שחר', word2: 'ערב', bridge: 'ובין', difficulty: 'easy' },
  { id: 'he-e-029', word1: 'חוף', word2: 'חמד', bridge: 'ים', difficulty: 'easy' },
  { id: 'he-e-030', word1: 'כיכר', word2: 'שקל', bridge: 'לחם', difficulty: 'easy' },
  { id: 'he-e-031', word1: 'גן', word2: 'ילדים', bridge: 'עדן', difficulty: 'easy' },
  { id: 'he-e-032', word1: 'בקר', word2: 'ערב', bridge: 'טוב', difficulty: 'easy' },
  { id: 'he-e-033', word1: 'מזון', word2: 'בריאות', bridge: 'מהיר', difficulty: 'easy' },
  { id: 'he-e-034', word1: 'כבש', word2: 'הרים', bridge: 'פסח', difficulty: 'easy' },
  { id: 'he-e-035', word1: 'שמן', word2: 'צמח', bridge: 'זית', difficulty: 'easy' },
  { id: 'he-e-036', word1: 'חרב', word2: 'ברזל', bridge: 'פי', difficulty: 'easy', hint: 'קצה כלי לחימה' },
  { id: 'he-e-037', word1: 'עולם', word2: 'בא', bridge: 'הזה', difficulty: 'easy' },
  { id: 'he-e-038', word1: 'מחשב', word2: 'נייד', bridge: 'שולחן', difficulty: 'easy' },
  { id: 'he-e-039', word1: 'ספר', word2: 'ילדים', bridge: 'סיפורי', difficulty: 'easy' },
  { id: 'he-e-040', word1: 'קיר', word2: 'ברלין', bridge: 'ביצור', difficulty: 'easy' },
  { id: 'he-e-041', word1: 'מכונית', word2: 'מרוץ', bridge: 'ספורט', difficulty: 'easy' },
  { id: 'he-e-042', word1: 'נחש', word2: 'גן', bridge: 'עדן', difficulty: 'easy' },
  { id: 'he-e-043', word1: 'חתול', word2: 'מים', bridge: 'שחייה', difficulty: 'easy' },
  { id: 'he-e-044', word1: 'דגל', word2: 'לאום', bridge: 'מדינת', difficulty: 'easy' },
  { id: 'he-e-045', word1: 'כסף', word2: 'זהב', bridge: 'כסף', difficulty: 'easy', hint: 'כלי חרס מצופה' },
  { id: 'he-e-046', word1: 'אחד', word2: 'אחד', bridge: 'אחד', difficulty: 'easy', hint: 'מספר ראשוני' },
  { id: 'he-e-047', word1: 'חלב', word2: 'דבש', bridge: 'וארץ', difficulty: 'easy' },
  { id: 'he-e-048', word1: 'פרח', word2: 'אביב', bridge: 'עונת', difficulty: 'easy' },
  { id: 'he-e-049', word1: 'שקט', word2: 'לב', bridge: 'שלווה', difficulty: 'easy' },
  { id: 'he-e-050', word1: 'בגד', word2: 'עבודה', bridge: 'אחיד', difficulty: 'easy' },
  { id: 'he-e-051', word1: 'חם', word2: 'חורף', bridge: 'יום', difficulty: 'easy' },
  { id: 'he-e-052', word1: 'ציפור', word2: 'דרור', bridge: 'שיר', difficulty: 'easy' },
  { id: 'he-e-053', word1: 'דלת', word2: 'סגורה', bridge: 'פתח', difficulty: 'easy' },
  { id: 'he-e-054', word1: 'בלון', word2: 'ניסוי', bridge: 'גבוה', difficulty: 'easy', hint: 'עף באוויר' },
  { id: 'he-e-055', word1: 'ממשלה', word2: 'ארץ', bridge: 'ישראל', difficulty: 'easy' },
  { id: 'he-e-056', word1: 'ראייה', word2: 'חזות', bridge: 'שדה', difficulty: 'easy' },
  { id: 'he-e-057', word1: 'מדע', word2: 'פיקציה', bridge: 'בדיוני', difficulty: 'easy' },
  { id: 'he-e-058', word1: 'כדור', word2: 'ארץ', bridge: 'גלובוס', difficulty: 'easy' },
  { id: 'he-e-059', word1: 'בוקר', word2: 'עבר', bridge: 'טוב', difficulty: 'easy' },
  { id: 'he-e-060', word1: 'תרנגול', word2: 'בוקר', bridge: 'קריאת', difficulty: 'easy' },
  { id: 'he-e-061', word1: 'שחור', word2: 'שמיים', bridge: 'לבן', difficulty: 'easy' },
  { id: 'he-e-062', word1: 'עוף', word2: 'שמיים', bridge: 'שיר', difficulty: 'easy' },
  { id: 'he-e-063', word1: 'דף', word2: 'היסטוריה', bridge: 'זהב', difficulty: 'easy' },
  { id: 'he-e-064', word1: 'אחרית', word2: 'שנה', bridge: 'דבר', difficulty: 'easy' },
  { id: 'he-e-065', word1: 'מלאך', word2: 'מוות', bridge: 'שלום', difficulty: 'easy' },
  { id: 'he-e-066', word1: 'מנוחה', word2: 'שפה', bridge: 'שבת', difficulty: 'easy' },
  { id: 'he-e-067', word1: 'סוף', word2: 'עולם', bridge: 'קצה', difficulty: 'easy' },
  { id: 'he-e-068', word1: 'פנים', word2: 'פנים', bridge: 'אל', difficulty: 'easy', hint: 'מפגש ישיר' },
  { id: 'he-e-069', word1: 'חיים', word2: 'מוות', bridge: 'בין', difficulty: 'easy' },
  { id: 'he-e-070', word1: 'אור', word2: 'אופל', bridge: 'חושך', difficulty: 'easy' },
  { id: 'he-e-071', word1: 'ים', word2: 'מדבר', bridge: 'סוף', difficulty: 'easy' },
  { id: 'he-e-072', word1: 'ברית', word2: 'מילה', bridge: 'מילה', difficulty: 'easy' },
  { id: 'he-e-073', word1: 'מלחמה', word2: 'שלום', bridge: 'קריאה', difficulty: 'easy' },
  { id: 'he-e-074', word1: 'זכרון', word2: 'עם', bridge: 'לדור', difficulty: 'easy' },
  { id: 'he-e-075', word1: 'חלום', word2: 'לילה', bridge: 'חלום', difficulty: 'easy', hint: 'חזרה על אותה מילה' },
  { id: 'he-e-076', word1: 'פה', word2: 'לב', bridge: 'מן', difficulty: 'easy', hint: 'גם שם מקום: על' },
  { id: 'he-e-077', word1: 'ידיים', word2: 'רגליים', bridge: 'שתי', difficulty: 'easy' },
  { id: 'he-e-078', word1: 'חרוז', word2: 'שיר', bridge: 'פסוק', difficulty: 'easy' },
  { id: 'he-e-079', word1: 'ענב', word2: 'יין', bridge: 'גפן', difficulty: 'easy' },
  { id: 'he-e-080', word1: 'בנאי', word2: 'קיר', bridge: 'חרוב', difficulty: 'easy' },
  { id: 'he-e-081', word1: 'שביל', word2: 'לכת', bridge: 'ארחות', difficulty: 'easy' },
  { id: 'he-e-082', word1: 'אוויר', word2: 'טרי', bridge: 'נשימה', difficulty: 'easy' },
  { id: 'he-e-083', word1: 'לשון', word2: 'הרע', bridge: 'חרב', difficulty: 'easy' },
  { id: 'he-e-084', word1: 'עצמות', word2: 'חיים', bridge: 'גוף', difficulty: 'easy' },
  { id: 'he-e-085', word1: 'שפה', word2: 'גלים', bridge: 'שפת', difficulty: 'easy' },
];
