import type { ConnectionPuzzle } from '../types';

export const HE_HARD: ConnectionPuzzle[] = [
  { id: 'he-h-001', word1: 'דרדק', word2: 'ניסיון', bridge: 'ערכת', difficulty: 'hard', hint: 'ניסוי ראשון' },
  { id: 'he-h-002', word1: 'שיא', word2: 'לעולם', bridge: 'נצח', difficulty: 'hard' },
  { id: 'he-h-003', word1: 'ריח', word2: 'עשב', bridge: 'ניחוח', difficulty: 'hard' },
  { id: 'he-h-004', word1: 'זרם', word2: 'ידע', bridge: 'מידע', difficulty: 'hard' },
  { id: 'he-h-005', word1: 'מעבר', word2: 'זמן', bridge: 'עבר', difficulty: 'hard' },
  { id: 'he-h-006', word1: 'רוח', word2: 'יצירה', bridge: 'השראת', difficulty: 'hard' },
  { id: 'he-h-007', word1: 'חיסון', word2: 'מחלה', bridge: 'מניעת', difficulty: 'hard' },
  { id: 'he-h-008', word1: 'שוק', word2: 'מניות', bridge: 'ביורסה', difficulty: 'hard', hint: 'שוק ההון' },
  { id: 'he-h-009', word1: 'כח', word2: 'דעת', bridge: 'דעת', difficulty: 'hard' },
  { id: 'he-h-010', word1: 'שוקת', word2: 'מרעה', bridge: 'מים', difficulty: 'hard' },
  { id: 'he-h-011', word1: 'שקר', word2: 'שקר', bridge: 'שקר אחרי', difficulty: 'hard', hint: 'כפל שקר' },
  { id: 'he-h-012', word1: 'מוח', word2: 'גזע', bridge: 'קליפת', difficulty: 'hard' },
  { id: 'he-h-013', word1: 'תקנות', word2: 'חברה', bridge: 'תקנון', difficulty: 'hard' },
  { id: 'he-h-014', word1: 'טרנספורמציה', word2: 'שינוי', bridge: 'מהפכת', difficulty: 'hard' },
  { id: 'he-h-015', word1: 'מנגנון', word2: 'מכונה', bridge: 'שיניים', difficulty: 'hard', hint: 'גלגלי...' },
  { id: 'he-h-016', word1: 'שיטה', word2: 'הוראה', bridge: 'פדגוגית', difficulty: 'hard' },
  { id: 'he-h-017', word1: 'ערבות', word2: 'הדדית', bridge: 'ערבות', difficulty: 'hard' },
  { id: 'he-h-018', word1: 'מרקם', word2: 'עיר', bridge: 'חברתי', difficulty: 'hard' },
  { id: 'he-h-019', word1: 'ממד', word2: 'רביעי', bridge: 'זמן', difficulty: 'hard' },
  { id: 'he-h-020', word1: 'גרעין', word2: 'תא', bridge: 'ציר', difficulty: 'hard' },
  { id: 'he-h-021', word1: 'תפיסה', word2: 'אור', bridge: 'חוש', difficulty: 'hard' },
  { id: 'he-h-022', word1: 'דיאלוג', word2: 'תיאטרון', bridge: 'סוקרטי', difficulty: 'hard' },
  { id: 'he-h-023', word1: 'פרדוקס', word2: 'הגיון', bridge: 'צב', difficulty: 'hard', hint: 'של אכילס' },
  { id: 'he-h-024', word1: 'אנטרופיה', word2: 'מערכת', bridge: 'כאוס', difficulty: 'hard' },
  { id: 'he-h-025', word1: 'אמפתיה', word2: 'הבנה', bridge: 'רגשית', difficulty: 'hard' },
  { id: 'he-h-026', word1: 'קוגניציה', word2: 'ידע', bridge: 'עיבוד', difficulty: 'hard' },
  { id: 'he-h-027', word1: 'נרטיב', word2: 'זהות', bridge: 'אישי', difficulty: 'hard' },
  { id: 'he-h-028', word1: 'תת', word2: 'מודע', bridge: 'תת-מודע', difficulty: 'hard', hint: 'פרויד' },
  { id: 'he-h-029', word1: 'הרמנויטיקה', word2: 'טקסט', bridge: 'פרשנות', difficulty: 'hard' },
  { id: 'he-h-030', word1: 'פנומנולוגיה', word2: 'הכרה', bridge: 'חוויה', difficulty: 'hard' },
  { id: 'he-h-031', word1: 'ספסופיסט', word2: 'ויכוח', bridge: 'פלפול', difficulty: 'hard', hint: 'ויכוח לשמו' },
  { id: 'he-h-032', word1: 'קינסטתזיה', word2: 'תנועה', bridge: 'תחושת', difficulty: 'hard' },
  { id: 'he-h-033', word1: 'תזה', word2: 'מחקר', bridge: 'הוכחת', difficulty: 'hard' },
  { id: 'he-h-034', word1: 'ניתוח', word2: 'מבנה', bridge: 'שכבות', difficulty: 'hard' },
  { id: 'he-h-035', word1: 'גשר', word2: 'תקשורת', bridge: 'בין', difficulty: 'hard' },
  { id: 'he-h-036', word1: 'אלגוריתם', word2: 'פתרון', bridge: 'חישוב', difficulty: 'hard' },
  { id: 'he-h-037', word1: 'נבואה', word2: 'אירוע', bridge: 'המגשימה', difficulty: 'hard', hint: 'נבואה ש...' },
  { id: 'he-h-038', word1: 'ריבונות', word2: 'מדינה', bridge: 'לאומית', difficulty: 'hard' },
  { id: 'he-h-039', word1: 'תדמית', word2: 'ציבור', bridge: 'יחסי', difficulty: 'hard' },
  { id: 'he-h-040', word1: 'קצב', word2: 'שינוי', bridge: 'האצת', difficulty: 'hard' },
  { id: 'he-h-041', word1: 'ממשק', word2: 'משתמש', bridge: 'חוויית', difficulty: 'hard' },
  { id: 'he-h-042', word1: 'אבולוציה', word2: 'מין', bridge: 'ברירת', difficulty: 'hard' },
  { id: 'he-h-043', word1: 'דואליות', word2: 'טבע', bridge: 'גוף-נשמה', difficulty: 'hard' },
  { id: 'he-h-044', word1: 'שיוויון', word2: 'הזדמנויות', bridge: 'צדק', difficulty: 'hard' },
  { id: 'he-h-045', word1: 'גלובליזציה', word2: 'שוק', bridge: 'כלכלת', difficulty: 'hard' },
  { id: 'he-h-046', word1: 'מודל', word2: 'התנהגות', bridge: 'פסיכולוגי', difficulty: 'hard' },
  { id: 'he-h-047', word1: 'טריגר', word2: 'תגובה', bridge: 'גירוי', difficulty: 'hard' },
  { id: 'he-h-048', word1: 'הסתגלות', word2: 'שינוי', bridge: 'יכולת', difficulty: 'hard' },
  { id: 'he-h-049', word1: 'ביצוע', word2: 'מיטבי', bridge: 'שיא', difficulty: 'hard' },
  { id: 'he-h-050', word1: 'אינטגרציה', word2: 'מערכות', bridge: 'שילוב', difficulty: 'hard' },
  { id: 'he-h-051', word1: 'הפשטה', word2: 'קוד', bridge: 'שכבת', difficulty: 'hard' },
  { id: 'he-h-052', word1: 'קשר', word2: 'תקשורת', bridge: 'פרוטוקול', difficulty: 'hard' },
  { id: 'he-h-053', word1: 'זכות', word2: 'דין', bridge: 'טיעון', difficulty: 'hard' },
  { id: 'he-h-054', word1: 'תמריץ', word2: 'פעולה', bridge: 'מניע', difficulty: 'hard' },
  { id: 'he-h-055', word1: 'מדיניות', word2: 'עניין', bridge: 'ציבורי', difficulty: 'hard' },
  { id: 'he-h-056', word1: 'ממשל', word2: 'בינה', bridge: 'ורגולציה', difficulty: 'hard' },
  { id: 'he-h-057', word1: 'מגמה', word2: 'שוק', bridge: 'עסקית', difficulty: 'hard' },
  { id: 'he-h-058', word1: 'זיכרון', word2: 'קהילה', bridge: 'קולקטיבי', difficulty: 'hard' },
  { id: 'he-h-059', word1: 'כוח', word2: 'מדינה', bridge: 'רך', difficulty: 'hard' },
  { id: 'he-h-060', word1: 'פרדיגמה', word2: 'מחשבה', bridge: 'מסגרת', difficulty: 'hard' },
  { id: 'he-h-061', word1: 'מינוף', word2: 'מקורות', bridge: 'כלכלי', difficulty: 'hard' },
  { id: 'he-h-062', word1: 'שיח', word2: 'כוח', bridge: 'יחסי', difficulty: 'hard' },
  { id: 'he-h-063', word1: 'חלוקה', word2: 'תפקידים', bridge: 'עבודת', difficulty: 'hard' },
  { id: 'he-h-064', word1: 'לקוח', word2: 'מטרה', bridge: 'קהל', difficulty: 'hard' },
  { id: 'he-h-065', word1: 'אסטרטגיה', word2: 'יתרון', bridge: 'תחרותי', difficulty: 'hard' },
  { id: 'he-h-066', word1: 'גבולות', word2: 'מרחב', bridge: 'קביעת', difficulty: 'hard' },
  { id: 'he-h-067', word1: 'נכסים', word2: 'ניהול', bridge: 'כספיים', difficulty: 'hard' },
  { id: 'he-h-068', word1: 'הנחות', word2: 'מודל', bridge: 'בסיס', difficulty: 'hard' },
  { id: 'he-h-069', word1: 'מיקום', word2: 'שוק', bridge: 'עמדת', difficulty: 'hard' },
  { id: 'he-h-070', word1: 'פרמטר', word2: 'הגדרה', bridge: 'שינוי', difficulty: 'hard' },
  { id: 'he-h-071', word1: 'קונספט', word2: 'מסגרת', bridge: 'מושגי', difficulty: 'hard' },
  { id: 'he-h-072', word1: 'תרחיש', word2: 'תכנון', bridge: 'תשתית', difficulty: 'hard' },
  { id: 'he-h-073', word1: 'השפעה', word2: 'מדידה', bridge: 'מדד', difficulty: 'hard' },
  { id: 'he-h-074', word1: 'מחזור', word2: 'חיים', bridge: 'מוצר', difficulty: 'hard' },
  { id: 'he-h-075', word1: 'ממשק', word2: 'כלים', bridge: 'פיתוח', difficulty: 'hard' },
  { id: 'he-h-076', word1: 'אוטונומיה', word2: 'פעולה', bridge: 'חופש', difficulty: 'hard' },
  { id: 'he-h-077', word1: 'מבנה', word2: 'רשת', bridge: 'ארגוני', difficulty: 'hard' },
  { id: 'he-h-078', word1: 'עקרון', word2: 'ניהול', bridge: 'שיטת', difficulty: 'hard' },
  { id: 'he-h-079', word1: 'תרבות', word2: 'ניהול', bridge: 'ארגונית', difficulty: 'hard' },
  { id: 'he-h-080', word1: 'אג"ח', word2: 'ריבית', bridge: 'שוק', difficulty: 'hard', hint: 'שוק אגרות החוב' },
];
