import type { ConnectionPuzzle } from '../types';

export const HE_HARD: ConnectionPuzzle[] = [
  { id: 'he-h-001', word1: 'אור', word2: 'לתנועה', bridge: 'ירוק', difficulty: 'hard', hint: 'אישור להתקדם' },
  { id: 'he-h-003', word1: 'לב', word2: 'טהור', bridge: 'זהב', difficulty: 'hard' },
  { id: 'he-h-004', word1: 'ראש', word2: 'לחשיבה', bridge: 'פתוח', difficulty: 'hard' },
  { id: 'he-h-006', word1: 'אוזן', word2: 'שומעת', bridge: 'קשבת', difficulty: 'hard' },
  { id: 'he-h-009', word1: 'דם', word2: 'עולה', bridge: 'חם', difficulty: 'hard' },
  { id: 'he-h-010', word1: 'מים', word2: 'קרים', bridge: 'חיים', difficulty: 'hard' },
  { id: 'he-h-018', word1: 'כוכב', word2: 'לכת', bridge: 'שביט', difficulty: 'hard' },
  { id: 'he-h-019', word1: 'ירח', word2: 'מתוק', bridge: 'דבש', difficulty: 'hard' },
  { id: 'he-h-021', word1: 'זריחה', word2: 'בוקר', bridge: 'שמש', difficulty: 'hard' },
  { id: 'he-h-023', word1: 'ערפל', word2: 'סמיך', bridge: 'בוקר', difficulty: 'hard' },
  { id: 'he-h-024', word1: 'טל', word2: 'חיים', bridge: 'בוקר', difficulty: 'hard' },
  { id: 'he-h-025', word1: 'מטר', word2: 'ראשון', bridge: 'גשם', difficulty: 'hard' },
  { id: 'he-h-026', word1: 'שלולית', word2: 'בחורף', bridge: 'גשם', difficulty: 'hard' },
  { id: 'he-h-028', word1: 'זית', word2: 'אחרון', bridge: 'שמן', difficulty: 'hard' },
  { id: 'he-h-030', word1: 'חיטה', word2: 'חדש', bridge: 'יבול', difficulty: 'hard' },
  { id: 'he-h-032', word1: 'דגן', word2: 'שחור', bridge: 'לחם', difficulty: 'hard' },
  { id: 'he-h-036', word1: 'חמאת', word2: 'שחור', bridge: 'בוטנים', difficulty: 'hard' },
  { id: 'he-h-037', word1: 'ריבת', word2: 'טעים', bridge: 'תותים', difficulty: 'hard' },
  { id: 'he-h-039', word1: 'שמנת', word2: 'לבישול', bridge: 'מתוקה', difficulty: 'hard' },
  { id: 'he-h-040', word1: 'קצפת', word2: 'שחורה', bridge: 'עוגת', difficulty: 'hard' },
  { id: 'he-h-041', word1: 'גלידת', word2: 'לבנה', bridge: 'שוקולד', difficulty: 'hard' },
  { id: 'he-h-042', word1: 'עוגיית', word2: 'חמאה', bridge: 'שוקולד', difficulty: 'hard' },
  { id: 'he-h-044', word1: 'מלח', word2: 'המלח', bridge: 'ים', difficulty: 'hard' },
  { id: 'he-h-045', word1: 'פלפל', word2: 'מתוק', bridge: 'שחור', difficulty: 'hard' },
  { id: 'he-h-048', word1: 'מחבת', word2: 'כבד', bridge: 'ברזל', difficulty: 'hard' },
  { id: 'he-h-049', word1: 'קומקום', word2: 'מהיר', bridge: 'חשמלי', difficulty: 'hard' },
  { id: 'he-h-050', word1: 'מחבתית', word2: 'דקה', bridge: 'טפלון', difficulty: 'hard' },
  { id: 'he-h-052', word1: 'כף', word2: 'רגל', bridge: 'יד', difficulty: 'hard' },
  { id: 'he-h-053', word1: 'מזלג', word2: 'גדול', bridge: 'כסף', difficulty: 'hard' },
  { id: 'he-h-056', word1: 'קערת', word2: 'ירקות', bridge: 'סלט', difficulty: 'hard' },
  { id: 'he-h-061', word1: 'פנס', word2: 'ראשי', bridge: 'רחוב', difficulty: 'hard' },
  { id: 'he-h-080', word1: 'מפתח', word2: 'שחור', bridge: 'שמש', difficulty: 'hard' },
  { id: 'he-h-081', word1: 'מטרייה', word2: 'משומשת', bridge: 'גשם', difficulty: 'hard' },
  { id: 'he-h-083', word1: 'כפפת', word2: 'שמאל', bridge: 'יד', difficulty: 'hard' },
  { id: 'he-h-087', word1: 'כובע', word2: 'גבוה', bridge: 'קש', difficulty: 'hard' },
  { id: 'he-h-088', word1: 'חולצת', word2: 'פולו', bridge: 'טריקו', difficulty: 'hard' },
  { id: 'he-h-097', word1: 'ספת', word2: 'שחורה', bridge: 'עור', difficulty: 'hard' },
  { id: 'he-h-105', word1: 'מרתף', word2: 'עמוק', bridge: 'יין', difficulty: 'hard' },
  { id: 'he-h-108', word1: 'מעלית', word2: 'מנהלים', bridge: 'שירות', difficulty: 'hard' },
  { id: 'he-h-109', word1: 'פעמון', word2: 'מפתיעה', bridge: 'אזעקה', difficulty: 'hard' },
  { id: 'he-h-114', word1: 'פרק', word2: 'ארוך', bridge: 'זמן', difficulty: 'hard' },
  { id: 'he-h-116', word1: 'מסיבת', word2: 'הולדת', bridge: 'יום', difficulty: 'hard' },
  { id: 'he-h-117', word1: 'חגיגת', word2: 'הולדת', bridge: 'יום', difficulty: 'hard' },
  { id: 'he-h-118', word1: 'הפתעת', word2: 'אחרון', bridge: 'רגע', difficulty: 'hard' },
  { id: 'he-h-119', word1: 'מתנת', word2: 'טוב', bridge: 'מזל', difficulty: 'hard' },
  { id: 'he-h-120', word1: 'ברכת', word2: 'טוב', bridge: 'מזל', difficulty: 'hard' },
];
