import type { ConnectionPuzzle } from '../types';

export const HE_HARD: ConnectionPuzzle[] = [
  { id: 'he-h-001', word1: 'אור', word2: 'בהיר', bridge: 'ירוק', difficulty: 'hard', hint: 'אישור להתקדם' },
  { id: 'he-h-003', word1: 'לב', word2: 'טהור', bridge: 'זהב', difficulty: 'hard' },
  { id: 'he-h-010', word1: 'מים', word2: 'קלים', bridge: 'חיים', difficulty: 'hard' },
  { id: 'he-h-019', word1: 'ירח', word2: 'מתוק', bridge: 'דבש', difficulty: 'hard' },
  { id: 'he-h-021', word1: 'זריחת', word2: 'בוקר', bridge: 'שמש', difficulty: 'hard' },
  { id: 'he-h-024', word1: 'טל', word2: 'טוב', bridge: 'בוקר', difficulty: 'hard' },
  { id: 'he-h-025', word1: 'מטר', word2: 'ראשון', bridge: 'גשם', difficulty: 'hard' },
  { id: 'he-h-026', word1: 'שלולית', word2: 'שוטף', bridge: 'גשם', difficulty: 'hard' },
  { id: 'he-h-036', word1: 'חמאת', word2: 'קלויים', bridge: 'בוטנים', difficulty: 'hard' },
  { id: 'he-h-037', word1: 'ריבת', word2: 'טעימים', bridge: 'תותים', difficulty: 'hard' },
  { id: 'he-h-039', word1: 'גבינת', word2: 'לבישול', bridge: 'שמנת', difficulty: 'hard' },
  { id: 'he-h-041', word1: 'גלידת', word2: 'לבן', bridge: 'שוקולד', difficulty: 'hard' },
  { id: 'he-h-042', word1: 'עוגיית', word2: 'חלב', bridge: 'שוקולד', difficulty: 'hard' },
  { id: 'he-h-044', word1: 'מלח', word2: 'המלח', bridge: 'ים', difficulty: 'hard' },
  { id: 'he-h-048', word1: 'מחבת', word2: 'כבד', bridge: 'ברזל', difficulty: 'hard' },
  { id: 'he-h-052', word1: 'כף', word2: 'ימין', bridge: 'יד', difficulty: 'hard' },
  { id: 'he-h-056', word1: 'קערת', word2: 'ירקות', bridge: 'סלט', difficulty: 'hard' },
  { id: 'he-h-061', word1: 'פנס', word2: 'ראשי', bridge: 'רחוב', difficulty: 'hard' },
  { id: 'he-h-081', word1: 'טיפת', word2: 'חזק', bridge: 'גשם', difficulty: 'hard' },
  { id: 'he-h-083', word1: 'כפפת', word2: 'שמאל', bridge: 'יד', difficulty: 'hard' },
  { id: 'he-h-087', word1: 'כובע', word2: 'יבש', bridge: 'קש', difficulty: 'hard' },
  { id: 'he-h-088', word1: 'חולצת', word2: 'ארוך', bridge: 'טריקו', difficulty: 'hard' },
  { id: 'he-h-097', word1: 'ספת', word2: 'שחור', bridge: 'עור', difficulty: 'hard' },
  { id: 'he-h-105', word1: 'מרתף', word2: 'אדום', bridge: 'יין', difficulty: 'hard' },
  { id: 'he-h-108', word1: 'מעלית', word2: 'לקוחות', bridge: 'שירות', difficulty: 'hard' },
  { id: 'he-h-109', word1: 'פעמון', word2: 'מפתיעה', bridge: 'אזעקה', difficulty: 'hard' },
  { id: 'he-h-114', word1: 'פרק', word2: 'ארוך', bridge: 'זמן', difficulty: 'hard' },
  { id: 'he-h-116', word1: 'מסיבת', word2: 'הולדת', bridge: 'יום', difficulty: 'hard' },
  { id: 'he-h-117', word1: 'חגיגת', word2: 'הולדת', bridge: 'יום', difficulty: 'hard' },
  { id: 'he-h-119', word1: 'מתנת', word2: 'טוב', bridge: 'מזל', difficulty: 'hard' },
];
