/**
 * The exported PDF must not be half-translated.
 *
 * `ClassReport` already threads `t` in and uses it for section titles, then
 * hardcodes English right beside it: `Teacher:`, `Total Students`, `Active
 * Students`, `Class Average Accuracy`, `Completion Rate`, `Top Performers`,
 * `Student Rankings`, and every table column header. A Hebrew teacher exported a
 * class report and got Hebrew headings over English metric labels.
 *
 * Nearly all of the keys already existed under `teacher.reports.metrics.*`,
 * `sections.*` and `columns.*` — the file simply was not using them.
 *
 * This test renders with a `t` that returns the KEY, so any literal English left
 * in the tree shows up as itself and fails.
 */
import React from 'react';
import { render, screen } from '@testing-library/react';

vi.mock('@react-pdf/renderer', () => ({
  Document: ({ children }: { children: React.ReactNode }) => <div>{children}</div>,
  Page: ({ children }: { children: React.ReactNode }) => <div>{children}</div>,
  View: ({ children }: { children: React.ReactNode }) => <div>{children}</div>,
  Text: ({ children }: { children: React.ReactNode }) => <span>{children}</span>,
  StyleSheet: { create: (s: Record<string, unknown>) => s },
  Font: { register: vi.fn() },
}));

vi.mock('@/contexts/LanguageContext', () => ({
  useLanguage: () => ({ t: (key: string) => key, language: 'he', dir: 'rtl' }),
}));

import { ProgressReportPDF, type ClassReportPDFData } from '../ProgressReportPDF';

const CLASS_DATA: ClassReportPDFData = {
  type: 'class',
  classroomName: 'ELA (7th)',
  teacherName: 'Ms Plant',
  generatedAt: new Date('2026-09-05T10:00:00Z'),
  metrics: {
    totalStudents: 5,
    activeStudents: 4,
    classAverageAccuracy: 82,
    completionRate: 60,
  },
  topPerformers: [{ studentName: 'Maya', accuracy: 94, wordsLearned: 21 }],
  studentRankings: [{ rank: 1, studentName: 'Maya', score: 310, accuracy: 94, wordsLearned: 21 }],
};

/**
 * Multi-word literals that used to be baked into the class report in English.
 *
 * The single-word column headers (Rank / Student / Score / Words / Accuracy) are
 * NOT scanned as substrings: they appear inside the key names themselves
 * (`sections.studentRankings` contains "Rank"), so a substring scan would fail
 * on a correct render. They are asserted by key in the third test instead.
 */
const LEAKED_ENGLISH = [
  'Total Students',
  'Active Students',
  'Class Average Accuracy',
  'Completion Rate',
  'Top Performers',
  'Student Rankings',
  'Generated by LexiClash',
  'Teacher: ',
];

describe('ProgressReportPDF class report — every label goes through t()', () => {
  it('leaves no hardcoded English label in the tree', () => {
    // GIVEN a Hebrew teacher exporting a class report
    const { container } = render(<ProgressReportPDF data={CLASS_DATA} />);
    const text = container.textContent ?? '';

    // THEN none of the old literals survive
    for (const literal of LEAKED_ENGLISH) {
      expect(text).not.toContain(literal);
    }
  });

  it('renders the metric labels from their existing translation keys', () => {
    // GIVEN the same report
    render(<ProgressReportPDF data={CLASS_DATA} />);

    // THEN the keys that already existed are the ones being used
    expect(screen.getByText('teacher.reports.metrics.totalStudents')).toBeInTheDocument();
    expect(screen.getByText('teacher.reports.metrics.activeStudents')).toBeInTheDocument();
    expect(screen.getByText('teacher.reports.metrics.classAverageAccuracy')).toBeInTheDocument();
    expect(screen.getByText('teacher.reports.metrics.completionRate')).toBeInTheDocument();
    expect(screen.getByText('teacher.reports.sections.topPerformers')).toBeInTheDocument();
    expect(screen.getByText('teacher.reports.sections.studentRankings')).toBeInTheDocument();
  });

  it('translates the teacher line and the ranking column headers', () => {
    // GIVEN the same report
    render(<ProgressReportPDF data={CLASS_DATA} />);

    // THEN the labels that had no key yet now have one
    expect(screen.getByText(/teacher\.reports\.teacherLabel/)).toBeInTheDocument();
    expect(screen.getByText('teacher.reports.columns.rank')).toBeInTheDocument();
    expect(screen.getByText('teacher.reports.columns.student')).toBeInTheDocument();
    expect(screen.getByText('teacher.reports.columns.score')).toBeInTheDocument();
    expect(screen.getByText('teacher.reports.columns.words')).toBeInTheDocument();
  });
});
