/**
 * The PDF is rendered by `pdf(<ProgressReportPDF/>)` — react-pdf's own root,
 * with NO LanguageProvider above it. When the document called `useLanguage()`
 * itself, dev threw (export silently did nothing) and prod fell back to the
 * default locale: a Hebrew teacher's PDF came out in English. The older i18n
 * test mocked `useLanguage`, which mocked away exactly the broken thing.
 *
 * Here `useLanguage` THROWS if touched, and `t` returns the key plus its params,
 * so any literal English left in the tree shows up as itself.
 */
import React from 'react';
import { render } from '@testing-library/react';

vi.mock('@react-pdf/renderer', () => ({
  Document: ({ children }: { children: React.ReactNode }) => <div>{children}</div>,
  Page: ({ children }: { children: React.ReactNode }) => <div>{children}</div>,
  View: ({ children }: { children: React.ReactNode }) => <div>{children}</div>,
  Text: ({ children }: { children?: React.ReactNode }) => <span>{children}</span>,
  StyleSheet: { create: (s: Record<string, unknown>) => s },
  Font: { register: vi.fn(), registerHyphenationCallback: vi.fn() },
}));

vi.mock('@/contexts/LanguageContext', () => ({
  useLanguage: () => {
    throw new Error('ProgressReportPDF must not read LanguageContext');
  },
}));

import {
  ProgressReportPDF,
  type StudentReportPDFData,
  type ClassReportPDFData,
} from '../ProgressReportPDF';

const t = (key: string, params?: Record<string, string | number> | string) =>
  params && typeof params === 'object' ? `${key}${JSON.stringify(params)}` : key;

const STUDENT: StudentReportPDFData = {
  type: 'student',
  studentName: 'מאיה',
  classroomName: 'ז׳ 2',
  generatedAt: new Date('2026-09-05T10:00:00Z'),
  metrics: {
    wordsLearned: 12,
    totalWords: 20,
    accuracy: 84,
    practiceTimeMinutes: 65,
    currentStreak: 3,
    longestStreak: 9,
    sessionsCompleted: 7,
    averageScore: 310,
    masteryLevel: 'developing',
  },
  wordMastery: [
    { word: 'שלום', mastered: true, accuracy: 100, attempts: 4 },
    { word: 'ספר', mastered: false, accuracy: 50, attempts: 6 },
  ],
  recommendations: ['low_accuracy_focus'],
};

const CLASS: ClassReportPDFData = {
  type: 'class',
  classroomName: 'ELA 7',
  teacherName: 'Ms Plant',
  generatedAt: new Date('2026-09-05T10:00:00Z'),
  metrics: {
    totalStudents: 5,
    activeStudents: 4,
    classAverageAccuracy: 82,
    classAverageWordsLearned: 11,
    completionRate: 60,
    participationRate: 80,
  },
  topPerformers: [{ studentName: 'Maya', accuracy: 94, wordsLearned: 21 }],
  studentsNeedingAttention: [{ studentName: 'Noam', accuracy: 31, issue: 'low_accuracy' }],
  studentRankings: [{ rank: 1, studentName: 'Maya', score: 310, accuracy: 94, wordsLearned: 21 }],
};

const renderText = (data: StudentReportPDFData | ClassReportPDFData, language = 'he') =>
  render(
    <ProgressReportPDF data={data} t={t} language={language} dir={language === 'he' ? 'rtl' : 'ltr'} />
  ).container.textContent ?? '';

describe('ProgressReportPDF — rendered outside the app tree', () => {
  it('renders a student report without touching LanguageContext', () => {
    // GIVEN a Hebrew teacher's student export WHEN rendered with props only
    // THEN it renders (the mock throws if useLanguage is called)
    expect(renderText(STUDENT)).toContain('מאיה');
  });

  it('leaves no hardcoded English in the student report', () => {
    const text = renderText(STUDENT);
    for (const literal of ['Mastered', 'Practicing', ' days', '1h 5m', 'Generated by']) {
      expect(text).not.toContain(literal);
    }
  });

  it('routes status, streak and duration through their existing keys', () => {
    const text = renderText(STUDENT);
    expect(text).toContain('teacher.reports.mastery.mastered');
    expect(text).toContain('teacher.reports.mastery.practicing');
    expect(text).toContain('teacher.reports.streakDays{"count":3}');
    expect(text).toContain('teacher.reports.practiceDuration{"hours":1,"minutes":5}');
  });

  it('prints the recommendations the on-screen report shows', () => {
    expect(renderText(STUDENT)).toContain('teacher.reports.recommendations.lowAccuracyFocus');
  });

  it('formats the date in the teacher language, not en-US', () => {
    // GIVEN language he WHEN rendered THEN the month is Hebrew
    expect(renderText(STUDENT, 'he')).toContain('בספטמבר');
    expect(renderText(STUDENT, 'en')).toContain('September');
  });

  it('leaves no hardcoded English in the class report', () => {
    const text = renderText(CLASS);
    expect(text).not.toMatch(/\d+ words/);
    expect(text).not.toContain('Teacher: ');
    expect(text).toContain('teacher.reports.teacherLine{"name":"Ms Plant"}');
    expect(text).toContain('education.classroomGame.words{"count":21}');
  });

  it('prints the students who need attention with a translated issue', () => {
    const text = renderText(CLASS);
    expect(text).toContain('Noam');
    expect(text).toContain('teacher.reports.issue.lowAccuracy');
  });
});
