import { supabase } from '@/lib/supabase';
import logger from '@/utils/logger';

// Types matching database schema from migration 056
export type Language = 'en' | 'he' | 'sv' | 'ja';

export interface Classroom {
  id: string;
  teacher_id: string;
  name: string;
  join_code: string;
  language: Language;
  created_at: string;
  updated_at: string;
  member_count?: number;
}

export interface VocabularyWord {
  word: string;
  definition?: string;
  canIntegrate: boolean;
}

export interface VocabularyLesson {
  id: string;
  teacher_id: string;
  classroom_id: string | null;
  name: string;
  description: string | null;
  language: Language;
  words: VocabularyWord[];
  is_public: boolean;
  source_game_code: string | null;
  created_at: string;
  updated_at: string;
}

export interface WordAttempt {
  attempts: number;
  correct: number;
  lastAttemptAt: string;
}

export interface StudentLessonProgress {
  id: string;
  student_id: string;
  lesson_id: string;
  assignment_id: string | null;
  words_attempted: Record<string, WordAttempt>;
  words_mastered: string[];
  started_at: string;
  completed_at: string | null;
}

export interface ClassroomWithMembers extends Classroom {
  member_count: number;
}

// =============================================
// CLASSROOM QUERIES
// =============================================

/**
 * Get all classrooms for a teacher
 */
export async function getClassrooms(teacherId: string): Promise<{ data: ClassroomWithMembers[]; error: { message: string } | null }> {
  if (!supabase) return { data: [], error: { message: 'Supabase not configured' } };

  try {
    // Get classrooms with member count
    const { data: classrooms, error: classroomsError } = await supabase
      .from('classrooms')
      .select('*')
      .eq('teacher_id', teacherId)
      .order('created_at', { ascending: false });

    if (classroomsError) {
      logger.error('Error fetching classrooms:', classroomsError);
      return { data: [], error: { message: classroomsError.message } };
    }

    if (!classrooms || classrooms.length === 0) {
      return { data: [], error: null };
    }

    // Get member counts for all classrooms in one query
    const { data: memberships, error: membershipsError } = await supabase
      .from('classroom_memberships')
      .select('classroom_id')
      .in('classroom_id', classrooms.map(c => c.id));

    if (membershipsError) {
      logger.error('Error fetching memberships:', membershipsError);
      // Return classrooms without member counts rather than failing
      return {
        data: classrooms.map(c => ({ ...c, member_count: 0 })),
        error: null
      };
    }

    // Count members per classroom
    const memberCounts = (memberships || []).reduce((acc, m) => {
      acc[m.classroom_id] = (acc[m.classroom_id] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    // Attach member counts
    const classroomsWithCounts = classrooms.map(classroom => ({
      ...classroom,
      member_count: memberCounts[classroom.id] || 0
    }));

    return { data: classroomsWithCounts, error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in getClassrooms:', error);
    return { data: [], error: { message: error } };
  }
}

/**
 * Get a single classroom by ID
 */
export async function getClassroom(classroomId: string): Promise<{ data: ClassroomWithMembers | null; error: { message: string } | null }> {
  if (!supabase) return { data: null, error: { message: 'Supabase not configured' } };

  try {
    const { data: classroom, error: classroomError } = await supabase
      .from('classrooms')
      .select('*')
      .eq('id', classroomId)
      .single();

    if (classroomError) {
      logger.error('Error fetching classroom:', classroomError);
      return { data: null, error: { message: classroomError.message } };
    }

    // Get member count
    const { count, error: countError } = await supabase
      .from('classroom_memberships')
      .select('*', { count: 'exact', head: true })
      .eq('classroom_id', classroomId);

    if (countError) {
      logger.error('Error counting members:', countError);
      return { data: { ...classroom, member_count: 0 }, error: null };
    }

    return { data: { ...classroom, member_count: count || 0 }, error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in getClassroom:', error);
    return { data: null, error: { message: error } };
  }
}

/**
 * Create a new classroom (join_code auto-generated by trigger)
 */
export async function createClassroom(
  data: Omit<Classroom, 'id' | 'join_code' | 'created_at' | 'updated_at' | 'member_count'>
): Promise<{ data: Classroom | null; error: { message: string } | null }> {
  if (!supabase) return { data: null, error: { message: 'Supabase not configured' } };

  try {
    const { data: classroom, error } = await supabase
      .from('classrooms')
      .insert(data)
      .select()
      .single();

    if (error) {
      logger.error('Error creating classroom:', error);
      return { data: null, error: { message: error.message } };
    }

    return { data: classroom, error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in createClassroom:', error);
    return { data: null, error: { message: error } };
  }
}

/**
 * Update a classroom
 */
export async function updateClassroom(
  id: string,
  updates: Partial<Pick<Classroom, 'name' | 'language'>>
): Promise<{ data: Classroom | null; error: { message: string } | null }> {
  if (!supabase) return { data: null, error: { message: 'Supabase not configured' } };

  try {
    const { data: classroom, error } = await supabase
      .from('classrooms')
      .update(updates)
      .eq('id', id)
      .select()
      .single();

    if (error) {
      logger.error('Error updating classroom:', error);
      return { data: null, error: { message: error.message } };
    }

    return { data: classroom, error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in updateClassroom:', error);
    return { data: null, error: { message: error } };
  }
}

/**
 * Delete a classroom (cascades to memberships via foreign key)
 */
export async function deleteClassroom(id: string): Promise<{ error: { message: string } | null }> {
  if (!supabase) return { error: { message: 'Supabase not configured' } };

  try {
    const { error } = await supabase
      .from('classrooms')
      .delete()
      .eq('id', id);

    if (error) {
      logger.error('Error deleting classroom:', error);
      return { error: { message: error.message } };
    }

    return { error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in deleteClassroom:', error);
    return { error: { message: error } };
  }
}

/**
 * Join a classroom using join code
 */
export async function joinClassroom(
  joinCode: string,
  studentId: string
): Promise<{ data: { classroom_id: string } | null; error: { message: string } | null }> {
  if (!supabase) return { data: null, error: { message: 'Supabase not configured' } };

  try {
    // Find classroom by join code
    const { data: classroom, error: classroomError } = await supabase
      .from('classrooms')
      .select('id')
      .eq('join_code', joinCode.toUpperCase())
      .single();

    if (classroomError || !classroom) {
      return { data: null, error: { message: 'Invalid join code' } };
    }

    // Check if already a member
    const { data: existing } = await supabase
      .from('classroom_memberships')
      .select('id')
      .eq('classroom_id', classroom.id)
      .eq('student_id', studentId)
      .maybeSingle();

    if (existing) {
      return { data: { classroom_id: classroom.id }, error: null };
    }

    // Add membership
    const { error: membershipError } = await supabase
      .from('classroom_memberships')
      .insert({
        classroom_id: classroom.id,
        student_id: studentId
      });

    if (membershipError) {
      logger.error('Error joining classroom:', membershipError);
      return { data: null, error: { message: membershipError.message } };
    }

    return { data: { classroom_id: classroom.id }, error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in joinClassroom:', error);
    return { data: null, error: { message: error } };
  }
}

// =============================================
// LESSON QUERIES
// =============================================

/**
 * Get all lessons for a teacher, optionally filtered by classroom
 */
export async function getLessons(
  teacherId: string,
  classroomId?: string
): Promise<{ data: VocabularyLesson[]; error: { message: string } | null }> {
  if (!supabase) return { data: [], error: { message: 'Supabase not configured' } };

  try {
    let query = supabase
      .from('vocabulary_lessons')
      .select('*')
      .eq('teacher_id', teacherId)
      .order('created_at', { ascending: false });

    if (classroomId) {
      query = query.eq('classroom_id', classroomId);
    }

    const { data, error } = await query;

    if (error) {
      logger.error('Error fetching lessons:', error);
      return { data: [], error: { message: error.message } };
    }

    return { data: data || [], error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in getLessons:', error);
    return { data: [], error: { message: error } };
  }
}

/**
 * Get a single lesson by ID
 */
export async function getLesson(lessonId: string): Promise<{ data: VocabularyLesson | null; error: { message: string } | null }> {
  if (!supabase) return { data: null, error: { message: 'Supabase not configured' } };

  try {
    const { data, error } = await supabase
      .from('vocabulary_lessons')
      .select('*')
      .eq('id', lessonId)
      .single();

    if (error) {
      logger.error('Error fetching lesson:', error);
      return { data: null, error: { message: error.message } };
    }

    return { data, error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in getLesson:', error);
    return { data: null, error: { message: error } };
  }
}

/**
 * Create a new vocabulary lesson
 */
export async function createLesson(
  data: Omit<VocabularyLesson, 'id' | 'created_at' | 'updated_at'>
): Promise<{ data: VocabularyLesson | null; error: { message: string } | null }> {
  if (!supabase) return { data: null, error: { message: 'Supabase not configured' } };

  try {
    const { data: lesson, error } = await supabase
      .from('vocabulary_lessons')
      .insert(data)
      .select()
      .single();

    if (error) {
      logger.error('Error creating lesson:', error);
      return { data: null, error: { message: error.message } };
    }

    return { data: lesson, error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in createLesson:', error);
    return { data: null, error: { message: error } };
  }
}

/**
 * Update a vocabulary lesson
 */
export async function updateLesson(
  id: string,
  updates: Partial<Omit<VocabularyLesson, 'id' | 'teacher_id' | 'created_at' | 'updated_at'>>
): Promise<{ data: VocabularyLesson | null; error: { message: string } | null }> {
  if (!supabase) return { data: null, error: { message: 'Supabase not configured' } };

  try {
    const { data: lesson, error } = await supabase
      .from('vocabulary_lessons')
      .update(updates)
      .eq('id', id)
      .select()
      .single();

    if (error) {
      logger.error('Error updating lesson:', error);
      return { data: null, error: { message: error.message } };
    }

    return { data: lesson, error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in updateLesson:', error);
    return { data: null, error: { message: error } };
  }
}

/**
 * Delete a vocabulary lesson
 */
export async function deleteLesson(id: string): Promise<{ error: { message: string } | null }> {
  if (!supabase) return { error: { message: 'Supabase not configured' } };

  try {
    const { error } = await supabase
      .from('vocabulary_lessons')
      .delete()
      .eq('id', id);

    if (error) {
      logger.error('Error deleting lesson:', error);
      return { error: { message: error.message } };
    }

    return { error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in deleteLesson:', error);
    return { error: { message: error } };
  }
}

// =============================================
// PROGRESS QUERIES
// =============================================

/**
 * Get student progress for a specific lesson or all lessons
 */
export async function getStudentProgress(
  studentId: string,
  lessonId?: string
): Promise<{ data: StudentLessonProgress[]; error: { message: string } | null }> {
  if (!supabase) return { data: [], error: { message: 'Supabase not configured' } };

  try {
    let query = supabase
      .from('student_lesson_progress')
      .select('*')
      .eq('student_id', studentId)
      .order('started_at', { ascending: false });

    if (lessonId) {
      query = query.eq('lesson_id', lessonId);
    }

    const { data, error } = await query;

    if (error) {
      logger.error('Error fetching student progress:', error);
      return { data: [], error: { message: error.message } };
    }

    return { data: data || [], error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in getStudentProgress:', error);
    return { data: [], error: { message: error } };
  }
}

/**
 * Get progress for all students in a classroom for a specific lesson
 */
export async function getClassProgress(
  classroomId: string,
  lessonId: string
): Promise<{ data: StudentLessonProgress[]; error: { message: string } | null }> {
  if (!supabase) return { data: [], error: { message: 'Supabase not configured' } };

  try {
    // Get all student IDs in the classroom
    const { data: memberships, error: memberError } = await supabase
      .from('classroom_memberships')
      .select('student_id')
      .eq('classroom_id', classroomId);

    if (memberError) {
      logger.error('Error fetching classroom members:', memberError);
      return { data: [], error: { message: memberError.message } };
    }

    if (!memberships || memberships.length === 0) {
      return { data: [], error: null };
    }

    const studentIds = memberships.map(m => m.student_id);

    // Get progress for all students in the lesson
    const { data, error } = await supabase
      .from('student_lesson_progress')
      .select('*')
      .eq('lesson_id', lessonId)
      .in('student_id', studentIds)
      .order('started_at', { ascending: false });

    if (error) {
      logger.error('Error fetching class progress:', error);
      return { data: [], error: { message: error.message } };
    }

    return { data: data || [], error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in getClassProgress:', error);
    return { data: [], error: { message: error } };
  }
}

/**
 * Update student progress for a word attempt
 */
export async function updateProgress(
  studentId: string,
  lessonId: string,
  wordAttempt: { word: string; correct: boolean }
): Promise<{ data: StudentLessonProgress | null; error: { message: string } | null }> {
  if (!supabase) return { data: null, error: { message: 'Supabase not configured' } };

  try {
    // Get existing progress or create new
    const { data: existing, error: fetchError } = await supabase
      .from('student_lesson_progress')
      .select('*')
      .eq('student_id', studentId)
      .eq('lesson_id', lessonId)
      .maybeSingle();

    if (fetchError) {
      logger.error('Error fetching progress:', fetchError);
      return { data: null, error: { message: fetchError.message } };
    }

    const now = new Date().toISOString();
    const { word, correct } = wordAttempt;

    if (existing) {
      // Update existing progress
      const wordsAttempted = existing.words_attempted || {};
      const currentAttempt = wordsAttempted[word] || { attempts: 0, correct: 0, lastAttemptAt: now };

      const updatedAttempt: WordAttempt = {
        attempts: currentAttempt.attempts + 1,
        correct: currentAttempt.correct + (correct ? 1 : 0),
        lastAttemptAt: now
      };

      wordsAttempted[word] = updatedAttempt;

      // Check if word should be marked as mastered (3+ correct attempts)
      const wordsMastered = existing.words_mastered || [];
      if (correct && updatedAttempt.correct >= 3 && !wordsMastered.includes(word)) {
        wordsMastered.push(word);
      }

      const { data: updated, error: updateError } = await supabase
        .from('student_lesson_progress')
        .update({
          words_attempted: wordsAttempted,
          words_mastered: wordsMastered
        })
        .eq('id', existing.id)
        .select()
        .single();

      if (updateError) {
        logger.error('Error updating progress:', updateError);
        return { data: null, error: { message: updateError.message } };
      }

      return { data: updated, error: null };
    } else {
      // Create new progress record
      const wordsAttempted: Record<string, WordAttempt> = {
        [word]: {
          attempts: 1,
          correct: correct ? 1 : 0,
          lastAttemptAt: now
        }
      };

      const wordsMastered = correct ? [] : []; // Need 3 correct for mastery

      const { data: created, error: createError } = await supabase
        .from('student_lesson_progress')
        .insert({
          student_id: studentId,
          lesson_id: lessonId,
          words_attempted: wordsAttempted,
          words_mastered: wordsMastered,
          started_at: now
        })
        .select()
        .single();

      if (createError) {
        logger.error('Error creating progress:', createError);
        return { data: null, error: { message: createError.message } };
      }

      return { data: created, error: null };
    }
  } catch (err) {
    const error = err instanceof Error ? err.message : 'Unknown error';
    logger.error('Exception in updateProgress:', error);
    return { data: null, error: { message: error } };
  }
}
