/**
 * Season placement badge registry.
 *
 * Top-5 finishers in each season earn a unique collectible badge.
 * Title is parameterized (rank-keyed) and the season name supplies
 * the "uniqueness" via image + theme. Image art is generated by
 * scripts/generate-season-badges.ts and lives in /public/badges/.
 */

const SEASON_THEMES = [
  'Word Warriors',
  'Letter Legends',
  'Vocab Victors',
  'Syllable Champions',
  'Phonic Phenoms',
  'Lexicon Lords',
];

const SEASON_ACCENT: Record<number, string> = {
  1: '#BFFF00',
  2: '#FF1493',
  3: '#00FFFF',
  4: '#8B5CF6',
  5: '#FFE135',
  6: '#FF6B35',
};

export const SEASON_BADGE_MAX_RANK = 5;

export type RankBadgeRarity = 'legendary' | 'epic' | 'rare' | 'uncommon';

export interface SeasonRankBadge {
  seasonId: number;
  rank: number;
  titleKey: string;
  imagePath: string;
  accentColor: string;
  rarity: RankBadgeRarity;
  theme: string;
}

export function isTopFiveRank(rank: number | undefined | null): boolean {
  if (typeof rank !== 'number') return false;
  return rank >= 1 && rank <= SEASON_BADGE_MAX_RANK;
}

export function seasonBadgeImagePath(seasonId: number, rank: number): string {
  return `/badges/season-${seasonId}-rank-${rank}.png`;
}

export function rankTitleKey(rank: number): string {
  return `seasonBadges.title.rank${rank}`;
}

export function rankBadgeRarity(rank: number): RankBadgeRarity {
  if (rank === 1) return 'legendary';
  if (rank === 2) return 'epic';
  if (rank === 3) return 'rare';
  return 'uncommon';
}

function themeForSeason(seasonId: number): string {
  const idx = ((seasonId - 1) % SEASON_THEMES.length + SEASON_THEMES.length) % SEASON_THEMES.length;
  return SEASON_THEMES[idx];
}

function accentForSeason(seasonId: number): string {
  if (SEASON_ACCENT[seasonId]) return SEASON_ACCENT[seasonId];
  // Cycle accents in lockstep with theme cycle for unmapped seasons.
  const cycleId = ((seasonId - 1) % 6 + 6) % 6 + 1;
  return SEASON_ACCENT[cycleId] ?? '#BFFF00';
}

export function getRankBadge(seasonId: number, rank: number): SeasonRankBadge | null {
  if (!isTopFiveRank(rank)) return null;
  if (!Number.isFinite(seasonId) || seasonId < 1) return null;
  return {
    seasonId,
    rank,
    titleKey: rankTitleKey(rank),
    imagePath: seasonBadgeImagePath(seasonId, rank),
    accentColor: accentForSeason(seasonId),
    rarity: rankBadgeRarity(rank),
    theme: themeForSeason(seasonId),
  };
}

/**
 * Filter a player's season-history rows down to top-5 placements,
 * returning ready-to-render badge metadata sorted by season DESC.
 */
export function selectEarnedBadges(
  history: Array<{ seasonId: number; rankPosition?: number }>,
): SeasonRankBadge[] {
  return history
    .filter((entry) => isTopFiveRank(entry.rankPosition))
    .map((entry) => getRankBadge(entry.seasonId, entry.rankPosition as number))
    .filter((b): b is SeasonRankBadge => b !== null)
    .sort((a, b) => b.seasonId - a.seasonId || a.rank - b.rank);
}
