/**
 * Socket Schemas - CommonJS Bridge
 *
 * Single source of truth: imports from shared/schemas/socketSchemas.ts
 * This file is compiled to CommonJS for Node.js compatibility.
 *
 * Build: npm run build:schemas
 */

export {
  LanguageSchema,
  AvatarSchema,
  GameCodeSchema,
  UsernameSchema,
  WordSchema,
  GridPositionSchema,
  DifficultySchema,
  BotDifficultySchema,
  PresenceStatusSchema,
  RoomNameSchema,
  PlayerIdSchema,
  GuestTokenHashSchema,

  CreateGameSchema,
  JoinGameSchema,
  LeaveRoomSchema,
  StartGameSchema,
  StartGameAckSchema,
  SubmitWordSchema,
  SubmitWordVoteSchema,
  SubmitPeerValidationVoteSchema,
  ChatMessageSchema,
  AddBotSchema,
  RemoveBotSchema,
  HeartbeatSchema,
  PresenceUpdateSchema,
  WindowFocusChangeSchema,
  KickPlayerSchema,
  TransferHostSchema,
  CreateTournamentSchema,
  GetWordsForBoardSchema,
  ResetGameSchema,
  CloseRoomSchema,
  ReconnectSchema,
  UpdateGameSettingsSchema,
  BroadcastShufflingGridSchema,
  GenerateScoreCardSchema,
  ApplyWordPackSchema,

  ClientEventSchemas,
  validatePayload,
  validateSocketEvent,
  safeValidateSocketEvent,
  getEventSchema,

  type ClientEventName,
  type Language,
  type Avatar,
  type GridPosition,
  type Difficulty,
  type BotDifficulty,
  type PresenceStatus,
  type CreateGameData,
  type JoinGameData,
  type LeaveRoomData,
  type StartGameData,
  type SubmitWordData,
  type ChatMessageData,
  type AddBotData,
  type RemoveBotData,
  type HeartbeatData,
  type PresenceUpdateData,
  type KickPlayerData,
  type TransferHostData,
  type CreateTournamentData,
  type ReconnectData,
  type ApplyWordPackData,
} from '../../shared/schemas/socketSchemas';

import { ClientEventSchemas } from '../../shared/schemas/socketSchemas';

export const eventSchemas = ClientEventSchemas;

export {
  LanguageSchema as languageSchema,
  AvatarSchema as avatarSchema,
  GameCodeSchema as gameCodeSchema,
  UsernameSchema as usernameSchema,
  WordSchema as wordSchema,
  GridPositionSchema as gridPositionSchema,
  DifficultySchema as difficultySchema,
  BotDifficultySchema as botDifficultySchema,
  PresenceStatusSchema as presenceStatusSchema,
  RoomNameSchema as roomNameSchema,
  PlayerIdSchema as playerIdSchema,
  GuestTokenHashSchema as guestTokenHashSchema,
  CreateGameSchema as createGameSchema,
  JoinGameSchema as joinGameSchema,
  LeaveRoomSchema as leaveRoomSchema,
  StartGameSchema as startGameSchema,
  StartGameAckSchema as startGameAckSchema,
  SubmitWordSchema as submitWordSchema,
  SubmitWordVoteSchema as submitWordVoteSchema,
  SubmitPeerValidationVoteSchema as submitPeerValidationVoteSchema,
  ChatMessageSchema as chatMessageSchema,
  AddBotSchema as addBotSchema,
  RemoveBotSchema as removeBotSchema,
  HeartbeatSchema as heartbeatSchema,
  PresenceUpdateSchema as presenceUpdateSchema,
  WindowFocusChangeSchema as windowFocusChangeSchema,
  KickPlayerSchema as kickPlayerSchema,
  TransferHostSchema as transferHostSchema,
  CreateTournamentSchema as createTournamentSchema,
  GetWordsForBoardSchema as getWordsForBoardSchema,
  ResetGameSchema as resetGameSchema,
  CloseRoomSchema as closeRoomSchema,
  ReconnectSchema as reconnectSchema,
  UpdateGameSettingsSchema as updateGameSettingsSchema,
  BroadcastShufflingGridSchema as broadcastShufflingGridSchema,
  GenerateScoreCardSchema as generateScoreCardSchema,
} from '../../shared/schemas/socketSchemas';
